"""
Générateur de backend : AST NOVA -> application FastAPI + SQLModel.

Un bloc `entity` devient une table SQLModel ; un bloc `api` associé devient
un routeur FastAPI avec les actions CRUD demandées (list/create/update/
delete/get, dans n'importe quelle langue à l'origine).
"""

from __future__ import annotations

from .. import keywords as kw
from ..ast_nodes import Email as _Email
from ..ast_nodes import Entity, NovaProgram, QueryFilter
from .utils import PY_TYPE_MAP, pluralize, to_ascii_identifier, to_pascal_case, to_snake_case

_HEADER = (
    "# " + "-" * 76 + "\n"
    "# Fichier généré automatiquement par le compilateur NOVA. Ne pas éditer\n"
    "# à la main : régénérez à partir du fichier .nova source (`nova compile`).\n"
    "# Auto-generated by the NOVA compiler. Do not edit by hand: regenerate\n"
    "# from the source .nova file (`nova compile`).\n"
    "# " + "-" * 76 + "\n"
)


def _model_class_name(entity: Entity) -> str:
    return to_pascal_case(entity.name)


def _table_name(entity: Entity) -> str:
    return to_snake_case(pluralize(to_ascii_identifier(entity.name)))


def _multilingual_column_names(f, active_langs: list[str]) -> list[str]:
    """Un champ `chaine`/`texte multilingue` devient une colonne par langue
    ACTIVE du projet (`<champ>_fr`, `<champ>_en`, ... — toutes les 6 langues
    du DSL par défaut, ou le sous-ensemble choisi via `application {
    langues: fr, en }`, voir `NovaProgram.active_languages`), pas une seule
    colonne. Voir parser._validate_multilingual_fields pour les contraintes
    associées."""
    base = to_snake_case(f.name)
    return [f"{base}_{lang}" for lang in active_langs]


def _multilingual_model_lines(f, active_langs: list[str]) -> list[str]:
    """Colonnes de table SQLModel pour un champ multilingue : toutes
    `Optional[str]` (voir parser._validate_multilingual_fields — `requis`/
    `unique`/`motif` sont interdits sur un champ `multilingue` dans ce
    MVP, donc pas de cas à gérer ici au-delà d'un simple champ optionnel)."""
    return [f"    {col}: Optional[str] = Field(default=None)" for col in _multilingual_column_names(f, active_langs)]


def _multilingual_schema_lines(f, active_langs: list[str]) -> list[str]:
    """Mêmes colonnes que `_multilingual_model_lines`, pour les schémas
    Create/Update — syntaxe légèrement différente (pas de `Field(...)`),
    cohérente avec le reste de `_generate_models` pour un champ optionnel
    sans contrainte."""
    return [f"    {col}: Optional[str] = None" for col in _multilingual_column_names(f, active_langs)]


def _field_line(entity: Entity, f) -> str:
    if not f.is_reference:
        py_type = PY_TYPE_MAP.get(f.type, "str")
        type_hint = py_type if f.required else f"Optional[{py_type}]"
        opts = []
        if f.unique:
            opts.append("unique=True")
        if f.pattern:
            opts.append(f'pattern=r"{f.pattern}"')
        if f.default is not None:
            opts.append(f"default={f.default!r}")
        elif not f.required:
            opts.append("default=None")
        opts_str = ", ".join(opts)
        suffix = f" = Field({opts_str})" if opts_str else ""
        return f"    {to_snake_case(f.name)}: {type_hint}{suffix}"
    else:
        # Référence vers une autre entité : clé étrangère simple sur son id.
        target_table = to_snake_case(pluralize(to_ascii_identifier(f.type)))
        return (
            f"    {to_snake_case(f.name)}_id: Optional[int] = "
            f'Field(default=None, foreign_key="{target_table}.id")'
        )


def _relation_display_field(entity: Entity):
    """Choisit le champ « titre » d'une entité enfant pour résumer ses
    enregistrements liés (relation `has_many`, voir `_generate_router`) :
    le premier champ simple (ni référence, ni multilingue — un champ
    multilingue serait éclaté en 6 colonnes, trop de complexité pour un
    simple résumé) déclaré sur l'entité, ou `None` si elle n'en a aucun
    (repli sur son `id`, voir les appelants)."""
    for f in entity.fields:
        if not f.is_reference and not f.multilingual:
            return f
    return None


def _has_many_relation_info(entity: Entity, program: NovaProgram):
    """Pour chaque relation `has_many` de `entity` dont la cible existe et
    porte bien un `belongs_to` en retour (garanti par
    `parser._validate_relations` à la compilation — ici on ignore
    simplement une relation invalide plutôt que de planter, au cas où cette
    fonction soit appelée sur un AST construit à la main dans un test),
    retourne un tuple (classe_python_enfant, table_enfant, colonne_cle_
    etrangere_cote_enfant, nom_du_champ_resume_texte, attribut_python_du_
    champ_titre_ou_None)."""
    info = []
    for rel in entity.relations:
        if rel.kind != "has_many":
            continue
        child = program.get_entity(rel.target)
        if child is None:
            continue
        child_cls = to_pascal_case(child.name)
        child_table = _table_name(child)
        fk_col = to_snake_case(entity.name) + "_id"
        text_field = f"{child_table}_text"
        display_field = _relation_display_field(child)
        display_attr = to_snake_case(display_field.name) if display_field else "id"
        info.append((child_cls, child_table, fk_col, text_field, display_attr))
    return info


def _validation_expr_fields(expr) -> list[str]:
    """Tous les noms de champ (NOVA, pas snake_case) référencés quelque
    part dans une `ValidationExpr` — utilisé pour générer les gardes
    `is not None` avant d'évaluer l'expression (voir _validation_check_lines
    ci-dessous)."""
    if expr.kind == "field":
        return [expr.value]
    if expr.kind in ("call", "binop"):
        out: list[str] = []
        for arg in expr.args:
            out += _validation_expr_fields(arg)
        return out
    return []


def _validation_expr_to_python(expr) -> str:
    """Traduit une `ValidationExpr` (voir ast_nodes.py) en expression
    Python : un champ -> `item.<snake>`, une constante -> son literal, un
    appel de fonction whitelist (`kw.VALIDATION_FUNCTIONS`, déjà résolu en
    nom Python natif par le parser : min/max/round/abs) -> l'appel Python
    équivalent, une somme/différence -> l'opération Python équivalente
    (parenthésée pour préserver l'associativité gauche du parser)."""
    if expr.kind == "number":
        return repr(expr.value)
    if expr.kind == "field":
        return f"item.{to_snake_case(expr.value)}"
    if expr.kind == "call":
        args = ", ".join(_validation_expr_to_python(a) for a in expr.args)
        return f"{expr.value}({args})"
    if expr.kind == "binop":
        left, right = expr.args
        return f"({_validation_expr_to_python(left)} {expr.value} {_validation_expr_to_python(right)})"
    raise ValueError(f"ValidationExpr.kind inconnu : {expr.kind!r}")  # pragma: no cover


def _validation_check_lines(entity: Entity, program: NovaProgram, indent: str = "    ") -> list[str]:
    """Lignes Python vérifiant chaque `validation <Nom> sur <Entite> {
    regle: ... message: "..." }` ciblant cette entité (voir
    `parser._validate_validations`, qui garantit que chaque expression est
    bien formée et que les champs qui y participent sont d'un type
    comparable/numérique) — insérées après que `item` porte l'état final de
    l'enregistrement (juste avant `session.add(item)`, aussi bien en
    `create` qu'en `update` : en update, APRÈS la boucle `setattr` qui
    applique le payload, pour valider l'état RÉSULTANT, pas seulement les
    champs modifiés). Une valeur `None` sur N'IMPORTE LEQUEL des champs
    référencés par l'expression (champ optionnel non renseigné) désactive
    silencieusement la règle plutôt que de lever une TypeError sur une
    comparaison/opération arithmétique avec `None`."""
    out = []
    for validation in program.validations:
        if validation.entity != entity.name:
            continue
        for rule in validation.rules:
            # dict.fromkeys plutôt que set() : préserve l'ordre d'apparition
            # (expr_a puis expr_b, comportement historique inchangé pour une
            # règle à deux champs nus) tout en dédupliquant un champ répété.
            fields = list(dict.fromkeys(_validation_expr_fields(rule.expr_a) + _validation_expr_fields(rule.expr_b)))
            none_guard = " and ".join(f"item.{to_snake_case(f)} is not None" for f in fields)
            condition = f"not ({_validation_expr_to_python(rule.expr_a)} {rule.op} {_validation_expr_to_python(rule.expr_b)})"
            if none_guard:
                condition = f"{none_guard} and {condition}"
            out.append(f"{indent}if {condition}:")
            out.append(f'{indent}    raise HTTPException(status_code=422, detail={rule.message!r})')
    return out


def _generate_models(program: NovaProgram) -> str:
    active_langs = program.active_languages()
    lines = [
        _HEADER,
        "from __future__ import annotations",
        "",
        "from datetime import date, datetime",
        "from typing import Optional",
        "",
        "from sqlmodel import Field, SQLModel",
        "",
        "",
    ]
    for entity in program.entities:
        cls = _model_class_name(entity)
        table = _table_name(entity)
        lines.append(f"class {cls}(SQLModel, table=True):")
        lines.append(f'    """Généré depuis `entity {entity.name}` / `entité {entity.name}`."""')
        lines.append(f'    __tablename__ = "{table}"')
        lines.append("")
        lines.append("    id: Optional[int] = Field(default=None, primary_key=True)")
        for f in entity.fields:
            if f.multilingual:
                lines += _multilingual_model_lines(f, active_langs)
            else:
                lines.append(_field_line(entity, f))
        for rel in entity.relations:
            if rel.kind == "belongs_to":
                target_table = to_snake_case(pluralize(to_ascii_identifier(rel.target)))
                lines.append(
                    f"    {to_snake_case(rel.target)}_id: Optional[int] = "
                    f'Field(default=None, foreign_key="{target_table}.id")'
                )
            else:  # has_many -> informational, pas de colonne sur cette table
                lines.append(f"    # has_many / possède_plusieurs {rel.target} -> voir la table {to_snake_case(pluralize(to_ascii_identifier(rel.target)))}")
        lines.append("")
        lines.append("")

        # Schémas Create/Update/Read séparés du modèle table pour une API propre.
        # Les relations belongs_to sont exposées comme de simples clés étrangères
        # (<cible>_id) : c'est ce qui permet de rattacher un enregistrement à un
        # parent via l'API (sinon la relation serait indisponible en écriture).
        fk_field_names = [to_snake_case(rel.target) + "_id" for rel in entity.relations if rel.kind == "belongs_to"]

        lines.append(f"class {cls}Create(SQLModel):")
        body = [f for f in entity.fields]
        if not body and not fk_field_names:
            lines.append("    pass")
        for f in body:
            if f.multilingual:
                lines += _multilingual_schema_lines(f, active_langs)
                continue
            py_type = PY_TYPE_MAP.get(f.type, "str") if not f.is_reference else "int"
            type_hint = py_type if f.required else f"Optional[{py_type}]"
            if f.pattern:
                kwargs = f'pattern=r"{f.pattern}"' if f.required else f'default=None, pattern=r"{f.pattern}"'
                lines.append(f"    {to_snake_case(f.name)}: {type_hint} = Field({kwargs})")
            else:
                default = "" if f.required else " = None"
                lines.append(f"    {to_snake_case(f.name)}: {type_hint}{default}")
        for fk_name in fk_field_names:
            lines.append(f"    {fk_name}: Optional[int] = None")
        lines.append("")
        lines.append("")

        lines.append(f"class {cls}Update(SQLModel):")
        if not body and not fk_field_names:
            lines.append("    pass")
        for f in body:
            if f.multilingual:
                lines += _multilingual_schema_lines(f, active_langs)
                continue
            py_type = PY_TYPE_MAP.get(f.type, "str") if not f.is_reference else "int"
            if f.pattern:
                lines.append(
                    f'    {to_snake_case(f.name)}: Optional[{py_type}] = Field(default=None, pattern=r"{f.pattern}")'
                )
            else:
                lines.append(f"    {to_snake_case(f.name)}: Optional[{py_type}] = None")
        for fk_name in fk_field_names:
            lines.append(f"    {fk_name}: Optional[int] = None")
        lines.append("")
        lines.append("")

        # Schéma de lecture supplémentaire, uniquement pour les entités
        # portant au moins un `has_many` : les actions `liste`/`get` de
        # `_generate_router` matérialisent alors les enregistrements liés
        # sous la forme d'un résumé texte par relation (`<table_enfant>_
        # text`, voir `_has_many_relation_info`) — un champ que `{cls}` (le
        # modèle de table) ne porte pas, d'où ce schéma dédié utilisé comme
        # `response_model` pour ces deux actions seulement (create/update/
        # delete continuent de renvoyer `{cls}`, inchangés).
        has_many_info = _has_many_relation_info(entity, program)
        if has_many_info:
            lines.append(f"class {cls}Read(SQLModel):")
            lines.append("    id: Optional[int] = None")
            for f in entity.fields:
                if f.multilingual:
                    lines += [f"    {col}: Optional[str] = None" for col in _multilingual_column_names(f, active_langs)]
                    continue
                py_type = PY_TYPE_MAP.get(f.type, "str") if not f.is_reference else "int"
                lines.append(f"    {to_snake_case(f.name)}: Optional[{py_type}] = None")
            for fk_name in fk_field_names:
                lines.append(f"    {fk_name}: Optional[int] = None")
            for _child_cls, _child_table, _fk_col, text_field, _display_attr in has_many_info:
                lines.append(f'    {text_field}: str = ""')
            lines.append("")
            lines.append("")

    return "\n".join(lines) + "\n"


def _generate_database(engine: str) -> str:
    # URL de repli par moteur (`kw.DB_DEFAULT_URLS`, source de vérité
    # partagée avec codegen/docker.py::_compose) — utilisée UNIQUEMENT si
    # NOVA_DATABASE_URL n'est pas fournie à l'exécution (toujours
    # surchargeable en production, voir parser._validate_app_database).
    default_url = kw.DB_DEFAULT_URLS.get(engine, kw.DB_DEFAULT_URLS["sqlite"])
    return _HEADER + f'''
from __future__ import annotations

import os
from collections.abc import Iterator

from sqlmodel import Session, SQLModel, create_engine

DATABASE_URL = os.environ.get("NOVA_DATABASE_URL", "{default_url}")

connect_args = {{"check_same_thread": False}} if DATABASE_URL.startswith("sqlite") else {{}}
engine = create_engine(DATABASE_URL, echo=False, connect_args=connect_args)


def init_db() -> None:
    """Crée les tables si elles n'existent pas encore (suffisant pour un MVP)."""
    SQLModel.metadata.create_all(engine)


def get_session() -> Iterator[Session]:
    with Session(engine) as session:
        yield session
'''


def _template_field_names(entity: Entity, program: NovaProgram) -> list[str]:
    """Noms (snake_case) de tous les champs substituables dans un template
    email externe (`email {{ template: "..." }}`, tâche #37) pour cette
    entité — `{{champ}}` dans le fichier .html référencé est remplacé par
    `item.<champ>` (ou la valeur capturée avant suppression pour `delete`,
    voir `_generate_router`) au moment de l'envoi. Reprend exactement les
    mêmes conventions de nommage que `_generate_models` : un champ
    multilingue devient une colonne par langue ACTIVE du projet, une
    référence directe (`champ x: AutreEntite`) ou une relation `belongs_to`
    explicite devient `<cible>_id`."""
    active_langs = program.active_languages()
    names: list[str] = []
    for f in entity.fields:
        if f.multilingual:
            names += _multilingual_column_names(f, active_langs)
        elif f.is_reference:
            names.append(f"{to_snake_case(f.name)}_id")
        else:
            names.append(to_snake_case(f.name))
    for rel in entity.relations:
        if rel.kind == "belongs_to":
            fk = f"{to_snake_case(rel.target)}_id"
            if fk not in names:
                names.append(fk)
    return names


def _generate_router(
    entity: Entity,
    actions: list[str],
    protected_role: str | None = None,
    notify_actions: list[str] | None = None,
    notify_recipient_field: str | None = None,
    notify_attachment_field: str | None = None,
    program: NovaProgram | None = None,
) -> str:
    cls = _model_class_name(entity)
    table = _table_name(entity)
    var = to_snake_case(entity.name)
    tag = entity.name
    notify_actions = notify_actions or []
    recipient_snake = to_snake_case(notify_recipient_field) if notify_recipient_field else None
    attachment_snake = to_snake_case(notify_attachment_field) if notify_attachment_field else None
    # `has_many: <Enfant>` (voir `parser._validate_relations`, qui garantit
    # que chaque relation ici a bien un `belongs_to` réciproque côté
    # enfant) : `list`/`get` matérialisent les enregistrements liés sous
    # forme d'un résumé texte par relation plutôt que d'une liste imbriquée
    # — même choix que pour le calendrier (`events_text`, voir
    # ui_reflex.py) : Reflex peine à typer un `rx.foreach` sur une valeur
    # imbriquée dans un dict lui-même dans une liste d'un state var, donc le
    # frontend affiche directement une chaîne déjà prête plutôt que de
    # reconstruire une liste côté client.
    has_many_info = _has_many_relation_info(entity, program) if program is not None else []

    def _notify_kwargs(recipient_expr: str | None, attachment_expr: str | None) -> str:
        # `destinataire:`/`piece_jointe:` (voir _validate_notifiers) : ajoute
        # `to=`/`attachment_path=` à l'appel `send_email(...)` déjà construit
        # par l'appelant. `recipient_expr`/`attachment_expr` sont des
        # expressions Python (texte) évaluées dans le code généré — soit
        # `item.<champ>` (create/update), soit une variable locale capturée
        # avant suppression (delete, voir plus bas : l'objet est expiré après
        # `session.commit()`).
        extra = ""
        if recipient_expr:
            extra += f", to=({recipient_expr} or None)"
        if attachment_expr:
            extra += (
                f", attachment_path=(UPLOADS_DIR / Path({attachment_expr}).name "
                f"if {attachment_expr} else None)"
            )
        return extra

    lines = [
        _HEADER,
        "from __future__ import annotations",
        "",
        "from fastapi import APIRouter, Depends, HTTPException",
        "from sqlmodel import Session, select",
        "",
        "from ..database import get_session",
    ]
    model_imports = [cls, f"{cls}Create", f"{cls}Update"]
    if has_many_info:
        model_imports.append(f"{cls}Read")
        model_imports += [child_cls for child_cls, *_rest in has_many_info]
    lines.append(f"from ..models import {', '.join(model_imports)}")
    if protected_role:
        lines.append("from ..auth import require_role")
    uses_template = bool(notify_actions and program is not None and program.email and program.email.template)
    if notify_actions:
        # `notifier: ...` sur `api {entity.name} { ... }` (nécessite un bloc
        # `email { ... }` — validé à la compilation, voir parser.py).
        # `email { template: ... }` (tâche #37) : importe aussi
        # `render_email_template`, seule différence entre les deux modes
        # (voir les blocs `notify_kwargs` plus bas dans ce fichier).
        if uses_template:
            lines.append("from ..emailer import render_email_template, send_email")
        else:
            lines.append("from ..emailer import send_email")
    if attachment_snake:
        # `piece_jointe: {notify_attachment_field}` : le champ est validé
        # `file`/`image` (parser.py::_validate_notifiers), donc le routeur
        # `_uploads.py` (UPLOADS_DIR) existe forcément — voir _has_uploads.
        lines.append("from pathlib import Path")
        lines.append("from ._uploads import UPLOADS_DIR")
    lines.append("")
    router_kwargs = f'prefix="/{table}", tags=["{tag}"]'
    if protected_role:
        # `proteger: <role>` dans le DSL protège TOUTES les actions de cette
        # API d'un coup — le plus simple à écrire, et le plus dur à oublier.
        router_kwargs += f', dependencies=[Depends(require_role("{protected_role}"))]'
    lines += [
        f"router = APIRouter({router_kwargs})",
        "",
        "",
    ]

    def _related_text_lines(indent: str, item_expr: str) -> list[str]:
        # Une ligne par relation `has_many` : interroge les enregistrements
        # enfants dont la clé étrangère pointe vers `item_expr`, et résume
        # leur champ « titre » (`display_attr`) en une seule chaîne jointe
        # par virgules (chaîne vide si aucun enfant).
        out = []
        for child_cls, child_table, fk_col, text_field, display_attr in has_many_info:
            related_var = f"related_{child_table}"
            out.append(
                f"{indent}{related_var} = session.exec("
                f"select({child_cls}).where({child_cls}.{fk_col} == {item_expr}.id)).all()"
            )
            out.append(
                f'{indent}data["{text_field}"] = ", ".join(str(c.{display_attr}) for c in {related_var})'
            )
        return out

    if "list" in actions:
        if has_many_info:
            lines += [
                f'@router.get("/", response_model=list[{cls}Read])',
                f"def list_{table}(session: Session = Depends(get_session)):",
                f'    """list / liste — retourne tous les {tag}, avec un résumé texte '
                f'des enregistrements liés ({", ".join(t for _c, _t, _f, t, _d in has_many_info)})."""',
                f"    items = session.exec(select({cls})).all()",
                "    result = []",
                "    for item in items:",
                "        data = item.model_dump()",
            ]
            lines += _related_text_lines("        ", "item")
            lines += [
                "        result.append(data)",
                "    return result",
                "",
                "",
            ]
        else:
            lines += [
                f'@router.get("/", response_model=list[{cls}])',
                f"def list_{table}(session: Session = Depends(get_session)):",
                f'    """list / liste — retourne tous les {tag}."""',
                f"    return session.exec(select({cls})).all()",
                "",
                "",
            ]

    if "get" in actions:
        if has_many_info:
            lines += [
                f'@router.get("/{{item_id}}", response_model={cls}Read)',
                f"def get_{var}(item_id: int, session: Session = Depends(get_session)):",
                f'    """get / obtenir / lire — retourne un {tag} par id, avec un résumé '
                f'texte des enregistrements liés."""',
                f"    item = session.get({cls}, item_id)",
                "    if item is None:",
                f'        raise HTTPException(status_code=404, detail="{tag} not found")',
                "    data = item.model_dump()",
            ]
            lines += _related_text_lines("    ", "item")
            lines += [
                "    return data",
                "",
                "",
            ]
        else:
            lines += [
                f'@router.get("/{{item_id}}", response_model={cls})',
                f"def get_{var}(item_id: int, session: Session = Depends(get_session)):",
                f'    """get / obtenir / lire — retourne un {tag} par id."""',
                f"    item = session.get({cls}, item_id)",
                "    if item is None:",
                f'        raise HTTPException(status_code=404, detail="{tag} not found")',
                "    return item",
                "",
                "",
            ]

    if "create" in actions:
        lines += [
            f'@router.post("/", response_model={cls}, status_code=201)',
            f"def create_{var}(payload: {cls}Create, session: Session = Depends(get_session)):",
            f'    """create / créer — crée un nouveau {tag}."""',
            f"    item = {cls}.model_validate(payload)",
        ]
        lines += _validation_check_lines(entity, program) if program is not None else []
        lines += [
            "    session.add(item)",
            "    session.commit()",
            "    session.refresh(item)",
        ]
        if "create" in notify_actions:
            notify_kwargs = _notify_kwargs(
                f"item.{recipient_snake}" if recipient_snake else None,
                f"item.{attachment_snake}" if attachment_snake else None,
            )
            if uses_template:
                field_names = _template_field_names(entity, program)
                values_expr = ", ".join(
                    ['"action": "created"', f'"entity": "{tag}"', '"id": item.id']
                    + [f'"{f}": item.{f}' for f in field_names]
                )
                lines.append(
                    f'    subject, html_body, text_body = render_email_template({{{values_expr}}})\n'
                    f'    send_email(subject=subject, body=text_body, html_body=html_body{notify_kwargs})'
                )
            else:
                lines.append(
                    f'    send_email(\n'
                    f'        subject="[NOVA] Nouveau {tag} / New {tag}",\n'
                    f'        body=f"{tag} #{{item.id}} créé / created.",\n'
                    f'        html_body=f"""<html><body style="font-family:sans-serif">'
                    f'<h2 style="color:#7c66dc">[NOVA] Nouveau {tag} / New {tag}</h2>'
                    f'<p>{tag} #{{item.id}} créé / created.</p></body></html>"""{notify_kwargs},\n'
                    f'    )'
                )
        lines += [
            "    return item",
            "",
            "",
        ]

    if "update" in actions:
        lines += [
            f'@router.put("/{{item_id}}", response_model={cls})',
            f"def update_{var}(item_id: int, payload: {cls}Update, session: Session = Depends(get_session)):",
            f'    """update / modifier — met à jour un {tag} existant."""',
            f"    item = session.get({cls}, item_id)",
            "    if item is None:",
            f'        raise HTTPException(status_code=404, detail="{tag} not found")',
            "    for key, value in payload.model_dump(exclude_unset=True).items():",
            "        setattr(item, key, value)",
        ]
        lines += _validation_check_lines(entity, program) if program is not None else []
        lines += [
            "    session.add(item)",
            "    session.commit()",
            "    session.refresh(item)",
        ]
        if "update" in notify_actions:
            notify_kwargs = _notify_kwargs(
                f"item.{recipient_snake}" if recipient_snake else None,
                f"item.{attachment_snake}" if attachment_snake else None,
            )
            if uses_template:
                field_names = _template_field_names(entity, program)
                values_expr = ", ".join(
                    ['"action": "updated"', f'"entity": "{tag}"', '"id": item.id']
                    + [f'"{f}": item.{f}' for f in field_names]
                )
                lines.append(
                    f'    subject, html_body, text_body = render_email_template({{{values_expr}}})\n'
                    f'    send_email(subject=subject, body=text_body, html_body=html_body{notify_kwargs})'
                )
            else:
                lines.append(
                    f'    send_email(\n'
                    f'        subject="[NOVA] {tag} modifié / updated",\n'
                    f'        body=f"{tag} #{{item.id}} mis à jour / updated.",\n'
                    f'        html_body=f"""<html><body style="font-family:sans-serif">'
                    f'<h2 style="color:#7c66dc">[NOVA] {tag} modifié / updated</h2>'
                    f'<p>{tag} #{{item.id}} mis à jour / updated.</p></body></html>"""{notify_kwargs},\n'
                    f'    )'
                )
        lines += [
            "    return item",
            "",
            "",
        ]

    if "delete" in actions:
        lines += [
            f'@router.delete("/{{item_id}}", status_code=204)',
            f"def delete_{var}(item_id: int, session: Session = Depends(get_session)):",
            f'    """delete / supprimer — supprime un {tag}."""',
            f"    item = session.get({cls}, item_id)",
            "    if item is None:",
            f'        raise HTTPException(status_code=404, detail="{tag} not found")',
        ]
        if "delete" in notify_actions:
            # L'id (et, si configurés, le destinataire/la pièce jointe) sont
            # capturés avant `session.delete`/`commit` : l'objet est expiré
            # après le commit, `item.<champ>` ne serait plus fiable ensuite.
            lines.append("    deleted_id = item.id")
            if recipient_snake:
                lines.append(f"    deleted_to = item.{recipient_snake}")
            if attachment_snake:
                lines.append(f"    deleted_attachment = item.{attachment_snake}")
            if uses_template:
                # `item` expire après `session.commit()` ci-dessous : tous
                # les champs substituables sont donc capturés maintenant
                # dans un dict, en plus de deleted_id/deleted_to/
                # deleted_attachment ci-dessus (voir _template_field_names).
                field_names = _template_field_names(entity, program)
                deleted_values_expr = ", ".join(f'"{f}": item.{f}' for f in field_names)
                lines.append(f"    deleted_values = {{{deleted_values_expr}}}")
        lines += [
            "    session.delete(item)",
            "    session.commit()",
        ]
        if "delete" in notify_actions:
            notify_kwargs = _notify_kwargs(
                "deleted_to" if recipient_snake else None,
                "deleted_attachment" if attachment_snake else None,
            )
            if uses_template:
                values_expr = (
                    f'"action": "deleted", "entity": "{tag}", "id": deleted_id, **deleted_values'
                )
                lines.append(
                    f'    subject, html_body, text_body = render_email_template({{{values_expr}}})\n'
                    f'    send_email(subject=subject, body=text_body, html_body=html_body{notify_kwargs})'
                )
            else:
                lines.append(
                    f'    send_email(\n'
                    f'        subject="[NOVA] {tag} supprimé / deleted",\n'
                    f'        body=f"{tag} #{{deleted_id}} supprimé / deleted.",\n'
                    f'        html_body=f"""<html><body style="font-family:sans-serif">'
                    f'<h2 style="color:#7c66dc">[NOVA] {tag} supprimé / deleted</h2>'
                    f'<p>{tag} #{{deleted_id}} supprimé / deleted.</p></body></html>"""{notify_kwargs},\n'
                    f'    )'
                )
        lines += [
            "    return None",
            "",
        ]

    return "\n".join(lines) + "\n"


def _generate_main(program: NovaProgram) -> str:
    app_name = program.app.name if program.app else "NovaApp"
    has_auth = program.auth is not None and program.auth.enabled
    has_queries = bool(program.queries)
    has_calendars = bool(program.calendars)
    has_uploads = _has_uploads(program)
    lines = [
        _HEADER,
        "from __future__ import annotations",
        "",
        "import importlib",
        "import pkgutil",
        "",
        "from fastapi import FastAPI",
        "from fastapi.middleware.cors import CORSMiddleware",
    ]
    if has_uploads:
        lines.append("from fastapi.staticfiles import StaticFiles")
    lines += [
        "",
        "from .database import init_db",
        "from . import routers_custom",
    ]
    if has_auth:
        lines.append("from .auth import router as auth_router")
    if has_queries:
        lines.append("from .routers._requetes import router as requetes_router")
    if has_calendars:
        lines.append("from .routers._ics import router as ics_router")
    if has_uploads:
        lines.append("from .routers._uploads import router as uploads_router, UPLOADS_DIR")
    for api in program.apis:
        entity = program.get_entity(api.entity)
        if entity is None:
            continue
        table = _table_name(entity)
        lines.append(f"from .routers.{table} import router as {table}_router")
    lines += [
        "",
        f'app = FastAPI(title="{app_name}", description="Généré par NOVA / Generated by NOVA")',
        "",
        "app.add_middleware(",
        "    CORSMiddleware,",
        '    allow_origins=["*"],',
        "    allow_methods=[\"*\"],",
        "    allow_headers=[\"*\"],",
        ")",
        "",
        "",
        "@app.on_event(\"startup\")",
        "def on_startup() -> None:",
        "    init_db()",
        "",
        "",
    ]
    if has_uploads:
        # Chemin distinct de "/uploads" (le routeur POST ci-dessous) pour
        # éviter tout conflit de préfixe entre le Mount ASGI (fichiers
        # statiques, GET) et l'APIRouter (upload, POST).
        lines.append('app.mount("/files", StaticFiles(directory=str(UPLOADS_DIR)), name="files")')
    if has_auth:
        lines.append("app.include_router(auth_router)")
    if has_queries:
        lines.append("app.include_router(requetes_router)")
    if has_calendars:
        lines.append("app.include_router(ics_router)")
    if has_uploads:
        lines.append("app.include_router(uploads_router)")
    for api in program.apis:
        entity = program.get_entity(api.entity)
        if entity is None:
            continue
        table = _table_name(entity)
        lines.append(f"app.include_router({table}_router)")
    lines += [
        "",
        "# Logique métier hors DSL (validations avancées, requêtes complexes,",
        "# écritures en base sur mesure...) : tout module de app/routers_custom/",
        "# exposant une variable `router` est inclus automatiquement. Ce dossier",
        "# n'est jamais régénéré par `nova compile` — voir routers_custom/example.py.",
        "for _finder, _mod_name, _ispkg in pkgutil.iter_modules(routers_custom.__path__):",
        '    _custom_mod = importlib.import_module(f".routers_custom.{_mod_name}", package=__package__)',
        '    if hasattr(_custom_mod, "router"):',
        "        app.include_router(_custom_mod.router)",
        "",
        "",
        '@app.get("/health")',
        "def health():",
        '    return {"status": "ok"}',
        "",
    ]
    return "\n".join(lines) + "\n"


def _generate_auth(program: NovaProgram) -> str:
    auth = program.auth
    roles = auth.roles if auth and auth.roles else ["user"]
    default_role = auth.default_role if auth else "user"
    roles_literal = "[" + ", ".join(repr(r) for r in roles) + "]"
    return _HEADER + f'''
from __future__ import annotations

import os
from datetime import datetime, timedelta, timezone
from typing import Optional

import bcrypt
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.security import OAuth2PasswordBearer, OAuth2PasswordRequestForm
from jose import JWTError, jwt
from sqlmodel import Field, Session, SQLModel, select

from .database import get_session

# Bloc `auth {{ ... }}` du fichier .nova : rôles déclarés et rôle par défaut
# attribué à l'inscription si aucun n'est précisé.
ROLES = {roles_literal}
DEFAULT_ROLE = "{default_role}"

# Clé de signature JWT : à définir en production via la variable
# d'environnement NOVA_JWT_SECRET. La valeur par défaut ci-dessous permet au
# projet généré de démarrer "out of the box" — ne JAMAIS l'utiliser telle
# quelle en production.
SECRET_KEY = os.environ.get("NOVA_JWT_SECRET", "nova-dev-secret-change-me")
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 60 * 24

# Hachage direct via la bibliothèque `bcrypt` (et non `passlib`, dont
# l'intégration bcrypt est cassée avec les versions récentes de la
# bibliothèque `bcrypt` — `passlib`, non maintenu depuis 2020, échoue avec
# une `ValueError` sans rapport à l'exécution — voir la doc du framework).
oauth2_scheme = OAuth2PasswordBearer(tokenUrl="/auth/login", auto_error=False)


class User(SQLModel, table=True):
    """Table utilisateur générée par le bloc `auth {{ ... }}` — indépendante
    des entités du DSL."""

    __tablename__ = "nova_users"

    id: Optional[int] = Field(default=None, primary_key=True)
    email: str = Field(unique=True, index=True)
    password_hash: str
    role: str = Field(default=DEFAULT_ROLE)
    created_at: datetime = Field(default_factory=datetime.utcnow)


class UserCreate(SQLModel):
    # Pas de champ `role` ici, volontairement : le rôle n'est JAMAIS choisi
    # par l'appelant de /auth/register (voir `register()` ci-dessous) —
    # accepter un `role` dans la charge utile permettrait à n'importe qui
    # de s'inscrire directement comme "admin".
    email: str
    password: str


class UserRead(SQLModel):
    id: int
    email: str
    role: str


class RoleUpdate(SQLModel):
    role: str


def hash_password(password: str) -> str:
    return bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt()).decode("utf-8")


def verify_password(password: str, password_hash: str) -> bool:
    return bcrypt.checkpw(password.encode("utf-8"), password_hash.encode("utf-8"))


def create_access_token(data: dict) -> str:
    to_encode = data.copy()
    expire = datetime.now(timezone.utc) + timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)
    to_encode.update({{"exp": expire}})
    return jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)


def get_current_user(
    token: Optional[str] = Depends(oauth2_scheme), session: Session = Depends(get_session)
) -> User:
    credentials_error = HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Identifiants invalides ou absents / Missing or invalid credentials",
        headers={{"WWW-Authenticate": "Bearer"}},
    )
    if token is None:
        raise credentials_error
    try:
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        email = payload.get("sub")
        if email is None:
            raise credentials_error
    except JWTError:
        raise credentials_error
    user = session.exec(select(User).where(User.email == email)).first()
    if user is None:
        raise credentials_error
    return user


def require_role(role: str):
    """Dépendance FastAPI protégeant une route/un routeur pour un rôle donné
    (utilisée automatiquement pour `api Xxx {{ ... proteger: <role> }}`) —
    un utilisateur "admin" passe toujours, quel que soit le rôle requis."""

    def _dependency(user: User = Depends(get_current_user)) -> User:
        if user.role != role and user.role != "admin":
            raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Accès refusé / Forbidden")
        return user

    return _dependency


router = APIRouter(prefix="/auth", tags=["auth"])


@router.post("/register", response_model=UserRead, status_code=201)
def register(payload: UserCreate, session: Session = Depends(get_session)):
    """Le rôle attribué n'est JAMAIS choisi par l'appelant (voir `UserCreate`
    ci-dessus, qui ne porte pas de champ `role`) : le tout premier compte
    créé sur le projet devient automatiquement "admin" (bootstrap sans
    étape manuelle ni identifiants par défaut à changer) ; tous les
    suivants reçoivent DEFAULT_ROLE. Un admin peut ensuite promouvoir un
    autre compte via `PATCH /auth/users/{{id}}/role`. Pensez à créer votre
    propre compte immédiatement après le déploiement : le premier email
    enregistré devient administrateur."""
    existing = session.exec(select(User).where(User.email == payload.email)).first()
    if existing is not None:
        raise HTTPException(status_code=400, detail="Email déjà utilisé / Email already registered")
    is_first_user = session.exec(select(User)).first() is None
    role = "admin" if (is_first_user and "admin" in ROLES) else DEFAULT_ROLE
    user = User(email=payload.email, password_hash=hash_password(payload.password), role=role)
    session.add(user)
    session.commit()
    session.refresh(user)
    return user


@router.patch("/users/{{user_id}}/role", response_model=UserRead)
def set_user_role(
    user_id: int,
    payload: RoleUpdate,
    admin: User = Depends(require_role("admin")),
    session: Session = Depends(get_session),
):
    """Promeut/rétrograde un compte existant — réservé aux admins, seul
    moyen légitime d'attribuer un rôle autre que DEFAULT_ROLE une fois le
    premier compte admin bootstrap via `register()` ci-dessus."""
    if payload.role not in ROLES:
        raise HTTPException(
            status_code=422, detail=f"Rôle inconnu / Unknown role: {{payload.role}}"
        )
    user = session.get(User, user_id)
    if user is None:
        raise HTTPException(status_code=404, detail="Utilisateur introuvable / User not found")
    user.role = payload.role
    session.add(user)
    session.commit()
    session.refresh(user)
    return user


@router.post("/login")
def login(form_data: OAuth2PasswordRequestForm = Depends(), session: Session = Depends(get_session)):
    """Compatible OAuth2PasswordRequestForm : envoyer `username` (= email) et
    `password` en `application/x-www-form-urlencoded`."""
    user = session.exec(select(User).where(User.email == form_data.username)).first()
    if user is None or not verify_password(form_data.password, user.password_hash):
        raise HTTPException(status_code=401, detail="Identifiants invalides / Invalid credentials")
    token = create_access_token({{"sub": user.email, "role": user.role}})
    return {{"access_token": token, "token_type": "bearer"}}


@router.get("/me", response_model=UserRead)
def me(user: User = Depends(get_current_user)):
    return user
'''


def _format_query_value(value) -> str:
    if isinstance(value, str):
        return repr(value)
    return repr(value)


def _query_entity_scope(program: NovaProgram, q) -> dict[str, str]:
    """Nom d'entité NOVA -> classe SQLModel (PascalCase) pour l'entité
    principale de la requête et chacune de ses `jointure:` (voir
    ast_nodes.Query.joins) — utilisé pour résoudre un champ qualifié
    (`"Client.pays"`) comme un champ non qualifié (`"pays"`, résolu contre
    l'entité principale, comportement historique inchangé)."""
    scope = {q.entity: to_pascal_case(q.entity)}
    for j in q.joins:
        scope[j.entity] = to_pascal_case(j.entity)
    return scope


def _query_field_expr(scope: dict[str, str], default_entity: str, qualified: str) -> str:
    if "." in qualified:
        entity_name, field_name = qualified.split(".", 1)
    else:
        entity_name, field_name = default_entity, qualified
    cls = scope[entity_name]
    snake = "id" if field_name == "id" else to_snake_case(field_name)
    return f"models.{cls}.{snake}"


def _generate_query_router(program: NovaProgram) -> str:
    # `filtre:` de premier niveau -> combinés par ET (autant d'appels
    # `.where()` chaînés, comportement historique inchangé). Un bloc
    # `ou: { filtre: ... filtre: ... }` (Query.filter_groups) -> un seul
    # `.where(or_(...))` par groupe, donc lui aussi ET-é avec le reste :
    # `WHERE f1 AND f2 AND (g1a OR g1b) AND (g2a OR g2b OR g2c)`. L'import
    # `or_` n'est ajouté que si au moins une requête du programme a un
    # groupe `ou:`, pour ne pas polluer le fichier généré sinon.
    #
    # `jointure: <Entite> sur <local> = <distant>` (Query.joins) -> un
    # `select()` portant plusieurs entités + `.join(Cls, onclause)` par
    # jointure déclarée, dans l'ordre où elles apparaissent dans le fichier
    # .nova (une jointure peut référencer une entité jointe précédemment,
    # pas seulement l'entité principale). `session.exec(...)` renvoie alors
    # des tuples (Row) plutôt que des instances uniques : la route sérialise
    # chaque ligne en dict, l'entité principale à plat et chaque entité
    # jointe sous une clé nommée d'après son nom en snake_case — pas de
    # `response_model` dans ce cas (une liste de dicts hétérogènes selon la
    # requête, contrairement au cas sans jointure où `response_model=
    # list[models.<Cls>]` reste précis et documenté dans /docs).
    has_or_groups = any(q.filter_groups for q in program.queries)
    has_joins = any(q.joins for q in program.queries)
    lines = [
        _HEADER,
        "from __future__ import annotations",
        "",
        "from fastapi import APIRouter, Depends",
    ]
    if has_or_groups:
        lines.append("from sqlalchemy import or_")
    lines += [
        "from sqlmodel import Session, select",
        "",
        "from ..database import get_session",
        "from .. import models",
        "",
        'router = APIRouter(prefix="/requetes", tags=["requetes"])',
        "",
        "",
    ]
    for q in program.queries:
        entity = program.get_entity(q.entity)
        cls = to_pascal_case(entity.name) if entity else to_pascal_case(q.entity)
        scope = _query_entity_scope(program, q)
        slug = to_snake_case(q.name).replace("_", "-")
        fn_name = to_snake_case(q.name)
        response_model = "" if q.joins else f", response_model=list[models.{cls}]"
        lines += [
            f'@router.get("/{slug}"{response_model})',
            f"def {fn_name}(session: Session = Depends(get_session)):",
            f'    """Requête déclarative `requete {q.name} sur {q.entity} {{ ... }}` du fichier .nova."""',
        ]
        if q.joins:
            select_targets = ", ".join(f"models.{scope[e]}" for e in [q.entity] + [j.entity for j in q.joins])
            lines.append(f"    query = select({select_targets})")
            for j in q.joins:
                local_expr = _query_field_expr(scope, q.entity, j.local_field)
                remote_expr = _query_field_expr(scope, q.entity, j.remote_field)
                lines.append(f"    query = query.join(models.{scope[j.entity]}, {local_expr} == {remote_expr})")
        else:
            lines.append(f"    query = select(models.{cls})")
        for f in q.filters:
            col = _query_field_expr(scope, q.entity, f.field)
            lines.append(f"    query = query.where({col} {f.op} {_format_query_value(f.value)})")
        for group in q.filter_groups:
            or_terms = ", ".join(
                f"{_query_field_expr(scope, q.entity, f.field)} {f.op} {_format_query_value(f.value)}"
                for f in group.filters
            )
            lines.append(f"    query = query.where(or_({or_terms}))")
        if q.order_by:
            col = _query_field_expr(scope, q.entity, q.order_by)
            direction = "desc" if q.order_dir == "desc" else "asc"
            lines.append(f"    query = query.order_by({col}.{direction}())")
        if q.limit is not None:
            lines.append(f"    query = query.limit({q.limit})")
        if q.joins:
            lines += [
                "    rows = session.exec(query).all()",
                "    result = []",
                "    for row in rows:",
                f"        item = row[0].model_dump()",
            ]
            for idx, j in enumerate(q.joins, start=1):
                key = to_snake_case(j.entity)
                lines.append(f'        item["{key}"] = row[{idx}].model_dump()')
            lines += [
                "        result.append(item)",
                "    return result",
                "",
                "",
            ]
        else:
            lines += [
                "    return session.exec(query).all()",
                "",
                "",
            ]
    return "\n".join(lines) + "\n"


def _generate_emailer(program: NovaProgram) -> str:
    """`backend/app/emailer.py` — généré uniquement si un bloc `email {
    ... }` est présent (voir `generate_backend`). Les valeurs du bloc
    servent de valeur par défaut, surchargeables sans recompiler via des
    variables d'environnement — sauf le mot de passe, jamais porté par
    `ast_nodes.Email` (voir son docstring), donc toujours vide par défaut
    ici : NOVA_SMTP_PASSWORD est la seule source possible."""
    email = program.email or _Email()
    tls_default = "true" if email.tls else "false"
    content = (
        _HEADER
        + f'''
from __future__ import annotations

import logging
import mimetypes
import os
import re
import smtplib
from email.message import EmailMessage
from pathlib import Path

logger = logging.getLogger("nova.email")


def _split_recipients(value: str) -> list[str]:
    """Découpe une chaîne de destinataires « comme sur les mails standard » :
    plusieurs adresses séparées par `;` (usage courant des clients mail) ou
    `,` (séparateur RFC 5322 du header `To`), espaces superflus tolérés,
    entrées vides ignorées. Utilisée aussi bien pour le destinataire fixe
    (NOVA_SMTP_TO / `email {{ to: ... }}`) que pour un champ dynamique
    (`api {{ ... destinataire: <champ> }}`, voir _generate_router) — les
    deux sources sont de simples chaînes .nova, jamais des listes."""
    return [addr.strip() for addr in re.split(r"[;,]", value) if addr.strip()]

# Bloc `email {{ ... }}` du fichier .nova : valeurs par défaut ci-dessous,
# surchargeables sans recompiler via NOVA_SMTP_HOST / NOVA_SMTP_PORT /
# NOVA_SMTP_USER / NOVA_SMTP_FROM / NOVA_SMTP_TO / NOVA_SMTP_TLS. Le mot de
# passe SMTP n'est JAMAIS lu depuis le fichier .nova (aucun secret en clair
# dans le code source généré) : toujours NOVA_SMTP_PASSWORD, vide par
# défaut (pas d'authentification SMTP tant qu'elle n'est pas fournie au
# runtime — même philosophie que NOVA_JWT_SECRET pour l'auth).
SMTP_HOST = os.environ.get("NOVA_SMTP_HOST", "{email.host}")
SMTP_PORT = int(os.environ.get("NOVA_SMTP_PORT", "{email.port}"))
SMTP_USER = os.environ.get("NOVA_SMTP_USER", "{email.user}")
SMTP_PASSWORD = os.environ.get("NOVA_SMTP_PASSWORD", "")
SMTP_FROM = os.environ.get("NOVA_SMTP_FROM", "{email.from_addr}")
SMTP_TO = os.environ.get("NOVA_SMTP_TO", "{email.to_addr}")
SMTP_TLS = os.environ.get("NOVA_SMTP_TLS", "{tls_default}").strip().lower() not in ("0", "false", "non", "no")


def send_email(
    subject: str,
    body: str,
    to: str | list[str] | None = None,
    html_body: str | None = None,
    attachment_path: str | Path | None = None,
) -> None:
    """Envoie une notification — déclenchée par `notifier:` sur un bloc
    `api` (voir app/routers/<entite>.py). Toute erreur (serveur SMTP
    injoignable, identifiants invalides, pièce jointe introuvable...) est
    loggée en warning et n'interrompt JAMAIS l'appelant : une notification
    est un effet de bord, pas une garantie — un souci SMTP ne doit jamais
    faire échouer une création/modification/suppression d'enregistrement.

    `to` : surcharge le destinataire fixe (SMTP_TO) — utilisé quand `api
    {{ ... destinataire: <champ> }}` référence un champ de l'enregistrement
    concerné (voir _generate_router). Plusieurs destinataires : comme sur
    les mails standard, une seule chaîne peut contenir plusieurs adresses
    séparées par `;` (ou `,`) — ex. `destinataire: contacts` avec un champ
    `contacts` valant `"a@x.com; b@y.com"` — découpée par
    `_split_recipients` ; `to` accepte aussi directement une liste de
    chaînes (chacune éventuellement elle-même multi-adresses). `html_body` :
    version HTML du message, envoyée en plus de `body` (texte brut, toujours
    présent en repli pour les clients mail qui n'affichent pas le HTML) via
    multipart/alternative. `attachment_path` : chemin d'un fichier local
    (voir `api {{ ... piece_jointe: <champ> }}`) à joindre — silencieusement
    ignoré s'il est None ou si le fichier n'existe pas (ex. champ vide sur
    l'enregistrement, ou fichier supprimé depuis) plutôt que de faire
    échouer l'envoi."""
    if to is None:
        recipients = _split_recipients(SMTP_TO)
    elif isinstance(to, str):
        recipients = _split_recipients(to)
    else:
        recipients = [addr for value in to for addr in _split_recipients(value)]
    if not recipients:
        logger.warning("NOVA email: aucun destinataire configuré (NOVA_SMTP_TO), notification ignorée.")
        return
    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = SMTP_FROM or SMTP_USER or "noreply@nova.local"
    msg["To"] = ", ".join(recipients)
    msg.set_content(body)
    if html_body:
        msg.add_alternative(html_body, subtype="html")
    if attachment_path:
        path = Path(attachment_path)
        try:
            data = path.read_bytes()
        except OSError as exc:
            logger.warning("NOVA email: pièce jointe '%s' illisible (%s) — envoyée sans pièce jointe.", path, exc)
        else:
            mime_type, _ = mimetypes.guess_type(path.name)
            maintype, _, subtype = (mime_type or "application/octet-stream").partition("/")
            msg.add_attachment(data, maintype=maintype, subtype=subtype or "octet-stream", filename=path.name)
    try:
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=10) as smtp:
            if SMTP_TLS:
                smtp.starttls()
            if SMTP_USER and SMTP_PASSWORD:
                smtp.login(SMTP_USER, SMTP_PASSWORD)
            smtp.send_message(msg)
    except Exception as exc:  # pragma: no cover - dépend d'un serveur SMTP réel
        logger.warning("NOVA email: envoi échoué (%s) — notification ignorée.", exc)
'''
    )
    if email.template:
        content += _EMAIL_TEMPLATE_BLOCK
    return content


# `email {{ template: "chemin/vers/fichier.html" }}` (tâche #37) : template
# HTML externe personnalisable, alternative au sujet/corps codés en dur
# ci-dessus (`send_email(subject="[NOVA] ...", html_body=f"""...""")` dans
# `_generate_router`). Bloc AJOUTÉ à la suite du contenu ci-dessus (jamais
# fusionné dans le même f-string : les `{{`/`}}` de la regex/f-string
# générées ci-dessous entreraient en collision avec les accolades de
# formatage de l'f-string de `_generate_emailer`) — chaîne brute (r'''),
# écrite telle quelle dans emailer.py, donc sans double-échappement des
# accolades ni des antislashs des motifs regex.
_EMAIL_TEMPLATE_BLOCK = r'''

# `email { template: "..." }` : template HTML externe, résolu à la
# compilation relativement au fichier .nova source puis copié ici (voir
# nova_compiler.codegen.generate_project — même mécanisme que
# `application { css: "..." }`), chargé une seule fois au démarrage.
# Chaque `{{champ}}` du fichier est remplacé par la valeur correspondante
# de l'enregistrement concerné au moment de l'envoi — voir
# render_email_template ci-dessous, et app/routers/<entite>.py qui
# l'appelle à la place du sujet/corps codés en dur plus haut.
TEMPLATE_PATH = Path(__file__).parent / "email_templates" / "notification.html"
try:
    _TEMPLATE_HTML = TEMPLATE_PATH.read_text(encoding="utf-8")
except OSError:  # pragma: no cover - le fichier est toujours présent en pratique
    _TEMPLATE_HTML = ""

_PLACEHOLDER_RE = re.compile(r"\{\{\s*(\w+)\s*\}\}")
_TITLE_RE = re.compile(r"<title[^>]*>(.*?)</title>", re.IGNORECASE | re.DOTALL)
_TAG_RE = re.compile(r"<[^>]+>")


def render_email_template(values: dict) -> tuple[str, str, str]:
    """Substitue chaque `{{cle}}` du template HTML externe par
    str(values.get(cle, "")) — jamais de KeyError : une clé absente du
    dictionnaire (ou valeur None) devient une chaîne vide plutôt que de
    faire échouer l'envoi. Dérive ensuite : (1) le sujet — depuis la balise
    <title>...</title> du HTML déjà substitué si présente (convention :
    c'est donc là qu'on personnalise le sujet), sinon un repli générique
    bilingue ; (2) le corps HTML — le template substitué tel quel ; (3) un
    repli texte brut (balises HTML retirées, lignes vides condensées) pour
    les clients mail qui n'affichent pas le HTML."""
    html = _PLACEHOLDER_RE.sub(lambda m: str(values.get(m.group(1)) or ""), _TEMPLATE_HTML)
    title_match = _TITLE_RE.search(html)
    if title_match:
        subject = title_match.group(1).strip()
    else:
        action = values.get("action", "")
        entity = values.get("entity", "Notification")
        subject = f"[NOVA] {entity} {action}".strip()
    text_body = _TAG_RE.sub("", html)
    text_body = re.sub(r"\n\s*\n+", "\n\n", text_body).strip()
    return subject, html, text_body
'''


def _has_uploads(program: NovaProgram) -> bool:
    """True si au moins un champ `file`/`fichier` ou `image` existe quelque
    part dans le programme — déclenche la génération du routeur d'upload et
    du montage de fichiers statiques (voir `_generate_uploads_router` et
    `_generate_main`)."""
    return any(f.type in ("file", "image") for e in program.entities for f in e.fields)


_UPLOADS_ROUTER_TEMPLATE = _HEADER + '''\
from __future__ import annotations

import io
import os
import uuid
from pathlib import Path

from fastapi import APIRouter, File, HTTPException, UploadFile

try:
    from PIL import Image
except ImportError:  # pragma: no cover - Pillow est toujours dans
    # requirements.txt dès qu'un champ file/image existe (voir generate_backend
    # ci-dessous) ; ce filet de sécurité évite seulement de planter à l'import
    # si l'environnement d'exécution s'écarte du requirements.txt généré.
    Image = None

# Toute cette configuration est surchargeable sans recompiler, via variable
# d'environnement (même principe que NOVA_JWT_SECRET/NOVA_SMTP_PASSWORD) :
# aucune limite de taille/type n'était appliquée par défaut avant cette
# fonctionnalité (limitation documentée du MVP) — ces valeurs par défaut
# sont volontairement permissives plutôt que de casser un projet existant.
UPLOADS_DIR = Path(os.environ.get("NOVA_UPLOADS_DIR", "uploads"))
UPLOADS_DIR.mkdir(parents=True, exist_ok=True)

# Taille max par fichier, en octets (défaut 10 Mo).
MAX_UPLOAD_BYTES = int(os.environ.get("NOVA_UPLOAD_MAX_BYTES", str(10 * 1024 * 1024)))

# Extensions autorisées (liste séparée par des virgules, insensible à la
# casse) — un sous-ensemble raisonnable par défaut (images + documents
# bureautiques courants + archives), pas une liste blanche exhaustive :
# à étendre via NOVA_UPLOAD_ALLOWED_EXTENSIONS si besoin (ex. vidéos).
_DEFAULT_ALLOWED_EXTENSIONS = (
    ".jpg,.jpeg,.png,.gif,.webp,.svg,.bmp,"
    ".pdf,.txt,.csv,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.zip"
)
ALLOWED_EXTENSIONS = {
    ext.strip().lower()
    for ext in os.environ.get("NOVA_UPLOAD_ALLOWED_EXTENSIONS", _DEFAULT_ALLOWED_EXTENSIONS).split(",")
    if ext.strip()
}

# Dimension max (largeur ou hauteur, en pixels) pour un fichier reconnu comme
# une image : au-delà, redimensionné (aspect ratio conservé) avant d'être
# écrit sur disque — évite qu'une photo directement sortie d'un appareil
# photo/smartphone (plusieurs dizaines de Mpx) alourdisse inutilement le
# stockage et le temps de chargement des vignettes générées (voir
# codegen/ui_reflex.py::_field_value_src, rendu `rx.image` en table/carte).
MAX_IMAGE_DIMENSION = int(os.environ.get("NOVA_UPLOAD_MAX_IMAGE_DIMENSION", "2000"))

router = APIRouter(prefix="/uploads", tags=["uploads"])


def _resize_if_oversized_image(content: bytes, suffix: str) -> bytes:
    """Si `content` est une image (ouverte avec succès par Pillow) dont une
    dimension dépasse MAX_IMAGE_DIMENSION, la redimensionne (thumbnail,
    aspect ratio conservé) et la ré-encode dans son format d'origine. Toute
    autre valeur de `content` (pas une image, ou Pillow absent) est
    retournée inchangée — la détection se fait sur le CONTENU réel, pas sur
    l'extension déclarée du fichier ni sur le type de champ NOVA d'origine,
    puisque ce routeur est partagé par tous les champs `file`/`image` du
    projet."""
    if Image is None:
        return content
    try:
        img = Image.open(io.BytesIO(content))
        img.load()  # force la lecture complète : détecte aussi un fichier corrompu
    except Exception:
        return content  # pas une image valide (ou format non supporté par Pillow)
    if img.width <= MAX_IMAGE_DIMENSION and img.height <= MAX_IMAGE_DIMENSION:
        return content
    img.thumbnail((MAX_IMAGE_DIMENSION, MAX_IMAGE_DIMENSION))
    out = io.BytesIO()
    fmt = img.format or "PNG"
    if fmt == "JPEG" and img.mode in ("RGBA", "P"):
        img = img.convert("RGB")  # JPEG ne supporte pas la transparence
    img.save(out, format=fmt)
    return out.getvalue()


@router.post("/")
async def upload_file(file: UploadFile = File(...)):
    """Reçoit un fichier et retourne son URL publique (`/files/<nom>`, servie
    par le montage `StaticFiles` de app/main.py) — à stocker telle quelle
    dans le champ `file`/`image` de l'entité concernée. Le formulaire Reflex
    généré fait cet appel automatiquement dès qu'un fichier est sélectionné,
    avant de soumettre le reste du formulaire (voir codegen/ui_reflex.py).

    Rejette (415) une extension absente de ALLOWED_EXTENSIONS et (413) un
    fichier dépassant MAX_UPLOAD_BYTES ; redimensionne automatiquement une
    image dépassant MAX_IMAGE_DIMENSION avant de l'écrire sur disque."""
    suffix = Path(file.filename or "").suffix.lower()
    if ALLOWED_EXTENSIONS and suffix not in ALLOWED_EXTENSIONS:
        raise HTTPException(
            status_code=415,
            detail=(
                f"Type de fichier non autorisé / Unsupported file type: '{suffix}'. "
                f"Autorisés / Allowed: {', '.join(sorted(ALLOWED_EXTENSIONS))}"
            ),
        )
    content = await file.read()
    if len(content) > MAX_UPLOAD_BYTES:
        raise HTTPException(
            status_code=413,
            detail=(
                f"Fichier trop volumineux / File too large: {len(content)} octets/bytes "
                f"(max {MAX_UPLOAD_BYTES})."
            ),
        )
    content = _resize_if_oversized_image(content, suffix)
    stored_name = f"{uuid.uuid4().hex}{suffix}"
    dest = UPLOADS_DIR / stored_name
    dest.write_bytes(content)
    return {"url": f"/files/{stored_name}"}
'''


def _calendar_ics_slug(cal) -> str:
    """Même slug que `codegen/ui_reflex.py::_calendar_ics_slug` (dupliqué
    plutôt que partagé entre les deux modules de codegen, comme le reste des
    fonctions de nommage de ce fichier — voir `_table_name`/`to_snake_case`
    utilisées indépendamment de leur pendant côté frontend)."""
    return to_snake_case(to_ascii_identifier(cal.name)).replace("_", "-")


_ICS_ESCAPE_HELPER = r'''
def _ics_escape(text: str) -> str:
    """Échappe les caractères spéciaux d'un champ texte iCalendar (SUMMARY...)
    — RFC 5545 section 3.3.11 : antislash, point-virgule, virgule et retour
    à la ligne doivent être précédés d'un antislash dans la valeur encodée."""
    return (
        text.replace("\\", "\\\\")
        .replace(";", "\\;")
        .replace(",", "\\,")
        .replace("\n", "\\n")
    )
'''


def _generate_calendar_ics_router(program: NovaProgram) -> str:
    """`backend/app/routers/_ics.py` — généré uniquement si au moins un bloc
    `calendar { ... }` est présent (voir `generate_backend`). Une route GET
    par calendrier (`/ics/<slug>.ics`) exportant les enregistrements de
    l'entité source au format iCalendar (RFC 5545) — sans nouvelle
    dépendance : le format est assez simple pour être produit par de
    simples f-strings (voir `_ics_escape` ci-dessus), pas besoin d'ajouter
    une bibliothèque au requirements.txt généré pour ça. Compatible avec un
    import ou un abonnement URL direct dans Google Calendar/Outlook/Apple
    Calendar. Chaque route hérite de la même protection par rôle que l'API
    de l'entité source (`api <Entite> { proteger: <role> }`), même logique
    que `codegen/ui_reflex.py::_chart_data_source`/`_calendar_data_source`
    pour la page Reflex correspondante — un calendrier protégé ne doit pas
    exposer un export non protégé de la même donnée."""
    lines = [
        _HEADER,
        "from __future__ import annotations",
        "",
        "from datetime import datetime, timezone",
        "",
        "from fastapi import APIRouter, Depends, Response",
        "from sqlmodel import Session, select",
        "",
        "from ..database import get_session",
        "from .. import models",
    ]
    cal_roles: dict[str, str | None] = {}
    for cal in program.calendars:
        api = next((a for a in program.apis if a.entity == cal.entity), None)
        cal_roles[cal.name] = api.protected_role if api else None
    if any(cal_roles.values()):
        lines.append("from ..auth import require_role")
    lines.append(_ICS_ESCAPE_HELPER)
    lines += [
        'router = APIRouter(prefix="/ics", tags=["calendriers"])',
        "",
        "",
    ]
    for cal in program.calendars:
        entity = program.get_entity(cal.entity)
        if entity is None:
            continue
        cls = _model_class_name(entity)
        slug = _calendar_ics_slug(cal)
        fn_name = to_snake_case(cal.name)
        date_field_snake = to_snake_case(cal.date_field)
        title_field_snake = to_snake_case(cal.title_field) if cal.title_field else None
        date_field_obj = next((f for f in entity.fields if f.name == cal.date_field), None)
        is_datetime = bool(date_field_obj and date_field_obj.type == "datetime")
        role = cal_roles.get(cal.name)
        route_decorator = f'@router.get("/{slug}.ics"'
        if role:
            route_decorator += f', dependencies=[Depends(require_role("{role}"))]'
        route_decorator += ")"
        title_default = repr(cal.entity)
        title_expr = (
            f'_ics_escape(str(getattr(item, "{title_field_snake}", "") or {title_default}))'
            if title_field_snake
            else f"_ics_escape({title_default})"
        )
        dtstart_expr = (
            "raw_date.strftime('%Y%m%dT%H%M%SZ')"
            if is_datetime
            else "raw_date.strftime('%Y%m%d')"
        )
        dtstart_prefix = "DTSTART" if is_datetime else "DTSTART;VALUE=DATE"
        lines += [
            route_decorator,
            f"def {fn_name}_ics(session: Session = Depends(get_session)):",
            f'    """Export iCalendar (.ics) du calendrier `{cal.name}` (source : {cal.entity}).',
            f'    Un événement par enregistrement dont `{cal.date_field}` n\'est pas vide."""',
            f"    items = session.exec(select(models.{cls})).all()",
            '    now_stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")',
            "    ics_lines = [",
            '        "BEGIN:VCALENDAR",',
            '        "VERSION:2.0",',
            f'        "PRODID:-//NOVA//{cal.name}//FR",',
            '        "CALSCALE:GREGORIAN",',
            "    ]",
            "    for item in items:",
            f'        raw_date = getattr(item, "{date_field_snake}", None)',
            "        if raw_date is None:",
            "            continue",
            f"        summary = {title_expr}",
            '        ics_lines.append("BEGIN:VEVENT")',
            f'        ics_lines.append(f"UID:{to_snake_case(cal.entity)}-{{item.id}}@nova.local")',
            '        ics_lines.append(f"DTSTAMP:{now_stamp}")',
            f'        ics_lines.append(f"{dtstart_prefix}:{{{dtstart_expr}}}")',
            '        ics_lines.append(f"SUMMARY:{summary}")',
            '        ics_lines.append("END:VEVENT")',
            "    ics_lines.append(\"END:VCALENDAR\")",
            '    return Response(content="\\r\\n".join(ics_lines), media_type="text/calendar")',
            "",
            "",
        ]
    return "\n".join(lines) + "\n"


def generate_backend(program: NovaProgram) -> dict[str, str]:
    has_auth = program.auth is not None and program.auth.enabled
    has_queries = bool(program.queries)
    has_uploads = _has_uploads(program)
    has_email = program.email is not None
    db_engine = program.database_engine()

    # `alembic` (tâche #38) : toujours présent côté backend SQL — la
    # structure `backend/migrations/` (voir _ALEMBIC_SCAFFOLD ci-dessous)
    # est générée systématiquement, que le projet utilise `nova migrate`
    # ou non (comme `routers_custom/`) ; MongoDB/Beanie (api_mongo.py) n'a
    # pas de schéma figé à faire migrer et n'en a donc jamais besoin.
    requirements = ["fastapi>=0.110", "uvicorn[standard]>=0.29", "sqlmodel>=0.0.16", "alembic>=1.13"]
    if db_engine in kw.DB_DRIVER_REQUIREMENTS:
        requirements.append(kw.DB_DRIVER_REQUIREMENTS[db_engine])
    if has_auth:
        requirements += ["bcrypt>=4.0", "python-jose[cryptography]>=3.3", "python-multipart>=0.0.9"]
    elif has_uploads:
        # python-multipart est requis par FastAPI pour parser tout endpoint
        # `UploadFile = File(...)` — déjà tiré par `has_auth` ci-dessus
        # (formulaire OAuth2), mais un projet sans `auth` avec un champ
        # `file`/`image` en a besoin tout autant.
        requirements.append("python-multipart>=0.0.9")
    if has_uploads:
        # Pillow : redimensionnement automatique des images dépassant
        # NOVA_UPLOAD_MAX_IMAGE_DIMENSION (voir _UPLOADS_ROUTER_TEMPLATE).
        requirements.append("Pillow>=10.0")

    files: dict[str, str] = {
        "backend/app/__init__.py": "",
        "backend/app/models.py": _generate_models(program),
        "backend/app/database.py": _generate_database(db_engine),
        "backend/app/routers/__init__.py": "",
        "backend/app/main.py": _generate_main(program),
        "backend/requirements.txt": "\n".join(requirements) + "\n",
    }
    if has_auth:
        files["backend/app/auth.py"] = _generate_auth(program)
    if has_queries:
        files["backend/app/routers/_requetes.py"] = _generate_query_router(program)
    if program.calendars:
        files["backend/app/routers/_ics.py"] = _generate_calendar_ics_router(program)
    if has_uploads:
        files["backend/app/routers/_uploads.py"] = _UPLOADS_ROUTER_TEMPLATE
    if has_email:
        files["backend/app/emailer.py"] = _generate_emailer(program)
        if program.email and program.email.template:
            # Réserve l'emplacement attendu par `render_email_template`
            # (voir _EMAIL_TEMPLATE_BLOCK) ; le *contenu réel* du fichier
            # référencé par `email { template: "..." }` est copié ici par
            # `nova_compiler.codegen.generate_project` (qui connaît le
            # dossier source du .nova) — même mécanisme que `application {
            # css: "..." }` pour la feuille de style externe.
            files["backend/app/email_templates/notification.html"] = (
                "<!-- Remplacé par le contenu du fichier référencé dans\n"
                f'     `email {{ template: "{program.email.template}" }}` si ce fichier a\n'
                "     été trouvé au moment de la compilation (voir\n"
                "     nova_compiler.codegen.generate_project). -->\n"
                "<html><body><p>{{action}} {{entity}} #{{id}}</p></body></html>\n"
            )
    for api in program.apis:
        entity = program.get_entity(api.entity)
        if entity is None:
            continue
        table = _table_name(entity)
        files[f"backend/app/routers/{table}.py"] = _generate_router(
            entity,
            api.actions,
            api.protected_role,
            api.notify_actions,
            api.notify_recipient_field,
            api.notify_attachment_field,
            program,
        )
    return files


_CUSTOM_ROUTER_EXAMPLE = '''\
"""
Exemple de routeur "custom" (backend/app/routers_custom/example.py).

Ce dossier n'est JAMAIS régénéré par `nova compile` : il est créé une seule
fois, puis laissé intact à chaque compilation suivante. C'est ici qu'écrire
tout ce que le DSL NOVA ne couvre pas — contrôles de formulaire avancés,
expressions régulières, requêtes complexes (jointures, agrégations),
écritures en base personnalisées, appels à des services externes.

Tout module de ce dossier exposant une variable `router` (un
`fastapi.APIRouter`) est automatiquement inclus par app/main.py : pas besoin
de toucher au fichier généré pour ajouter vos propres routes.
"""

from __future__ import annotations

import re

from fastapi import APIRouter, Depends, HTTPException
from sqlmodel import Session

from ..database import get_session

router = APIRouter(prefix="/custom", tags=["custom"])


@router.get("/ping")
def ping():
    """Vérifie que ce routeur custom est bien chargé."""
    return {"status": "custom router actif"}


# ---------------------------------------------------------------------------
# Exemple : validation par expression régulière avant écriture en base.
# Le DSL sait déjà générer une contrainte de ce type sur un champ simple
# (`champ email: chaine motif = "^[^@]+@[^@]+$"` -> voir models.py), mais
# toute logique plus riche (règles croisant plusieurs champs, dépendant de
# données en base, etc.) se code ici en Python normal.
# ---------------------------------------------------------------------------
_EMAIL_RE = re.compile(r"^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$")


@router.post("/exemple-validation")
def exemple_validation(email: str, session: Session = Depends(get_session)):
    if not _EMAIL_RE.match(email):
        raise HTTPException(status_code=422, detail="Email invalide")
    # Écriture en base directe via la Session SQLModel, exactement comme
    # dans les routeurs générés (voir app/routers/<entite>.py) :
    #   from ..models import MonEntite
    #   item = MonEntite(...)
    #   session.add(item); session.commit(); session.refresh(item)
    return {"email": email, "valide": True}


@router.get("/exemple-requete-complexe")
def exemple_requete_complexe(session: Session = Depends(get_session)):
    """Point de départ pour une requête au-delà du CRUD simple (jointure,
    agrégation SQL...). Remplacez ce corps par votre propre logique, en
    important vos modèles depuis `..models`."""
    return {"exemple": "adaptez cette fonction à vos propres modèles"}
'''


def generate_backend_scaffold() -> dict[str, str]:
    """Fichiers d'extension "custom" : créés une seule fois si absents,
    jamais réécrits par une compilation suivante (contrairement à
    `generate_backend`, dont le contenu est toujours régénéré)."""
    return {
        "backend/app/routers_custom/__init__.py": "",
        "backend/app/routers_custom/example.py": _CUSTOM_ROUTER_EXAMPLE,
        **_ALEMBIC_SCAFFOLD,
    }


# --------------------------------------------------------------------------- #
# Migrations Alembic (tâche #38) : structure générée UNE SEULE FOIS, comme
# `routers_custom/` ci-dessus — jamais réécrite par `nova compile`, puisque
# `migrations/versions/` accumule au fil du temps l'historique réel des
# migrations appliquées à la base (l'écraser à chaque compilation détruirait
# cet historique). La commande `nova migrate` (voir cli.py) appelle ensuite
# `alembic revision --autogenerate` puis `alembic upgrade head` dans ce
# dossier `backend/` — SQL uniquement : MongoDB/Beanie (voir api_mongo.py,
# generate_backend_scaffold_mongo) n'a pas de schéma figé à faire migrer.
# --------------------------------------------------------------------------- #

_ALEMBIC_INI = '''\
[alembic]
script_location = migrations
prepend_sys_path = .

# L'URL de connexion n'est JAMAIS codée en dur ici : `migrations/env.py`
# (voir ci-dessous) la lit dynamiquement depuis `app.database` (donc depuis
# NOVA_DATABASE_URL au runtime) — cette ligne reste vide volontairement.
sqlalchemy.url =

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
'''

_ALEMBIC_ENV_PY = '''\
"""env.py Alembic — NE PAS ÉDITER À LA MAIN sauf besoin spécifique : voir
`backend/app/routers_custom/` pour le mécanisme équivalent côté API. Ce
fichier fait partie de la structure Alembic générée UNE SEULE FOIS par
`nova compile` (tâche #38) : contrairement à `app/models.py`, il n'est
jamais régénéré automatiquement, donc toute modification manuelle ici
survit aux compilations suivantes.

Réutilise directement l'engine/l'URL de `app/database.py` (donc
NOVA_DATABASE_URL au runtime, jamais une valeur codée en dur dans
alembic.ini) et importe `app.models` pour que `SQLModel.metadata`
connaisse toutes les tables NOVA avant toute autogénération — sans cet
import, `alembic revision --autogenerate` ne verrait aucune table."""

from __future__ import annotations

from logging.config import fileConfig

from alembic import context
from sqlmodel import SQLModel

from app import models  # noqa: F401 - peuple SQLModel.metadata
from app.database import DATABASE_URL, engine

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = SQLModel.metadata


def run_migrations_offline() -> None:
    """Génère le SQL sans connexion réelle à la base (`alembic upgrade
    head --sql`) : utile pour relire/valider une migration avant de
    l'appliquer en production."""
    context.configure(
        url=DATABASE_URL,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Mode par défaut (`alembic upgrade head`, `alembic revision
    --autogenerate`, ...) : connexion réelle via l'engine SQLModel déjà
    configuré dans app/database.py."""
    with engine.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
'''

_ALEMBIC_SCRIPT_MAKO = '''\
"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
${imports if imports else ""}

# revision identifiers, used by Alembic.
revision = ${repr(up_revision)}
down_revision = ${repr(down_revision)}
branch_labels = ${repr(branch_labels)}
depends_on = ${repr(depends_on)}


def upgrade() -> None:
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    ${downgrades if downgrades else "pass"}
'''

_ALEMBIC_SCAFFOLD = {
    "backend/alembic.ini": _ALEMBIC_INI,
    "backend/migrations/env.py": _ALEMBIC_ENV_PY,
    "backend/migrations/script.py.mako": _ALEMBIC_SCRIPT_MAKO,
    # Dossier vide au départ (aucune migration n'a encore été générée) :
    # `.gitkeep` garantit que `migrations/versions/` existe bien avant le
    # premier `nova migrate` (requis par Alembic) et reste suivi par git
    # même sans fichier de révision dedans.
    "backend/migrations/versions/.gitkeep": "",
}
