"""
Générateur de backend : AST NOVA -> application FastAPI + SQLModel.

Un bloc `entity` devient une table SQLModel ; un bloc `api` associé devient
un routeur FastAPI avec les actions CRUD demandées (list/create/update/
delete/get, dans n'importe quelle langue à l'origine).
"""

from __future__ import annotations

from ..ast_nodes import Email as _Email
from ..ast_nodes import Entity, NovaProgram, QueryFilter
from .utils import PY_TYPE_MAP, pluralize, to_ascii_identifier, to_pascal_case, to_snake_case

_HEADER = (
    "# " + "-" * 76 + "\n"
    "# Fichier généré automatiquement par le compilateur NOVA. Ne pas éditer\n"
    "# à la main : régénérez à partir du fichier .nova source (`nova compile`).\n"
    "# Auto-generated by the NOVA compiler. Do not edit by hand: regenerate\n"
    "# from the source .nova file (`nova compile`).\n"
    "# " + "-" * 76 + "\n"
)


def _model_class_name(entity: Entity) -> str:
    return to_pascal_case(entity.name)


def _table_name(entity: Entity) -> str:
    return to_snake_case(pluralize(to_ascii_identifier(entity.name)))


def _field_line(entity: Entity, f) -> str:
    if not f.is_reference:
        py_type = PY_TYPE_MAP.get(f.type, "str")
        type_hint = py_type if f.required else f"Optional[{py_type}]"
        opts = []
        if f.unique:
            opts.append("unique=True")
        if f.pattern:
            opts.append(f'pattern=r"{f.pattern}"')
        if f.default is not None:
            opts.append(f"default={f.default!r}")
        elif not f.required:
            opts.append("default=None")
        opts_str = ", ".join(opts)
        suffix = f" = Field({opts_str})" if opts_str else ""
        return f"    {to_snake_case(f.name)}: {type_hint}{suffix}"
    else:
        # Référence vers une autre entité : clé étrangère simple sur son id.
        target_table = to_snake_case(pluralize(to_ascii_identifier(f.type)))
        return (
            f"    {to_snake_case(f.name)}_id: Optional[int] = "
            f'Field(default=None, foreign_key="{target_table}.id")'
        )


def _generate_models(program: NovaProgram) -> str:
    lines = [
        _HEADER,
        "from __future__ import annotations",
        "",
        "from datetime import date, datetime",
        "from typing import Optional",
        "",
        "from sqlmodel import Field, SQLModel",
        "",
        "",
    ]
    for entity in program.entities:
        cls = _model_class_name(entity)
        table = _table_name(entity)
        lines.append(f"class {cls}(SQLModel, table=True):")
        lines.append(f'    """Généré depuis `entity {entity.name}` / `entité {entity.name}`."""')
        lines.append(f'    __tablename__ = "{table}"')
        lines.append("")
        lines.append("    id: Optional[int] = Field(default=None, primary_key=True)")
        for f in entity.fields:
            lines.append(_field_line(entity, f))
        for rel in entity.relations:
            if rel.kind == "belongs_to":
                target_table = to_snake_case(pluralize(to_ascii_identifier(rel.target)))
                lines.append(
                    f"    {to_snake_case(rel.target)}_id: Optional[int] = "
                    f'Field(default=None, foreign_key="{target_table}.id")'
                )
            else:  # has_many -> informational, pas de colonne sur cette table
                lines.append(f"    # has_many / possède_plusieurs {rel.target} -> voir la table {to_snake_case(pluralize(to_ascii_identifier(rel.target)))}")
        lines.append("")
        lines.append("")

        # Schémas Create/Update/Read séparés du modèle table pour une API propre.
        # Les relations belongs_to sont exposées comme de simples clés étrangères
        # (<cible>_id) : c'est ce qui permet de rattacher un enregistrement à un
        # parent via l'API (sinon la relation serait indisponible en écriture).
        fk_field_names = [to_snake_case(rel.target) + "_id" for rel in entity.relations if rel.kind == "belongs_to"]

        lines.append(f"class {cls}Create(SQLModel):")
        body = [f for f in entity.fields]
        if not body and not fk_field_names:
            lines.append("    pass")
        for f in body:
            py_type = PY_TYPE_MAP.get(f.type, "str") if not f.is_reference else "int"
            type_hint = py_type if f.required else f"Optional[{py_type}]"
            if f.pattern:
                kwargs = f'pattern=r"{f.pattern}"' if f.required else f'default=None, pattern=r"{f.pattern}"'
                lines.append(f"    {to_snake_case(f.name)}: {type_hint} = Field({kwargs})")
            else:
                default = "" if f.required else " = None"
                lines.append(f"    {to_snake_case(f.name)}: {type_hint}{default}")
        for fk_name in fk_field_names:
            lines.append(f"    {fk_name}: Optional[int] = None")
        lines.append("")
        lines.append("")

        lines.append(f"class {cls}Update(SQLModel):")
        if not body and not fk_field_names:
            lines.append("    pass")
        for f in body:
            py_type = PY_TYPE_MAP.get(f.type, "str") if not f.is_reference else "int"
            if f.pattern:
                lines.append(
                    f'    {to_snake_case(f.name)}: Optional[{py_type}] = Field(default=None, pattern=r"{f.pattern}")'
                )
            else:
                lines.append(f"    {to_snake_case(f.name)}: Optional[{py_type}] = None")
        for fk_name in fk_field_names:
            lines.append(f"    {fk_name}: Optional[int] = None")
        lines.append("")
        lines.append("")

    return "\n".join(lines) + "\n"


def _generate_database() -> str:
    return _HEADER + '''
from __future__ import annotations

import os
from collections.abc import Iterator

from sqlmodel import Session, SQLModel, create_engine

DATABASE_URL = os.environ.get("NOVA_DATABASE_URL", "sqlite:///./nova.db")

connect_args = {"check_same_thread": False} if DATABASE_URL.startswith("sqlite") else {}
engine = create_engine(DATABASE_URL, echo=False, connect_args=connect_args)


def init_db() -> None:
    """Crée les tables si elles n'existent pas encore (suffisant pour un MVP)."""
    SQLModel.metadata.create_all(engine)


def get_session() -> Iterator[Session]:
    with Session(engine) as session:
        yield session
'''


def _generate_router(
    entity: Entity,
    actions: list[str],
    protected_role: str | None = None,
    notify_actions: list[str] | None = None,
) -> str:
    cls = _model_class_name(entity)
    table = _table_name(entity)
    var = to_snake_case(entity.name)
    tag = entity.name
    notify_actions = notify_actions or []

    lines = [
        _HEADER,
        "from __future__ import annotations",
        "",
        "from fastapi import APIRouter, Depends, HTTPException",
        "from sqlmodel import Session, select",
        "",
        "from ..database import get_session",
        f"from ..models import {cls}, {cls}Create, {cls}Update",
    ]
    if protected_role:
        lines.append("from ..auth import require_role")
    if notify_actions:
        # `notifier: ...` sur `api {entity.name} { ... }` (nécessite un bloc
        # `email { ... }` — validé à la compilation, voir parser.py).
        lines.append("from ..emailer import send_email")
    lines.append("")
    router_kwargs = f'prefix="/{table}", tags=["{tag}"]'
    if protected_role:
        # `proteger: <role>` dans le DSL protège TOUTES les actions de cette
        # API d'un coup — le plus simple à écrire, et le plus dur à oublier.
        router_kwargs += f', dependencies=[Depends(require_role("{protected_role}"))]'
    lines += [
        f"router = APIRouter({router_kwargs})",
        "",
        "",
    ]

    if "list" in actions:
        lines += [
            f'@router.get("/", response_model=list[{cls}])',
            f"def list_{table}(session: Session = Depends(get_session)):",
            f'    """list / liste — retourne tous les {tag}."""',
            f"    return session.exec(select({cls})).all()",
            "",
            "",
        ]

    if "get" in actions:
        lines += [
            f'@router.get("/{{item_id}}", response_model={cls})',
            f"def get_{var}(item_id: int, session: Session = Depends(get_session)):",
            f'    """get / obtenir / lire — retourne un {tag} par id."""',
            f"    item = session.get({cls}, item_id)",
            "    if item is None:",
            f'        raise HTTPException(status_code=404, detail="{tag} not found")',
            "    return item",
            "",
            "",
        ]

    if "create" in actions:
        lines += [
            f'@router.post("/", response_model={cls}, status_code=201)',
            f"def create_{var}(payload: {cls}Create, session: Session = Depends(get_session)):",
            f'    """create / créer — crée un nouveau {tag}."""',
            f"    item = {cls}.model_validate(payload)",
            "    session.add(item)",
            "    session.commit()",
            "    session.refresh(item)",
        ]
        if "create" in notify_actions:
            lines.append(
                f'    send_email(subject="[NOVA] Nouveau {tag} / New {tag}", '
                f'body=f"{tag} #{{item.id}} créé / created.")'
            )
        lines += [
            "    return item",
            "",
            "",
        ]

    if "update" in actions:
        lines += [
            f'@router.put("/{{item_id}}", response_model={cls})',
            f"def update_{var}(item_id: int, payload: {cls}Update, session: Session = Depends(get_session)):",
            f'    """update / modifier — met à jour un {tag} existant."""',
            f"    item = session.get({cls}, item_id)",
            "    if item is None:",
            f'        raise HTTPException(status_code=404, detail="{tag} not found")',
            "    for key, value in payload.model_dump(exclude_unset=True).items():",
            "        setattr(item, key, value)",
            "    session.add(item)",
            "    session.commit()",
            "    session.refresh(item)",
        ]
        if "update" in notify_actions:
            lines.append(
                f'    send_email(subject="[NOVA] {tag} modifié / updated", '
                f'body=f"{tag} #{{item.id}} mis à jour / updated.")'
            )
        lines += [
            "    return item",
            "",
            "",
        ]

    if "delete" in actions:
        lines += [
            f'@router.delete("/{{item_id}}", status_code=204)',
            f"def delete_{var}(item_id: int, session: Session = Depends(get_session)):",
            f'    """delete / supprimer — supprime un {tag}."""',
            f"    item = session.get({cls}, item_id)",
            "    if item is None:",
            f'        raise HTTPException(status_code=404, detail="{tag} not found")',
        ]
        if "delete" in notify_actions:
            # L'id est capturé avant `session.delete`/`commit` : l'objet est
            # expiré après le commit, `item.id` ne serait plus fiable ensuite.
            lines.append("    deleted_id = item.id")
        lines += [
            "    session.delete(item)",
            "    session.commit()",
        ]
        if "delete" in notify_actions:
            lines.append(
                f'    send_email(subject="[NOVA] {tag} supprimé / deleted", '
                f'body=f"{tag} #{{deleted_id}} supprimé / deleted.")'
            )
        lines += [
            "    return None",
            "",
        ]

    return "\n".join(lines) + "\n"


def _generate_main(program: NovaProgram) -> str:
    app_name = program.app.name if program.app else "NovaApp"
    has_auth = program.auth is not None and program.auth.enabled
    has_queries = bool(program.queries)
    has_uploads = _has_uploads(program)
    lines = [
        _HEADER,
        "from __future__ import annotations",
        "",
        "import importlib",
        "import pkgutil",
        "",
        "from fastapi import FastAPI",
        "from fastapi.middleware.cors import CORSMiddleware",
    ]
    if has_uploads:
        lines.append("from fastapi.staticfiles import StaticFiles")
    lines += [
        "",
        "from .database import init_db",
        "from . import routers_custom",
    ]
    if has_auth:
        lines.append("from .auth import router as auth_router")
    if has_queries:
        lines.append("from .routers._requetes import router as requetes_router")
    if has_uploads:
        lines.append("from .routers._uploads import router as uploads_router, UPLOADS_DIR")
    for api in program.apis:
        entity = program.get_entity(api.entity)
        if entity is None:
            continue
        table = _table_name(entity)
        lines.append(f"from .routers.{table} import router as {table}_router")
    lines += [
        "",
        f'app = FastAPI(title="{app_name}", description="Généré par NOVA / Generated by NOVA")',
        "",
        "app.add_middleware(",
        "    CORSMiddleware,",
        '    allow_origins=["*"],',
        "    allow_methods=[\"*\"],",
        "    allow_headers=[\"*\"],",
        ")",
        "",
        "",
        "@app.on_event(\"startup\")",
        "def on_startup() -> None:",
        "    init_db()",
        "",
        "",
    ]
    if has_uploads:
        # Chemin distinct de "/uploads" (le routeur POST ci-dessous) pour
        # éviter tout conflit de préfixe entre le Mount ASGI (fichiers
        # statiques, GET) et l'APIRouter (upload, POST).
        lines.append('app.mount("/files", StaticFiles(directory=str(UPLOADS_DIR)), name="files")')
    if has_auth:
        lines.append("app.include_router(auth_router)")
    if has_queries:
        lines.append("app.include_router(requetes_router)")
    if has_uploads:
        lines.append("app.include_router(uploads_router)")
    for api in program.apis:
        entity = program.get_entity(api.entity)
        if entity is None:
            continue
        table = _table_name(entity)
        lines.append(f"app.include_router({table}_router)")
    lines += [
        "",
        "# Logique métier hors DSL (validations avancées, requêtes complexes,",
        "# écritures en base sur mesure...) : tout module de app/routers_custom/",
        "# exposant une variable `router` est inclus automatiquement. Ce dossier",
        "# n'est jamais régénéré par `nova compile` — voir routers_custom/example.py.",
        "for _finder, _mod_name, _ispkg in pkgutil.iter_modules(routers_custom.__path__):",
        '    _custom_mod = importlib.import_module(f".routers_custom.{_mod_name}", package=__package__)',
        '    if hasattr(_custom_mod, "router"):',
        "        app.include_router(_custom_mod.router)",
        "",
        "",
        '@app.get("/health")',
        "def health():",
        '    return {"status": "ok"}',
        "",
    ]
    return "\n".join(lines) + "\n"


def _generate_auth(program: NovaProgram) -> str:
    auth = program.auth
    roles = auth.roles if auth and auth.roles else ["user"]
    default_role = auth.default_role if auth else "user"
    roles_literal = "[" + ", ".join(repr(r) for r in roles) + "]"
    return _HEADER + f'''
from __future__ import annotations

import os
from datetime import datetime, timedelta, timezone
from typing import Optional

import bcrypt
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.security import OAuth2PasswordBearer, OAuth2PasswordRequestForm
from jose import JWTError, jwt
from sqlmodel import Field, Session, SQLModel, select

from .database import get_session

# Bloc `auth {{ ... }}` du fichier .nova : rôles déclarés et rôle par défaut
# attribué à l'inscription si aucun n'est précisé.
ROLES = {roles_literal}
DEFAULT_ROLE = "{default_role}"

# Clé de signature JWT : à définir en production via la variable
# d'environnement NOVA_JWT_SECRET. La valeur par défaut ci-dessous permet au
# projet généré de démarrer "out of the box" — ne JAMAIS l'utiliser telle
# quelle en production.
SECRET_KEY = os.environ.get("NOVA_JWT_SECRET", "nova-dev-secret-change-me")
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 60 * 24

# Hachage direct via la bibliothèque `bcrypt` (et non `passlib`, dont
# l'intégration bcrypt est cassée avec les versions récentes de la
# bibliothèque `bcrypt` — `passlib`, non maintenu depuis 2020, échoue avec
# une `ValueError` sans rapport à l'exécution — voir la doc du framework).
oauth2_scheme = OAuth2PasswordBearer(tokenUrl="/auth/login", auto_error=False)


class User(SQLModel, table=True):
    """Table utilisateur générée par le bloc `auth {{ ... }}` — indépendante
    des entités du DSL."""

    __tablename__ = "nova_users"

    id: Optional[int] = Field(default=None, primary_key=True)
    email: str = Field(unique=True, index=True)
    password_hash: str
    role: str = Field(default=DEFAULT_ROLE)
    created_at: datetime = Field(default_factory=datetime.utcnow)


class UserCreate(SQLModel):
    email: str
    password: str
    role: Optional[str] = None


class UserRead(SQLModel):
    id: int
    email: str
    role: str


def hash_password(password: str) -> str:
    return bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt()).decode("utf-8")


def verify_password(password: str, password_hash: str) -> bool:
    return bcrypt.checkpw(password.encode("utf-8"), password_hash.encode("utf-8"))


def create_access_token(data: dict) -> str:
    to_encode = data.copy()
    expire = datetime.now(timezone.utc) + timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)
    to_encode.update({{"exp": expire}})
    return jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)


def get_current_user(
    token: Optional[str] = Depends(oauth2_scheme), session: Session = Depends(get_session)
) -> User:
    credentials_error = HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Identifiants invalides ou absents / Missing or invalid credentials",
        headers={{"WWW-Authenticate": "Bearer"}},
    )
    if token is None:
        raise credentials_error
    try:
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        email = payload.get("sub")
        if email is None:
            raise credentials_error
    except JWTError:
        raise credentials_error
    user = session.exec(select(User).where(User.email == email)).first()
    if user is None:
        raise credentials_error
    return user


def require_role(role: str):
    """Dépendance FastAPI protégeant une route/un routeur pour un rôle donné
    (utilisée automatiquement pour `api Xxx {{ ... proteger: <role> }}`) —
    un utilisateur "admin" passe toujours, quel que soit le rôle requis."""

    def _dependency(user: User = Depends(get_current_user)) -> User:
        if user.role != role and user.role != "admin":
            raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Accès refusé / Forbidden")
        return user

    return _dependency


router = APIRouter(prefix="/auth", tags=["auth"])


@router.post("/register", response_model=UserRead, status_code=201)
def register(payload: UserCreate, session: Session = Depends(get_session)):
    existing = session.exec(select(User).where(User.email == payload.email)).first()
    if existing is not None:
        raise HTTPException(status_code=400, detail="Email déjà utilisé / Email already registered")
    role = payload.role if payload.role in ROLES else DEFAULT_ROLE
    user = User(email=payload.email, password_hash=hash_password(payload.password), role=role)
    session.add(user)
    session.commit()
    session.refresh(user)
    return user


@router.post("/login")
def login(form_data: OAuth2PasswordRequestForm = Depends(), session: Session = Depends(get_session)):
    """Compatible OAuth2PasswordRequestForm : envoyer `username` (= email) et
    `password` en `application/x-www-form-urlencoded`."""
    user = session.exec(select(User).where(User.email == form_data.username)).first()
    if user is None or not verify_password(form_data.password, user.password_hash):
        raise HTTPException(status_code=401, detail="Identifiants invalides / Invalid credentials")
    token = create_access_token({{"sub": user.email, "role": user.role}})
    return {{"access_token": token, "token_type": "bearer"}}


@router.get("/me", response_model=UserRead)
def me(user: User = Depends(get_current_user)):
    return user
'''


def _format_query_value(value) -> str:
    if isinstance(value, str):
        return repr(value)
    return repr(value)


def _generate_query_router(program: NovaProgram) -> str:
    lines = [
        _HEADER,
        "from __future__ import annotations",
        "",
        "from fastapi import APIRouter, Depends",
        "from sqlmodel import Session, select",
        "",
        "from ..database import get_session",
        "from .. import models",
        "",
        'router = APIRouter(prefix="/requetes", tags=["requetes"])',
        "",
        "",
    ]
    for q in program.queries:
        entity = program.get_entity(q.entity)
        cls = to_pascal_case(entity.name) if entity else to_pascal_case(q.entity)
        slug = to_snake_case(q.name).replace("_", "-")
        fn_name = to_snake_case(q.name)
        lines += [
            f'@router.get("/{slug}", response_model=list[models.{cls}])',
            f"def {fn_name}(session: Session = Depends(get_session)):",
            f'    """Requête déclarative `requete {q.name} sur {q.entity} {{ ... }}` du fichier .nova."""',
            f"    query = select(models.{cls})",
        ]
        for f in q.filters:
            snake = to_snake_case(f.field)
            lines.append(f"    query = query.where(models.{cls}.{snake} {f.op} {_format_query_value(f.value)})")
        if q.order_by:
            snake = to_snake_case(q.order_by)
            direction = "desc" if q.order_dir == "desc" else "asc"
            lines.append(f"    query = query.order_by(models.{cls}.{snake}.{direction}())")
        if q.limit is not None:
            lines.append(f"    query = query.limit({q.limit})")
        lines += [
            "    return session.exec(query).all()",
            "",
            "",
        ]
    return "\n".join(lines) + "\n"


def _generate_emailer(program: NovaProgram) -> str:
    """`backend/app/emailer.py` — généré uniquement si un bloc `email {
    ... }` est présent (voir `generate_backend`). Les valeurs du bloc
    servent de valeur par défaut, surchargeables sans recompiler via des
    variables d'environnement — sauf le mot de passe, jamais porté par
    `ast_nodes.Email` (voir son docstring), donc toujours vide par défaut
    ici : NOVA_SMTP_PASSWORD est la seule source possible."""
    email = program.email or _Email()
    tls_default = "true" if email.tls else "false"
    return (
        _HEADER
        + f'''
from __future__ import annotations

import logging
import os
import smtplib
from email.message import EmailMessage

logger = logging.getLogger("nova.email")

# Bloc `email {{ ... }}` du fichier .nova : valeurs par défaut ci-dessous,
# surchargeables sans recompiler via NOVA_SMTP_HOST / NOVA_SMTP_PORT /
# NOVA_SMTP_USER / NOVA_SMTP_FROM / NOVA_SMTP_TO / NOVA_SMTP_TLS. Le mot de
# passe SMTP n'est JAMAIS lu depuis le fichier .nova (aucun secret en clair
# dans le code source généré) : toujours NOVA_SMTP_PASSWORD, vide par
# défaut (pas d'authentification SMTP tant qu'elle n'est pas fournie au
# runtime — même philosophie que NOVA_JWT_SECRET pour l'auth).
SMTP_HOST = os.environ.get("NOVA_SMTP_HOST", "{email.host}")
SMTP_PORT = int(os.environ.get("NOVA_SMTP_PORT", "{email.port}"))
SMTP_USER = os.environ.get("NOVA_SMTP_USER", "{email.user}")
SMTP_PASSWORD = os.environ.get("NOVA_SMTP_PASSWORD", "")
SMTP_FROM = os.environ.get("NOVA_SMTP_FROM", "{email.from_addr}")
SMTP_TO = os.environ.get("NOVA_SMTP_TO", "{email.to_addr}")
SMTP_TLS = os.environ.get("NOVA_SMTP_TLS", "{tls_default}").strip().lower() not in ("0", "false", "non", "no")


def send_email(subject: str, body: str, to: str | None = None) -> None:
    """Envoie un email texte simple — notification déclenchée par
    `notifier:` sur un bloc `api` (voir app/routers/<entite>.py). Toute
    erreur (serveur SMTP injoignable, identifiants invalides...) est
    loggée en warning et n'interrompt JAMAIS l'appelant : une notification
    est un effet de bord, pas une garantie — un souci SMTP ne doit jamais
    faire échouer une création/modification/suppression d'enregistrement."""
    recipient = to or SMTP_TO
    if not recipient:
        logger.warning("NOVA email: aucun destinataire configuré (NOVA_SMTP_TO), notification ignorée.")
        return
    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = SMTP_FROM or SMTP_USER or "noreply@nova.local"
    msg["To"] = recipient
    msg.set_content(body)
    try:
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=10) as smtp:
            if SMTP_TLS:
                smtp.starttls()
            if SMTP_USER and SMTP_PASSWORD:
                smtp.login(SMTP_USER, SMTP_PASSWORD)
            smtp.send_message(msg)
    except Exception as exc:  # pragma: no cover - dépend d'un serveur SMTP réel
        logger.warning("NOVA email: envoi échoué (%s) — notification ignorée.", exc)
'''
    )


def _has_uploads(program: NovaProgram) -> bool:
    """True si au moins un champ `file`/`fichier` ou `image` existe quelque
    part dans le programme — déclenche la génération du routeur d'upload et
    du montage de fichiers statiques (voir `_generate_uploads_router` et
    `_generate_main`)."""
    return any(f.type in ("file", "image") for e in program.entities for f in e.fields)


_UPLOADS_ROUTER_TEMPLATE = _HEADER + '''\
from __future__ import annotations

import os
import uuid
from pathlib import Path

from fastapi import APIRouter, File, UploadFile

# Dossier de stockage des fichiers envoyés via un champ `file`/`fichier` ou
# `image` du DSL. Chemin surchargeable via NOVA_UPLOADS_DIR (relatif au
# répertoire de travail du conteneur backend — déjà persistant via le volume
# Docker `backend_data:/app`, voir codegen/docker.py, comme la base SQLite).
UPLOADS_DIR = Path(os.environ.get("NOVA_UPLOADS_DIR", "uploads"))
UPLOADS_DIR.mkdir(parents=True, exist_ok=True)

router = APIRouter(prefix="/uploads", tags=["uploads"])


@router.post("/")
async def upload_file(file: UploadFile = File(...)):
    """Reçoit un fichier et retourne son URL publique (`/files/<nom>`, servie
    par le montage `StaticFiles` de app/main.py) — à stocker telle quelle
    dans le champ `file`/`image` de l'entité concernée. Le formulaire Reflex
    généré fait cet appel automatiquement dès qu'un fichier est sélectionné,
    avant de soumettre le reste du formulaire (voir codegen/ui_reflex.py)."""
    suffix = Path(file.filename or "").suffix
    stored_name = f"{uuid.uuid4().hex}{suffix}"
    dest = UPLOADS_DIR / stored_name
    content = await file.read()
    dest.write_bytes(content)
    return {"url": f"/files/{stored_name}"}
'''


def generate_backend(program: NovaProgram) -> dict[str, str]:
    has_auth = program.auth is not None and program.auth.enabled
    has_queries = bool(program.queries)
    has_uploads = _has_uploads(program)
    has_email = program.email is not None

    requirements = ["fastapi>=0.110", "uvicorn[standard]>=0.29", "sqlmodel>=0.0.16"]
    if has_auth:
        requirements += ["bcrypt>=4.0", "python-jose[cryptography]>=3.3", "python-multipart>=0.0.9"]
    elif has_uploads:
        # python-multipart est requis par FastAPI pour parser tout endpoint
        # `UploadFile = File(...)` — déjà tiré par `has_auth` ci-dessus
        # (formulaire OAuth2), mais un projet sans `auth` avec un champ
        # `file`/`image` en a besoin tout autant.
        requirements.append("python-multipart>=0.0.9")

    files: dict[str, str] = {
        "backend/app/__init__.py": "",
        "backend/app/models.py": _generate_models(program),
        "backend/app/database.py": _generate_database(),
        "backend/app/routers/__init__.py": "",
        "backend/app/main.py": _generate_main(program),
        "backend/requirements.txt": "\n".join(requirements) + "\n",
    }
    if has_auth:
        files["backend/app/auth.py"] = _generate_auth(program)
    if has_queries:
        files["backend/app/routers/_requetes.py"] = _generate_query_router(program)
    if has_uploads:
        files["backend/app/routers/_uploads.py"] = _UPLOADS_ROUTER_TEMPLATE
    if has_email:
        files["backend/app/emailer.py"] = _generate_emailer(program)
    for api in program.apis:
        entity = program.get_entity(api.entity)
        if entity is None:
            continue
        table = _table_name(entity)
        files[f"backend/app/routers/{table}.py"] = _generate_router(
            entity, api.actions, api.protected_role, api.notify_actions
        )
    return files


_CUSTOM_ROUTER_EXAMPLE = '''\
"""
Exemple de routeur "custom" (backend/app/routers_custom/example.py).

Ce dossier n'est JAMAIS régénéré par `nova compile` : il est créé une seule
fois, puis laissé intact à chaque compilation suivante. C'est ici qu'écrire
tout ce que le DSL NOVA ne couvre pas — contrôles de formulaire avancés,
expressions régulières, requêtes complexes (jointures, agrégations),
écritures en base personnalisées, appels à des services externes.

Tout module de ce dossier exposant une variable `router` (un
`fastapi.APIRouter`) est automatiquement inclus par app/main.py : pas besoin
de toucher au fichier généré pour ajouter vos propres routes.
"""

from __future__ import annotations

import re

from fastapi import APIRouter, Depends, HTTPException
from sqlmodel import Session

from ..database import get_session

router = APIRouter(prefix="/custom", tags=["custom"])


@router.get("/ping")
def ping():
    """Vérifie que ce routeur custom est bien chargé."""
    return {"status": "custom router actif"}


# ---------------------------------------------------------------------------
# Exemple : validation par expression régulière avant écriture en base.
# Le DSL sait déjà générer une contrainte de ce type sur un champ simple
# (`champ email: chaine motif = "^[^@]+@[^@]+$"` -> voir models.py), mais
# toute logique plus riche (règles croisant plusieurs champs, dépendant de
# données en base, etc.) se code ici en Python normal.
# ---------------------------------------------------------------------------
_EMAIL_RE = re.compile(r"^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$")


@router.post("/exemple-validation")
def exemple_validation(email: str, session: Session = Depends(get_session)):
    if not _EMAIL_RE.match(email):
        raise HTTPException(status_code=422, detail="Email invalide")
    # Écriture en base directe via la Session SQLModel, exactement comme
    # dans les routeurs générés (voir app/routers/<entite>.py) :
    #   from ..models import MonEntite
    #   item = MonEntite(...)
    #   session.add(item); session.commit(); session.refresh(item)
    return {"email": email, "valide": True}


@router.get("/exemple-requete-complexe")
def exemple_requete_complexe(session: Session = Depends(get_session)):
    """Point de départ pour une requête au-delà du CRUD simple (jointure,
    agrégation SQL...). Remplacez ce corps par votre propre logique, en
    important vos modèles depuis `..models`."""
    return {"exemple": "adaptez cette fonction à vos propres modèles"}
'''


def generate_backend_scaffold() -> dict[str, str]:
    """Fichiers d'extension "custom" : créés une seule fois si absents,
    jamais réécrits par une compilation suivante (contrairement à
    `generate_backend`, dont le contenu est toujours régénéré)."""
    return {
        "backend/app/routers_custom/__init__.py": "",
        "backend/app/routers_custom/example.py": _CUSTOM_ROUTER_EXAMPLE,
    }
