"""
Générateur de backend : AST NOVA -> application FastAPI + SQLModel.

Un bloc `entity` devient une table SQLModel ; un bloc `api` associé devient
un routeur FastAPI avec les actions CRUD demandées (list/create/update/
delete/get, dans n'importe quelle langue à l'origine).
"""

from __future__ import annotations

from ..ast_nodes import Entity, NovaProgram
from .utils import PY_TYPE_MAP, pluralize, to_ascii_identifier, to_pascal_case, to_snake_case

_HEADER = (
    "# " + "-" * 76 + "\n"
    "# Fichier généré automatiquement par le compilateur NOVA. Ne pas éditer\n"
    "# à la main : régénérez à partir du fichier .nova source (`nova compile`).\n"
    "# Auto-generated by the NOVA compiler. Do not edit by hand: regenerate\n"
    "# from the source .nova file (`nova compile`).\n"
    "# " + "-" * 76 + "\n"
)


def _model_class_name(entity: Entity) -> str:
    return to_pascal_case(entity.name)


def _table_name(entity: Entity) -> str:
    return to_snake_case(pluralize(to_ascii_identifier(entity.name)))


def _field_line(entity: Entity, f) -> str:
    if not f.is_reference:
        py_type = PY_TYPE_MAP.get(f.type, "str")
        type_hint = py_type if f.required else f"Optional[{py_type}]"
        opts = []
        if f.unique:
            opts.append("unique=True")
        if f.pattern:
            opts.append(f'pattern=r"{f.pattern}"')
        if f.default is not None:
            opts.append(f"default={f.default!r}")
        elif not f.required:
            opts.append("default=None")
        opts_str = ", ".join(opts)
        suffix = f" = Field({opts_str})" if opts_str else ""
        return f"    {to_snake_case(f.name)}: {type_hint}{suffix}"
    else:
        # Référence vers une autre entité : clé étrangère simple sur son id.
        target_table = to_snake_case(pluralize(to_ascii_identifier(f.type)))
        return (
            f"    {to_snake_case(f.name)}_id: Optional[int] = "
            f'Field(default=None, foreign_key="{target_table}.id")'
        )


def _generate_models(program: NovaProgram) -> str:
    lines = [
        _HEADER,
        "from __future__ import annotations",
        "",
        "from datetime import date, datetime",
        "from typing import Optional",
        "",
        "from sqlmodel import Field, SQLModel",
        "",
        "",
    ]
    for entity in program.entities:
        cls = _model_class_name(entity)
        table = _table_name(entity)
        lines.append(f"class {cls}(SQLModel, table=True):")
        lines.append(f'    """Généré depuis `entity {entity.name}` / `entité {entity.name}`."""')
        lines.append(f'    __tablename__ = "{table}"')
        lines.append("")
        lines.append("    id: Optional[int] = Field(default=None, primary_key=True)")
        for f in entity.fields:
            lines.append(_field_line(entity, f))
        for rel in entity.relations:
            if rel.kind == "belongs_to":
                target_table = to_snake_case(pluralize(to_ascii_identifier(rel.target)))
                lines.append(
                    f"    {to_snake_case(rel.target)}_id: Optional[int] = "
                    f'Field(default=None, foreign_key="{target_table}.id")'
                )
            else:  # has_many -> informational, pas de colonne sur cette table
                lines.append(f"    # has_many / possède_plusieurs {rel.target} -> voir la table {to_snake_case(pluralize(to_ascii_identifier(rel.target)))}")
        lines.append("")
        lines.append("")

        # Schémas Create/Update/Read séparés du modèle table pour une API propre.
        # Les relations belongs_to sont exposées comme de simples clés étrangères
        # (<cible>_id) : c'est ce qui permet de rattacher un enregistrement à un
        # parent via l'API (sinon la relation serait indisponible en écriture).
        fk_field_names = [to_snake_case(rel.target) + "_id" for rel in entity.relations if rel.kind == "belongs_to"]

        lines.append(f"class {cls}Create(SQLModel):")
        body = [f for f in entity.fields]
        if not body and not fk_field_names:
            lines.append("    pass")
        for f in body:
            py_type = PY_TYPE_MAP.get(f.type, "str") if not f.is_reference else "int"
            type_hint = py_type if f.required else f"Optional[{py_type}]"
            if f.pattern:
                kwargs = f'pattern=r"{f.pattern}"' if f.required else f'default=None, pattern=r"{f.pattern}"'
                lines.append(f"    {to_snake_case(f.name)}: {type_hint} = Field({kwargs})")
            else:
                default = "" if f.required else " = None"
                lines.append(f"    {to_snake_case(f.name)}: {type_hint}{default}")
        for fk_name in fk_field_names:
            lines.append(f"    {fk_name}: Optional[int] = None")
        lines.append("")
        lines.append("")

        lines.append(f"class {cls}Update(SQLModel):")
        if not body and not fk_field_names:
            lines.append("    pass")
        for f in body:
            py_type = PY_TYPE_MAP.get(f.type, "str") if not f.is_reference else "int"
            if f.pattern:
                lines.append(
                    f'    {to_snake_case(f.name)}: Optional[{py_type}] = Field(default=None, pattern=r"{f.pattern}")'
                )
            else:
                lines.append(f"    {to_snake_case(f.name)}: Optional[{py_type}] = None")
        for fk_name in fk_field_names:
            lines.append(f"    {fk_name}: Optional[int] = None")
        lines.append("")
        lines.append("")

    return "\n".join(lines) + "\n"


def _generate_database() -> str:
    return _HEADER + '''
from __future__ import annotations

import os
from collections.abc import Iterator

from sqlmodel import Session, SQLModel, create_engine

DATABASE_URL = os.environ.get("NOVA_DATABASE_URL", "sqlite:///./nova.db")

connect_args = {"check_same_thread": False} if DATABASE_URL.startswith("sqlite") else {}
engine = create_engine(DATABASE_URL, echo=False, connect_args=connect_args)


def init_db() -> None:
    """Crée les tables si elles n'existent pas encore (suffisant pour un MVP)."""
    SQLModel.metadata.create_all(engine)


def get_session() -> Iterator[Session]:
    with Session(engine) as session:
        yield session
'''


def _generate_router(entity: Entity, actions: list[str]) -> str:
    cls = _model_class_name(entity)
    table = _table_name(entity)
    var = to_snake_case(entity.name)
    tag = entity.name

    lines = [
        _HEADER,
        "from __future__ import annotations",
        "",
        "from fastapi import APIRouter, Depends, HTTPException",
        "from sqlmodel import Session, select",
        "",
        "from ..database import get_session",
        f"from ..models import {cls}, {cls}Create, {cls}Update",
        "",
        f'router = APIRouter(prefix="/{table}", tags=["{tag}"])',
        "",
        "",
    ]

    if "list" in actions:
        lines += [
            f'@router.get("/", response_model=list[{cls}])',
            f"def list_{table}(session: Session = Depends(get_session)):",
            f'    """list / liste — retourne tous les {tag}."""',
            f"    return session.exec(select({cls})).all()",
            "",
            "",
        ]

    if "get" in actions:
        lines += [
            f'@router.get("/{{item_id}}", response_model={cls})',
            f"def get_{var}(item_id: int, session: Session = Depends(get_session)):",
            f'    """get / obtenir / lire — retourne un {tag} par id."""',
            f"    item = session.get({cls}, item_id)",
            "    if item is None:",
            f'        raise HTTPException(status_code=404, detail="{tag} not found")',
            "    return item",
            "",
            "",
        ]

    if "create" in actions:
        lines += [
            f'@router.post("/", response_model={cls}, status_code=201)',
            f"def create_{var}(payload: {cls}Create, session: Session = Depends(get_session)):",
            f'    """create / créer — crée un nouveau {tag}."""',
            f"    item = {cls}.model_validate(payload)",
            "    session.add(item)",
            "    session.commit()",
            "    session.refresh(item)",
            "    return item",
            "",
            "",
        ]

    if "update" in actions:
        lines += [
            f'@router.put("/{{item_id}}", response_model={cls})',
            f"def update_{var}(item_id: int, payload: {cls}Update, session: Session = Depends(get_session)):",
            f'    """update / modifier — met à jour un {tag} existant."""',
            f"    item = session.get({cls}, item_id)",
            "    if item is None:",
            f'        raise HTTPException(status_code=404, detail="{tag} not found")',
            "    for key, value in payload.model_dump(exclude_unset=True).items():",
            "        setattr(item, key, value)",
            "    session.add(item)",
            "    session.commit()",
            "    session.refresh(item)",
            "    return item",
            "",
            "",
        ]

    if "delete" in actions:
        lines += [
            f'@router.delete("/{{item_id}}", status_code=204)',
            f"def delete_{var}(item_id: int, session: Session = Depends(get_session)):",
            f'    """delete / supprimer — supprime un {tag}."""',
            f"    item = session.get({cls}, item_id)",
            "    if item is None:",
            f'        raise HTTPException(status_code=404, detail="{tag} not found")',
            "    session.delete(item)",
            "    session.commit()",
            "    return None",
            "",
        ]

    return "\n".join(lines) + "\n"


def _generate_main(program: NovaProgram) -> str:
    app_name = program.app.name if program.app else "NovaApp"
    lines = [
        _HEADER,
        "from __future__ import annotations",
        "",
        "import importlib",
        "import pkgutil",
        "",
        "from fastapi import FastAPI",
        "from fastapi.middleware.cors import CORSMiddleware",
        "",
        "from .database import init_db",
        "from . import routers_custom",
    ]
    for api in program.apis:
        entity = program.get_entity(api.entity)
        if entity is None:
            continue
        table = _table_name(entity)
        lines.append(f"from .routers.{table} import router as {table}_router")
    lines += [
        "",
        f'app = FastAPI(title="{app_name}", description="Généré par NOVA / Generated by NOVA")',
        "",
        "app.add_middleware(",
        "    CORSMiddleware,",
        '    allow_origins=["*"],',
        "    allow_methods=[\"*\"],",
        "    allow_headers=[\"*\"],",
        ")",
        "",
        "",
        "@app.on_event(\"startup\")",
        "def on_startup() -> None:",
        "    init_db()",
        "",
        "",
    ]
    for api in program.apis:
        entity = program.get_entity(api.entity)
        if entity is None:
            continue
        table = _table_name(entity)
        lines.append(f"app.include_router({table}_router)")
    lines += [
        "",
        "# Logique métier hors DSL (validations avancées, requêtes complexes,",
        "# écritures en base sur mesure...) : tout module de app/routers_custom/",
        "# exposant une variable `router` est inclus automatiquement. Ce dossier",
        "# n'est jamais régénéré par `nova compile` — voir routers_custom/example.py.",
        "for _finder, _mod_name, _ispkg in pkgutil.iter_modules(routers_custom.__path__):",
        '    _custom_mod = importlib.import_module(f".routers_custom.{_mod_name}", package=__package__)',
        '    if hasattr(_custom_mod, "router"):',
        "        app.include_router(_custom_mod.router)",
        "",
        "",
        '@app.get("/health")',
        "def health():",
        '    return {"status": "ok"}',
        "",
    ]
    return "\n".join(lines) + "\n"


def generate_backend(program: NovaProgram) -> dict[str, str]:
    files: dict[str, str] = {
        "backend/app/__init__.py": "",
        "backend/app/models.py": _generate_models(program),
        "backend/app/database.py": _generate_database(),
        "backend/app/routers/__init__.py": "",
        "backend/app/main.py": _generate_main(program),
        "backend/requirements.txt": (
            "fastapi>=0.110\nuvicorn[standard]>=0.29\nsqlmodel>=0.0.16\n"
        ),
    }
    for api in program.apis:
        entity = program.get_entity(api.entity)
        if entity is None:
            continue
        table = _table_name(entity)
        files[f"backend/app/routers/{table}.py"] = _generate_router(entity, api.actions)
    return files


_CUSTOM_ROUTER_EXAMPLE = '''\
"""
Exemple de routeur "custom" (backend/app/routers_custom/example.py).

Ce dossier n'est JAMAIS régénéré par `nova compile` : il est créé une seule
fois, puis laissé intact à chaque compilation suivante. C'est ici qu'écrire
tout ce que le DSL NOVA ne couvre pas — contrôles de formulaire avancés,
expressions régulières, requêtes complexes (jointures, agrégations),
écritures en base personnalisées, appels à des services externes.

Tout module de ce dossier exposant une variable `router` (un
`fastapi.APIRouter`) est automatiquement inclus par app/main.py : pas besoin
de toucher au fichier généré pour ajouter vos propres routes.
"""

from __future__ import annotations

import re

from fastapi import APIRouter, Depends, HTTPException
from sqlmodel import Session

from ..database import get_session

router = APIRouter(prefix="/custom", tags=["custom"])


@router.get("/ping")
def ping():
    """Vérifie que ce routeur custom est bien chargé."""
    return {"status": "custom router actif"}


# ---------------------------------------------------------------------------
# Exemple : validation par expression régulière avant écriture en base.
# Le DSL sait déjà générer une contrainte de ce type sur un champ simple
# (`champ email: chaine motif = "^[^@]+@[^@]+$"` -> voir models.py), mais
# toute logique plus riche (règles croisant plusieurs champs, dépendant de
# données en base, etc.) se code ici en Python normal.
# ---------------------------------------------------------------------------
_EMAIL_RE = re.compile(r"^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$")


@router.post("/exemple-validation")
def exemple_validation(email: str, session: Session = Depends(get_session)):
    if not _EMAIL_RE.match(email):
        raise HTTPException(status_code=422, detail="Email invalide")
    # Écriture en base directe via la Session SQLModel, exactement comme
    # dans les routeurs générés (voir app/routers/<entite>.py) :
    #   from ..models import MonEntite
    #   item = MonEntite(...)
    #   session.add(item); session.commit(); session.refresh(item)
    return {"email": email, "valide": True}


@router.get("/exemple-requete-complexe")
def exemple_requete_complexe(session: Session = Depends(get_session)):
    """Point de départ pour une requête au-delà du CRUD simple (jointure,
    agrégation SQL...). Remplacez ce corps par votre propre logique, en
    important vos modèles depuis `..models`."""
    return {"exemple": "adaptez cette fonction à vos propres modèles"}
'''


def generate_backend_scaffold() -> dict[str, str]:
    """Fichiers d'extension "custom" : créés une seule fois si absents,
    jamais réécrits par une compilation suivante (contrairement à
    `generate_backend`, dont le contenu est toujours régénéré)."""
    return {
        "backend/app/routers_custom/__init__.py": "",
        "backend/app/routers_custom/example.py": _CUSTOM_ROUTER_EXAMPLE,
    }
