"""Générateur Docker : Dockerfiles + docker-compose pour le projet généré."""

from __future__ import annotations

from ..ast_nodes import NovaProgram
from .utils import to_ascii_identifier, to_snake_case

_BACKEND_DOCKERFILE = """\
# Généré par NOVA / Generated by NOVA
FROM python:3.11-slim

WORKDIR /app

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/app ./app

EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
"""

_FRONTEND_DOCKERFILE_TMPL = """\
# Généré par NOVA / Generated by NOVA
FROM python:3.11-slim

WORKDIR /app

# Reflex télécharge et installe son propre runtime JS (Bun) au premier
# démarrage : il a besoin de `unzip` (extraction de l'archive téléchargée)
# et de `curl`/`ca-certificates` (téléchargement en HTTPS), absents de
# l'image python slim de base.
RUN apt-get update \\
    && apt-get install -y --no-install-recommends unzip curl ca-certificates \\
    && rm -rf /var/lib/apt/lists/*

COPY frontend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY frontend/ .

EXPOSE 3000 8001
# Mode "dev" volontairement conservé ici (et pas "--env prod") : Reflex
# exige que frontend et backend partagent le même port en mode prod, ce qui
# est incompatible avec des ports distincts 3000/8001. Pour un vrai
# déploiement de production, il faudrait construire un export statique
# (`reflex export`) servi derrière un reverse proxy unique (voir chart Helm).
CMD ["reflex", "run", "--env", "dev", "--backend-port", "8001", "--frontend-port", "3000"]
"""


def _compose(program: NovaProgram) -> str:
    app_name = to_snake_case(to_ascii_identifier(program.app.name)) if program.app else "nova_app"
    return f"""\
# Généré par NOVA / Generated by NOVA
# Démarrage local : docker compose up --build
name: {app_name}

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      NOVA_DATABASE_URL: sqlite:///./nova.db
    volumes:
      - backend_data:/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
      - "8001:8001"
    environment:
      NOVA_BACKEND_URL: http://backend:8000
    depends_on:
      - backend

volumes:
  backend_data:
"""


def generate_docker(program: NovaProgram) -> dict[str, str]:
    return {
        "Dockerfile.backend": _BACKEND_DOCKERFILE,
        "Dockerfile.frontend": _FRONTEND_DOCKERFILE_TMPL,
        "docker-compose.yml": _compose(program),
        ".dockerignore": "**/__pycache__\n**/*.pyc\n.venv\nnode_modules\n.web\n*.db\n",
    }
