"""Générateur Docker : Dockerfiles + docker-compose pour le projet généré."""

from __future__ import annotations

from .. import keywords as kw
from ..ast_nodes import NovaProgram
from .utils import to_ascii_identifier, to_snake_case

# Image officielle + variables d'environnement + volume de données par
# moteur (tâche #28, voir `application { database: ... }`) : un service
# `db:` est ajouté au docker-compose généré pour tout moteur autre que
# sqlite (qui n'a besoin d'aucun serveur séparé — fichier local persisté
# via le volume `backend_data` existant, inchangé). Identifiants de
# développement en clair, cohérents avec `keywords.DB_DEFAULT_URLS` (même
# hôte "db", mêmes identifiants) : à surcharger en production comme le
# reste (NOVA_JWT_SECRET, NOVA_SMTP_PASSWORD...).
_DB_SERVICES = {
    "postgresql": """\
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: nova
      POSTGRES_PASSWORD: nova
      POSTGRES_DB: nova
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
""",
    "mysql": """\
  db:
    image: mysql:8
    environment:
      MYSQL_USER: nova
      MYSQL_PASSWORD: nova
      MYSQL_ROOT_PASSWORD: nova
      MYSQL_DATABASE: nova
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
""",
    "sqlserver": """\
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "NovaDev123!"
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql
""",
    "oracle": """\
  db:
    image: gvenzl/oracle-free:23-slim
    environment:
      ORACLE_PASSWORD: nova
    ports:
      - "1521:1521"
    volumes:
      - db_data:/opt/oracle/oradata
""",
    "mongodb": """\
  db:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: nova
      MONGO_INITDB_ROOT_PASSWORD: nova
      MONGO_INITDB_DATABASE: nova
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
""",
}

_BACKEND_DOCKERFILE = """\
# Généré par NOVA / Generated by NOVA
FROM python:3.11-slim

WORKDIR /app

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/app ./app

EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
"""

_FRONTEND_DOCKERFILE_TMPL = """\
# Généré par NOVA / Generated by NOVA
FROM python:3.11-slim

WORKDIR /app

# Reflex télécharge et installe son propre runtime JS (Bun) au premier
# démarrage : il a besoin de `unzip` (extraction de l'archive téléchargée)
# et de `curl`/`ca-certificates` (téléchargement en HTTPS), absents de
# l'image python slim de base.
RUN apt-get update \\
    && apt-get install -y --no-install-recommends unzip curl ca-certificates \\
    && rm -rf /var/lib/apt/lists/*

COPY frontend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY frontend/ .

EXPOSE 3000 8001
# Mode "dev" volontairement conservé ici (et pas "--env prod") : Reflex
# exige que frontend et backend partagent le même port en mode prod, ce qui
# est incompatible avec des ports distincts 3000/8001. Pour un vrai
# déploiement de production, il faudrait construire un export statique
# (`reflex export`) servi derrière un reverse proxy unique (voir chart Helm).
CMD ["reflex", "run", "--env", "dev", "--backend-port", "8001", "--frontend-port", "3000"]
"""


def _compose(program: NovaProgram) -> str:
    app_name = to_snake_case(to_ascii_identifier(program.app.name)) if program.app else "nova_app"
    has_auth = program.auth is not None and program.auth.enabled
    has_uploads = any(f.type in ("file", "image") for e in program.entities for f in e.fields)
    has_email = program.email is not None
    # `application { database: postgresql }` (tâche #28) : moteur autre que
    # sqlite -> service `db:` dédié + NOVA_DATABASE_URL pointant dessus +
    # backend qui en dépend. Sqlite (défaut) reste inchangé : fichier local
    # persisté via `backend_data` (volume déjà utilisé aussi par les
    # uploads, voir docstring de codegen/k8s.py), aucun service `db:`.
    db_engine = program.database_engine()
    db_url = kw.DB_DEFAULT_URLS.get(db_engine, kw.DB_DEFAULT_URLS["sqlite"])
    db_service_block = f"\n{_DB_SERVICES[db_engine]}" if db_engine in _DB_SERVICES else ""
    backend_depends_on = "\n    depends_on:\n      - db" if db_engine in _DB_SERVICES else ""
    db_volume_decl = "\n  db_data:" if db_engine in _DB_SERVICES else ""
    jwt_line = (
        "\n      # Bloc `auth { ... }` détecté : à surcharger avec une vraie valeur\n"
        "      # secrète en production (`openssl rand -hex 32`, par exemple).\n"
        "      NOVA_JWT_SECRET: nova-dev-secret-change-me"
        if has_auth
        else ""
    )
    public_backend_url_line = (
        "\n      # Champ `file`/`image` détecté : URL du backend joignable"
        "\n      # DEPUIS LE NAVIGATEUR (aperçus/téléchargements), distincte de"
        "\n      # NOVA_BACKEND_URL ci-dessus (appels serveur-à-serveur, nom"
        "\n      # Docker interne \"backend\" non résolvable par le navigateur)."
        "\n      # À surcharger avec le vrai domaine public en production."
        "\n      NOVA_PUBLIC_BACKEND_URL: http://localhost:8000"
        if has_uploads
        else ""
    )
    smtp_password_line = (
        "\n      # Bloc `email { ... }` détecté : le mot de passe SMTP n'est"
        "\n      # JAMAIS écrit dans le fichier .nova (voir backend/app/emailer.py)"
        "\n      # — à fournir ici (ou via un vrai secret Docker/K8s en production)."
        "\n      NOVA_SMTP_PASSWORD: \"\""
        if has_email
        else ""
    )
    return f"""\
# Généré par NOVA / Generated by NOVA
# Démarrage local : docker compose up --build
name: {app_name}

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      NOVA_DATABASE_URL: {db_url}{jwt_line}{smtp_password_line}
    volumes:
      - backend_data:/app{backend_depends_on}

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
      - "8001:8001"
    environment:
      NOVA_BACKEND_URL: http://backend:8000{public_backend_url_line}
    depends_on:
      - backend
{db_service_block}
volumes:
  backend_data:{db_volume_decl}
"""


def generate_docker(program: NovaProgram) -> dict[str, str]:
    return {
        "Dockerfile.backend": _BACKEND_DOCKERFILE,
        "Dockerfile.frontend": _FRONTEND_DOCKERFILE_TMPL,
        "docker-compose.yml": _compose(program),
        ".dockerignore": "**/__pycache__\n**/*.pyc\n.venv\nnode_modules\n.web\n*.db\n",
    }
