"""
Générateur de frontend : AST NOVA -> application Reflex (Python -> React).

Un bloc `page` devient une page Reflex : `afficher/show <Entity> comme/as
table|form|card` choisit le composant généré. Les données sont chargées
depuis le backend FastAPI via httpx.

Le rendu s'appuie sur le thème Radix intégré à Reflex (`rx.theme`) pour un
look moderne par défaut (arrondis, espacements, palette cohérente) sans
CSS personnalisé à écrire : une barre de navigation partagée entre toutes
les pages, un conteneur centré, des cartes (`rx.card`) pour les
tableaux/formulaires/fiches, et des boutons de navigation entre les pages
liées à une même entité (ex. lien "+ Nouveau" depuis un tableau vers son
formulaire de création).

Deux points d'extension supplémentaires restent "hyper simples" tout en
gardant la porte ouverte à du CSS/design sur mesure :
- `application { css: "chemin/vers/fichier.css" }` charge une feuille de
  style externe (copiée dans `frontend/assets/`, référencée via
  `rx.App(stylesheets=[...])`).
- `show ... style { propriete: "valeur" }` ajoute des styles inline (alias
  bilingues courants dans `keywords.STYLE_ALIASES`, ou n'importe quelle
  propriété CSS passée telle quelle) et/ou une classe CSS (`classe`/`class`)
  sur le composant généré, pour venir piocher dans la feuille de style
  externe.

Si le bloc `auth { ... }` est présent, une page de connexion et un état
d'authentification partagé (`AuthState`, jeton JWT persisté en cookie) sont
générés, et chaque page liée à une entité protégée (`api Xxx { ...
proteger: <role> }`) envoie le jeton en en-tête `Authorization`.
"""

from __future__ import annotations

import textwrap

from ..ast_nodes import Chart, NovaProgram, Page
from ..keywords import STYLE_ALIASES, STYLE_CLASS_KEYS
from .utils import to_ascii_identifier, to_pascal_case, to_snake_case, pluralize

_HEADER = (
    "# " + "-" * 76 + "\n"
    "# Fichier généré automatiquement par le compilateur NOVA. Ne pas éditer\n"
    "# à la main : régénérez à partir du fichier .nova source (`nova compile`).\n"
    "# Auto-generated by the NOVA compiler. Do not edit by hand: regenerate\n"
    "# from the source .nova file (`nova compile`).\n"
    "# " + "-" * 76 + "\n"
)


def _app_pkg_name(program: NovaProgram) -> str:
    if program.app:
        return to_snake_case(to_ascii_identifier(program.app.name)) or "nova_app"
    return "nova_app"


def _state_class_name(page: Page) -> str:
    return f"{to_pascal_case(page.name)}State"


def _page_route(page: Page) -> str:
    slug = to_snake_case(to_ascii_identifier(page.name)).replace("_", "-")
    return f"/{slug}" if slug else "/"


def _table_route_for_entity(program: NovaProgram, entity_name: str) -> str | None:
    """Première page en mode table affichant cette entité (cible de redirection
    après création, et lien "+ Nouveau" depuis le tableau)."""
    for p in program.pages:
        if p.shows and p.shows[0].entity == entity_name and p.shows[0].mode == "table":
            return _page_route(p)
    return None


def _form_page_for_entity(program: NovaProgram, entity_name: str) -> Page | None:
    for p in program.pages:
        if p.shows and p.shows[0].entity == entity_name and p.shows[0].mode == "form":
            return p
    return None


def _api_for_entity(program: NovaProgram, entity_name: str):
    return next((a for a in program.apis if a.entity == entity_name), None)


# --------------------------------------------------------------- chart ---

_CHART_COLOR = "#7c66dc"  # violet, cohérent avec le thème accent_color="violet"


def _chart_state_class_name(chart: Chart) -> str:
    return f"{to_pascal_case(chart.name)}ChartState"


def _chart_route(chart: Chart) -> str:
    slug = to_snake_case(to_ascii_identifier(chart.name)).replace("_", "-")
    return f"/graphiques/{slug}" if slug else "/graphiques"


def _chart_data_source(program: NovaProgram, chart: Chart, has_auth: bool) -> tuple[str, bool]:
    """Résout `chart ... sur <source>` en (chemin_url_backend, protege) :
    - une Entity -> son API liste (`/<entites>/`), protection héritée du
      bloc `api <Entity> { proteger: <role> }` s'il existe ;
    - une Query (`requete`/`query`) -> sa route dédiée (`/requetes/<slug>`),
      jamais protégée aujourd'hui (voir codegen/api_fastapi._generate_query_router,
      qui ne pose pas Depends(get_current_user)).
    `parser._validate_charts` garantit déjà que `chart.source` correspond à
    l'une des deux, donc le cas "aucune des deux" ne devrait jamais survenir
    ici — gardé par simple prudence plutôt que de lever une exception au
    milieu de la génération."""
    entity = program.get_entity(chart.source)
    if entity is not None:
        url_path = to_snake_case(pluralize(to_ascii_identifier(chart.source))) + "/"
        api = _api_for_entity(program, chart.source)
        is_protected = bool(has_auth and api and api.protected_role)
        return url_path, is_protected
    query = program.get_query(chart.source)
    if query is not None:
        slug = to_snake_case(query.name).replace("_", "-")
        return f"requetes/{slug}", False
    return to_snake_case(to_ascii_identifier(chart.source)) + "/", False


def _generate_chart_state_and_view(chart: Chart, program: NovaProgram, has_auth: bool) -> tuple[str, str]:
    """Retourne (code_du_state, code_de_la_fonction_de_page) pour un bloc
    `chart`, sur le même modèle que `_generate_state_and_view` ci-dessus :
    un état Reflex qui charge les lignes de données au montage de la page,
    et une fonction de page qui les affiche via `rx.recharts` (aucune
    dépendance Python supplémentaire : recharts est fourni avec Reflex)."""
    state_cls = _chart_state_class_name(chart)
    url_path, is_protected = _chart_data_source(program, chart, has_auth)

    auth_header_lines = []
    if is_protected:
        auth_header_lines = [
            "        auth_state = await self.get_state(AuthState)",
            '        headers = {"Authorization": f"Bearer {auth_state.token}"} if auth_state.token else {}',
        ]
    headers_kwarg = ", headers=headers" if is_protected else ""

    state_lines = [
        f"class {state_cls}(rx.State):",
        f'    """État Reflex pour le graphique `{chart.name}` (source : {chart.source}).'
        + (' Route protégée : le jeton AuthState est envoyé en en-tête Authorization."""' if is_protected else '"""'),
        "    rows: list[dict] = []",
        "    is_loading: bool = False",
        "",
        "    async def load_rows(self):",
        "        self.is_loading = True",
    ]
    state_lines += auth_header_lines
    state_lines += [
        "        async with httpx.AsyncClient() as client:",
        f'            resp = await client.get(f"{{BACKEND_URL}}/{url_path}"{headers_kwarg})',
        "            if resp.status_code == 200:",
        "                self.rows = resp.json()",
        "        self.is_loading = False",
        "",
    ]
    state_code = "\n".join(state_lines) + "\n"

    title = chart.title or chart.name
    x_key = chart.x_field or "x"
    y_key = chart.y_field or "y"

    if chart.type == "pie":
        # La donnée du camembert se pose sur le sous-composant `pie`, pas sur
        # `pie_chart` lui-même — contrairement à bar/line/area (vérifié par
        # exécution réelle avant d'écrire ce générateur).
        chart_component = (
            "rx.recharts.pie_chart(\n"
            f'    rx.recharts.pie(data={state_cls}.rows, data_key="{y_key}", name_key="{x_key}", '
            f'fill="{_CHART_COLOR}"),\n'
            "    rx.recharts.graphing_tooltip(),\n"
            "    rx.recharts.legend(),\n"
            '    width="100%",\n'
            "    height=360,\n"
            ")"
        )
    else:
        chart_fn = {"bar": "bar_chart", "line": "line_chart", "area": "area_chart"}[chart.type]
        series_fn = {"bar": "bar", "line": "line", "area": "area"}[chart.type]
        if chart.type == "line":
            series_kwargs = f'data_key="{y_key}", stroke="{_CHART_COLOR}"'
        elif chart.type == "area":
            series_kwargs = f'data_key="{y_key}", fill="{_CHART_COLOR}", stroke="{_CHART_COLOR}"'
        else:  # bar
            series_kwargs = f'data_key="{y_key}", fill="{_CHART_COLOR}"'
        chart_component = (
            f"rx.recharts.{chart_fn}(\n"
            f"    rx.recharts.{series_fn}({series_kwargs}),\n"
            f'    rx.recharts.x_axis(data_key="{x_key}"),\n'
            "    rx.recharts.y_axis(),\n"
            "    rx.recharts.graphing_tooltip(),\n"
            f"    data={state_cls}.rows,\n"
            '    width="100%",\n'
            "    height=360,\n"
            ")"
        )

    inner = (
        "rx.card(\n"
        "    rx.vstack(\n"
        f'        rx.heading("{title}", size="7"),\n'
        f"{textwrap.indent(chart_component, '        ')},\n"
        '        spacing="4",\n'
        '        width="100%",\n'
        "    ),\n"
        '    padding="2em",\n'
        '    width="100%",\n'
        ")"
    )
    view_code = (
        f"def {to_snake_case(chart.name)}_chart_page() -> rx.Component:\n"
        + _wrap_page_body(inner, f"{state_cls}.load_rows", "900px")
    )
    return state_code, view_code


# ---------------------------------------------------------------- style ---

def _snake_to_camel(name: str) -> str:
    parts = name.replace("-", "_").split("_")
    return parts[0] + "".join(p[:1].upper() + p[1:] for p in parts[1:] if p)


def _style_kwargs_src(style: dict[str, str]) -> str:
    """Kwargs Reflex supplémentaires (`, class_name="...", style={...}`) pour
    un bloc `style { ... }` du DSL — chaîne vide si aucun style déclaré.
    Les clés connues de `keywords.STYLE_ALIASES` (ex. `couleur_fond`) sont
    traduites vers la propriété CSS réelle ; toute autre clé est passée
    telle quelle (snake_case ou kebab-case), convertie en camelCase pour
    Reflex — la "porte de sortie" qui garde ce bloc aussi souple que du CSS
    brut."""
    if not style:
        return ""
    class_name = None
    css_props: dict[str, str] = {}
    for key, value in style.items():
        if key in STYLE_CLASS_KEYS:
            class_name = value
            continue
        css_key = STYLE_ALIASES.get(key, key.replace("_", "-"))
        camel_key = _snake_to_camel(css_key.replace("-", "_"))
        css_props[camel_key] = value
    parts = []
    if class_name:
        parts.append(f'class_name="{class_name}"')
    if css_props:
        style_dict_src = ", ".join(f'"{k}": "{v}"' for k, v in css_props.items())
        parts.append(f"style={{{style_dict_src}}}")
    return (", " + ", ".join(parts)) if parts else ""


# ----------------------------------------------------------------- auth ---

_AUTH_STATE_TEMPLATE = '''\
class AuthState(rx.State):
    """État d'authentification partagé (voir bloc `auth {{ ... }}` du fichier
    .nova) — le jeton JWT est persisté dans un cookie navigateur, valable
    entre deux rechargements de page."""

    token: str = rx.Cookie("", name="nova_token")
    email: str = ""
    password: str = ""
    error_message: str = ""

    def set_email(self, value: str) -> None:
        self.email = value

    def set_password(self, value: str) -> None:
        self.password = value

    async def login(self):
        self.error_message = ""
        async with httpx.AsyncClient() as client:
            resp = await client.post(
                f"{{BACKEND_URL}}/auth/login",
                data={{"username": self.email, "password": self.password}},
            )
            if resp.status_code == 200:
                self.token = resp.json()["access_token"]
                self.password = ""
                return rx.redirect("{home_route}")
            self.error_message = "Identifiants invalides / Invalid credentials"

    def logout(self):
        self.token = ""
        return rx.redirect("{login_route}")
'''


def _generate_auth_state(program: NovaProgram) -> str:
    home_route = _page_route(program.pages[0]) if program.pages else "/"
    return _AUTH_STATE_TEMPLATE.format(home_route=home_route, login_route="/connexion")


def _generate_login_page() -> str:
    inner = (
        "rx.card(\n"
        "    rx.vstack(\n"
        '        rx.heading("Connexion / Login", size="7"),\n'
        '        rx.cond(\n'
        '            AuthState.error_message != "",\n'
        '            rx.text(AuthState.error_message, color="red", size="2"),\n'
        "        ),\n"
        "        rx.vstack(\n"
        '            rx.text("Email", size="2", weight="bold", color_scheme="gray"),\n'
        '            rx.input(placeholder="email@exemple.com", value=AuthState.email, '
        'on_change=AuthState.set_email, size="3", width="100%"),\n'
        '            spacing="1",\n'
        '            width="100%",\n'
        "        ),\n"
        "        rx.vstack(\n"
        '            rx.text("Mot de passe / Password", size="2", weight="bold", color_scheme="gray"),\n'
        '            rx.input(placeholder="********", value=AuthState.password, '
        'on_change=AuthState.set_password, type="password", size="3", width="100%"),\n'
        '            spacing="1",\n'
        '            width="100%",\n'
        "        ),\n"
        '        rx.button("Se connecter / Log in", on_click=AuthState.login, size="3", '
        'width="100%", color_scheme="violet"),\n'
        '        spacing="4",\n'
        '        width="100%",\n'
        "    ),\n"
        '    padding="2em",\n'
        '    width="100%",\n'
        ")"
    )
    return "def connexion_page() -> rx.Component:\n" + _wrap_page_body(inner, "None", "420px")


def _generate_navbar(program: NovaProgram, has_auth: bool) -> str:
    app_title = program.app.name if program.app else "NOVA App"
    links = "\n".join(
        f'        rx.link("{p.name}", href="{_page_route(p)}", size="3", weight="medium", '
        f'color_scheme="gray", high_contrast=True),'
        for p in program.pages
    )
    chart_links = "\n".join(
        f'        rx.link("{c.name}", href="{_chart_route(c)}", size="3", weight="medium", '
        f'color_scheme="gray", high_contrast=True),'
        for c in program.charts
    )
    if chart_links:
        links = f"{links}\n{chart_links}" if links else chart_links
    auth_links = ""
    if has_auth:
        auth_links = (
            "        rx.cond(\n"
            "            AuthState.token != \"\",\n"
            '            rx.button("Déconnexion / Log out", on_click=AuthState.logout, size="2", variant="soft"),\n'
            '            rx.link(rx.button("Connexion / Log in", size="2"), href="/connexion"),\n'
            "        ),\n"
        )
    return (
        "def nova_navbar() -> rx.Component:\n"
        '    """Barre de navigation partagée entre toutes les pages générées."""\n'
        "    return rx.hstack(\n"
        f'        rx.heading("{app_title}", size="5", weight="bold"),\n'
        "        rx.spacer(),\n"
        f"{links}\n"
        f"{auth_links}"
        "        align=\"center\",\n"
        "        width=\"100%\",\n"
        "        padding=\"1em 2em\",\n"
        "        border_bottom=\"1px solid var(--gray-5)\",\n"
        "        background=\"var(--color-panel-solid)\",\n"
        "        position=\"sticky\",\n"
        "        top=\"0\",\n"
        "        z_index=\"10\",\n"
        "    )\n"
    )


def _wrap_page_body(inner_component_src: str, on_mount_expr: str, container_max_width: str) -> str:
    """Enveloppe le contenu propre à une page (`inner_component_src`, une
    expression Reflex sans le mot-clé `return`) dans le "shell" commun à
    toutes les pages : barre de navigation, conteneur centré, fond pleine
    page. Cette fonction gère l'indentation pour que le fichier généré
    reste lisible ; Python n'exige pas d'indentation précise à l'intérieur
    d'une liste d'arguments entre parenthèses, donc une légère imprécision
    ne casserait rien, mais on la soigne pour un fichier généré agréable à
    relire."""
    indented_inner = textwrap.indent(inner_component_src.rstrip("\n"), "            ")
    return (
        "    return rx.box(\n"
        "        nova_navbar(),\n"
        "        rx.container(\n"
        f"{indented_inner},\n"
        f'            max_width="{container_max_width}",\n'
        '            padding="2em",\n'
        '            width="100%",\n'
        "        ),\n"
        f"        on_mount={on_mount_expr},\n"
        '        width="100%",\n'
        '        min_height="100vh",\n'
        '        background="var(--gray-2)",\n'
        "    )\n"
    )


def _generate_state_and_view(page: Page, program: NovaProgram, has_auth: bool) -> tuple[str, str]:
    """Retourne (code_du_state, code_de_la_fonction_de_page) pour un bloc page."""
    if not page.shows:
        state_cls = _state_class_name(page)
        state_code = f"class {state_cls}(rx.State):\n    pass\n"
        view_code = (
            f"def {to_snake_case(page.name)}_page() -> rx.Component:\n"
            + _wrap_page_body(f'rx.heading("{page.name}", size="7")', "None", "800px")
        )
        return state_code, view_code

    show = page.shows[0]  # MVP : une entité principale par page
    entity = program.get_entity(show.entity)
    state_cls = _state_class_name(page)
    table_url_path = to_snake_case(pluralize(to_ascii_identifier(show.entity)))
    title = show.title or page.name
    fields = entity.fields if entity else []
    api = _api_for_entity(program, show.entity)
    is_protected = bool(has_auth and api and api.protected_role)

    state_lines = [
        f"class {state_cls}(rx.State):",
        f'    """État Reflex pour la page `{page.name}` (affiche {show.entity} en mode {show.mode}).'
        + (' Route protégée : le jeton AuthState est envoyé en en-tête Authorization."""' if is_protected else '"""'),
        "    rows: list[dict] = []",
        "    is_loading: bool = False",
    ]
    for f in fields:
        state_lines.append(f'    new_{to_snake_case(f.name)}: str = ""')

    if show.mode == "form":
        # Setters explicites : ne pas compter sur les setters `set_<var>`
        # auto-générés par Reflex, dont la disponibilité/le nom exact a varié
        # selon les versions de Reflex (observé en pratique : AttributeError
        # "has no attribute 'set_new_xxx'" avec certaines versions récentes).
        # Un setter écrit explicitement fonctionne quelle que soit la version.
        for f in fields:
            snake = to_snake_case(f.name)
            state_lines.append(f"    def set_new_{snake}(self, value: str) -> None:")
            state_lines.append(f"        self.new_{snake} = value")

    auth_header_lines = []
    if is_protected:
        auth_header_lines = [
            "        auth_state = await self.get_state(AuthState)",
            '        headers = {"Authorization": f"Bearer {auth_state.token}"} if auth_state.token else {}',
        ]
    headers_kwarg = ", headers=headers" if is_protected else ""

    state_lines += [
        "",
        "    async def load_rows(self):",
        "        self.is_loading = True",
    ]
    state_lines += auth_header_lines
    state_lines += [
        "        async with httpx.AsyncClient() as client:",
        f'            resp = await client.get(f"{{BACKEND_URL}}/{table_url_path}/"{headers_kwarg})',
        "            if resp.status_code == 200:",
        "                self.rows = resp.json()",
        "        self.is_loading = False",
        "",
    ]
    if show.mode == "form":
        payload_items = ", ".join(f'"{to_snake_case(f.name)}": self.new_{to_snake_case(f.name)}' for f in fields)
        redirect_route = _table_route_for_entity(program, show.entity)
        state_lines += ["    async def submit(self):"]
        state_lines += auth_header_lines
        state_lines += [
            "        async with httpx.AsyncClient() as client:",
            f'            await client.post(f"{{BACKEND_URL}}/{table_url_path}/", json={{{payload_items}}}{headers_kwarg})',
        ]
        for f in fields:
            state_lines.append(f'        self.new_{to_snake_case(f.name)} = ""')
        if redirect_route:
            # On revient sur le tableau qui liste cette entité une fois
            # l'enregistrement créé, plutôt que de rester sur le formulaire.
            state_lines.append(f'        return rx.redirect("{redirect_route}")')
        else:
            state_lines.append("        await self.load_rows()")
        state_lines.append("")
    state_code = "\n".join(state_lines) + "\n"

    style_kwargs = _style_kwargs_src(show.style)

    # ---- vue -------------------------------------------------------------
    if show.mode == "table":
        header_cells = ", ".join(f'rx.table.column_header_cell("{f.name}")' for f in fields)
        row_cells = ", ".join(f'rx.table.cell(row["{to_snake_case(f.name)}"])' for f in fields)
        create_page = _form_page_for_entity(program, show.entity)
        create_link = (
            f'rx.link(rx.button("+ {create_page.name}", size="2"), href="{_page_route(create_page)}"),'
            if create_page
            else ""
        )
        inner = (
            "rx.vstack(\n"
            "    rx.hstack(\n"
            f'        rx.heading("{title}", size="7"),\n'
            "        rx.spacer(),\n"
            f"        {create_link}\n"
            '        width="100%",\n'
            '        align="center",\n'
            "    ),\n"
            "    rx.card(\n"
            "        rx.table.root(\n"
            "            rx.table.header(\n"
            f"                rx.table.row({header_cells}),\n"
            "            ),\n"
            "            rx.table.body(\n"
            f"                rx.foreach({state_cls}.rows, lambda row: rx.table.row({row_cells})),\n"
            "            ),\n"
            '            variant="surface",\n'
            '            width="100%",\n'
            "        ),\n"
            f'        width="100%"{style_kwargs},\n'
            "    ),\n"
            '    spacing="4",\n'
            '    width="100%",\n'
            ")"
        )
        container_width = "1100px"
    elif show.mode == "form":
        field_blocks = []
        for f in fields:
            snake = to_snake_case(f.name)
            field_blocks.append(
                "    rx.vstack(\n"
                f'        rx.text("{f.name}", size="2", weight="bold", color_scheme="gray"),\n'
                f'        rx.input(placeholder="{f.name}", value={state_cls}.new_{snake}, '
                f"on_change={state_cls}.set_new_{snake}, size=\"3\", width=\"100%\"),\n"
                '        spacing="1",\n'
                '        width="100%",\n'
                "    ),"
            )
        fields_src = "\n".join(field_blocks)
        inner = (
            "rx.card(\n"
            "    rx.vstack(\n"
            f'        rx.heading("{title}", size="7"),\n'
            f"{fields_src}\n"
            f'        rx.button("Enregistrer / Save", on_click={state_cls}.submit, size="3", '
            'width="100%", color_scheme="violet"),\n'
            '        spacing="4",\n'
            '        width="100%",\n'
            "    ),\n"
            f'    padding="2em",\n'
            f'    width="100%"{style_kwargs},\n'
            ")"
        )
        container_width = "560px"
    else:  # card
        card_rows = ", ".join(
            f'rx.text(f"{f.name}: {{row[\'{to_snake_case(f.name)}\']}}")' for f in fields
        )
        inner = (
            "rx.vstack(\n"
            f'    rx.heading("{title}", size="7"),\n'
            "    rx.grid(\n"
            f"        rx.foreach({state_cls}.rows, lambda row: rx.card(\n"
            f"            rx.vstack({card_rows}, spacing=\"2\"),\n"
            '            padding="1.5em",\n'
            "        )),\n"
            '        columns="3",\n'
            '        spacing="4",\n'
            '        width="100%",\n'
            "    ),\n"
            '    spacing="4",\n'
            f'    width="100%"{style_kwargs},\n'
            ")"
        )
        container_width = "1100px"

    view_code = (
        f"def {to_snake_case(page.name)}_page() -> rx.Component:\n"
        + _wrap_page_body(inner, f"{state_cls}.load_rows", container_width)
    )
    return state_code, view_code


def generate_frontend(program: NovaProgram) -> dict[str, str]:
    pkg = _app_pkg_name(program)
    app_title = program.app.name if program.app else "NOVA App"
    has_auth = program.auth is not None and program.auth.enabled
    css_path = program.app.props.get("css") if program.app else None
    css_basename = css_path.rsplit("/", 1)[-1].rsplit("\\", 1)[-1] if css_path else None

    lines = [
        _HEADER,
        "from __future__ import annotations",
        "",
        "import os",
        "",
        "import httpx",
        "import reflex as rx",
        "",
        'BACKEND_URL = os.environ.get("NOVA_BACKEND_URL", "http://localhost:8000")',
        "",
        "",
    ]

    if program.pages or program.charts or has_auth:
        lines.append(_generate_navbar(program, has_auth))
        lines.append("")

    if has_auth:
        lines.append(_generate_auth_state(program))
        lines.append("")
        lines.append(_generate_login_page())
        lines.append("")

    page_fns = []
    for page in program.pages:
        state_code, view_code = _generate_state_and_view(page, program, has_auth)
        lines.append(state_code)
        lines.append("")
        lines.append(view_code)
        lines.append("")
        page_fns.append((to_snake_case(page.name) + "_page", _page_route(page), page.name))

    for chart in program.charts:
        state_code, view_code = _generate_chart_state_and_view(chart, program, has_auth)
        lines.append(state_code)
        lines.append("")
        lines.append(view_code)
        lines.append("")
        page_fns.append((to_snake_case(chart.name) + "_chart_page", _chart_route(chart), chart.title or chart.name))

    theme_kwargs = 'appearance="light", accent_color="violet", radius="large", scaling="100%"'
    app_kwargs = f"theme=rx.theme({theme_kwargs})"
    if css_basename:
        app_kwargs += f', stylesheets=["/{css_basename}"]'
    lines.append(f"app = rx.App({app_kwargs})")
    for fn_name, route, title in page_fns:
        lines.append(f'app.add_page({fn_name}, route="{route}", title="{title}")')
    if has_auth:
        lines.append('app.add_page(connexion_page, route="/connexion", title="Connexion")')
    if not page_fns and not has_auth:
        lines.append("")
        lines.append('@rx.page(route="/")')
        lines.append("def index() -> rx.Component:")
        lines.append(f'    return rx.center(rx.heading("{app_title}"))')

    lines += [
        "",
        "# Pages/composants hors DSL (validation avancée, UI sur mesure...) :",
        "# custom.py n'est jamais régénéré par `nova compile` (créé une seule",
        "# fois s'il n'existe pas déjà) — voir sa fonction register(app).",
        "try:",
        "    from . import custom as _custom",
        "except ImportError:",
        "    _custom = None",
        'if _custom is not None and hasattr(_custom, "register"):',
        "    _custom.register(app)",
    ]

    main_code = "\n".join(lines) + "\n"

    rxconfig = (
        _HEADER
        + "import reflex as rx\n\n"
        + f'config = rx.Config(\n    app_name="{pkg}",\n)\n'
    )

    files = {
        f"frontend/{pkg}/{pkg}.py": main_code,
        f"frontend/{pkg}/__init__.py": "",
        "frontend/rxconfig.py": rxconfig,
        "frontend/requirements.txt": "reflex>=0.5\nhttpx>=0.27\n",
    }
    if css_basename:
        # Feuille de style externe (`application { css: "..." }`) : le
        # *contenu réel* du fichier référencé est copié ici par
        # `codegen.generate_project` (qui connaît le dossier source du
        # .nova) — on réserve juste l'emplacement attendu par Reflex
        # (`assets/`, servi à la racine du site) avec un contenu par défaut
        # au cas où le fichier source ne serait pas trouvé.
        files[f"frontend/{pkg}/assets/{css_basename}"] = (
            "/* Remplacé par le contenu de la feuille de style référencée dans\n"
            f"   `application {{ css: \"{css_path}\" }}` si ce fichier a été trouvé au\n"
            "   moment de la compilation (voir nova_compiler.codegen.generate_project). */\n"
        )
    return files


_CUSTOM_FRONTEND_EXAMPLE = '''\
"""
Extensions frontend "custom" (frontend/<app>/custom.py).

Ce fichier n'est JAMAIS régénéré par `nova compile` : créé une seule fois,
puis laissé intact à chaque compilation suivante — contrairement au fichier
principal (<app>.py), entièrement régénéré à chaque fois.

C'est ici qu'ajouter tout ce que le DSL NOVA ne couvre pas encore : contrôles
de formulaire avancés (validation côté client), composants sur mesure,
pages hors du modèle table/formulaire/fiche, appels à des API tierces...

`register(app)` est appelé automatiquement par le fichier principal généré,
juste après la création de `app = rx.App(...)` : ajoutez-y vos propres
`app.add_page(...)`.
"""

from __future__ import annotations

import reflex as rx


def register(app: rx.App) -> None:
    """Point d'entrée appelé automatiquement au démarrage de l'application."""
    # Exemple : une page 100% custom, hors du DSL NOVA.
    #
    # def about_page() -> rx.Component:
    #     return rx.center(rx.heading("À propos"))
    #
    # app.add_page(about_page, route="/about", title="About")
    pass
'''


def generate_frontend_scaffold(program: NovaProgram) -> dict[str, str]:
    """Fichier d'extension "custom" : créé une seule fois si absent, jamais
    réécrit par une compilation suivante (contrairement à `generate_frontend`,
    dont le contenu est toujours régénéré)."""
    pkg = _app_pkg_name(program)
    return {f"frontend/{pkg}/custom.py": _CUSTOM_FRONTEND_EXAMPLE}
