"""
Générateur de frontend : AST NOVA -> application Reflex (Python -> React).

Un bloc `page` devient une page Reflex : `afficher/show <Entity> comme/as
table|form|card` choisit le composant généré. Les données sont chargées
depuis le backend FastAPI via httpx.

Le rendu s'appuie sur le thème Radix intégré à Reflex (`rx.theme`) pour un
look moderne par défaut (arrondis, espacements, palette cohérente) sans
CSS personnalisé à écrire : une barre de navigation partagée entre toutes
les pages, un conteneur centré, des cartes (`rx.card`) pour les
tableaux/formulaires/fiches, et des boutons de navigation entre les pages
liées à une même entité (ex. lien "+ Nouveau" depuis un tableau vers son
formulaire de création).

Deux points d'extension supplémentaires restent "hyper simples" tout en
gardant la porte ouverte à du CSS/design sur mesure :
- `application { css: "chemin/vers/fichier.css" }` charge une feuille de
  style externe (copiée dans `frontend/assets/`, référencée via
  `rx.App(stylesheets=[...])`).
- `show ... style { propriete: "valeur" }` ajoute des styles inline (alias
  bilingues courants dans `keywords.STYLE_ALIASES`, ou n'importe quelle
  propriété CSS passée telle quelle) et/ou une classe CSS (`classe`/`class`)
  sur le composant généré, pour venir piocher dans la feuille de style
  externe.

Si le bloc `auth { ... }` est présent, une page de connexion et un état
d'authentification partagé (`AuthState`, jeton JWT persisté en cookie) sont
générés, et chaque page liée à une entité protégée (`api Xxx { ...
proteger: <role> }`) envoie le jeton en en-tête `Authorization`.
"""

from __future__ import annotations

import textwrap

from ..ast_nodes import Calendar, Chart, NovaProgram, Page
from ..keywords import STYLE_ALIASES, STYLE_CLASS_KEYS
from .utils import to_ascii_identifier, to_pascal_case, to_snake_case, pluralize

_HEADER = (
    "# " + "-" * 76 + "\n"
    "# Fichier généré automatiquement par le compilateur NOVA. Ne pas éditer\n"
    "# à la main : régénérez à partir du fichier .nova source (`nova compile`).\n"
    "# Auto-generated by the NOVA compiler. Do not edit by hand: regenerate\n"
    "# from the source .nova file (`nova compile`).\n"
    "# " + "-" * 76 + "\n"
)


def _app_pkg_name(program: NovaProgram) -> str:
    if program.app:
        return to_snake_case(to_ascii_identifier(program.app.name)) or "nova_app"
    return "nova_app"


def _state_class_name(page: Page, show=None, index: int | None = None) -> str:
    # Une page avec un seul `show` garde le nom historique
    # `<NomPage>State` (compatibilité totale avec les projets/tests
    # existants). Une page multi-entités (plusieurs `show`, voir
    # _generate_state_and_view) qualifie chaque state par l'entité affichée
    # (`<NomPage><Entite>State`) pour que les N states d'une même page ne se
    # percutent jamais — SAUF si la même entité apparaît plusieurs fois sur
    # la même page (ex. `show Produit as table` PUIS `show Produit as
    # carte` sur une seule page) : dans ce cas `<NomPage><Entite>State`
    # collisionnerait entre les deux `show`, d'où `index` (1-based),
    # ajouté par `_generate_state_and_view` uniquement quand nécessaire
    # (`<NomPage><Entite><N>State`).
    if show is None:
        return f"{to_pascal_case(page.name)}State"
    base = f"{to_pascal_case(page.name)}{to_pascal_case(show.entity)}"
    if index is not None:
        base += str(index)
    return f"{base}State"


def _page_route(page: Page) -> str:
    slug = to_snake_case(to_ascii_identifier(page.name)).replace("_", "-")
    return f"/{slug}" if slug else "/"


def _table_route_for_entity(program: NovaProgram, entity_name: str) -> str | None:
    """Première page en mode table affichant cette entité (cible de redirection
    après création, et lien "+ Nouveau" depuis le tableau) — cherche parmi
    TOUS les `show` de la page (pas seulement le premier) : une page
    multi-entités (plusieurs `show`, voir _generate_state_and_view) peut
    très bien afficher la table concernée en second ou troisième `show`."""
    for p in program.pages:
        if any(s.entity == entity_name and s.mode == "table" for s in p.shows):
            return _page_route(p)
    return None


def _form_page_for_entity(program: NovaProgram, entity_name: str) -> Page | None:
    """Même logique que `_table_route_for_entity` ci-dessus, pour un `show
    ... comme formulaire` (cible du lien "+ Nouveau")."""
    for p in program.pages:
        if any(s.entity == entity_name and s.mode == "form" for s in p.shows):
            return p
    return None


def _api_for_entity(program: NovaProgram, entity_name: str):
    return next((a for a in program.apis if a.entity == entity_name), None)


def _has_many_text_fields(entity, program: NovaProgram) -> list[tuple[str, str]]:
    """Pour chaque relation `has_many` de `entity` (voir
    `parser._validate_relations`, qui garantit que la cible existe et porte
    un `belongs_to` réciproque), retourne (etiquette_affichee,
    cle_json_du_resume). La clé correspond exactement au champ résumé texte
    déjà calculé côté backend pour matérialiser la relation
    (`api_fastapi._has_many_relation_info` : `<table_enfant>_text`) — le
    frontend n'a donc besoin que de connaître cette clé, jamais la liste
    imbriquée elle-même (même choix que pour le calendrier, `events_text` :
    Reflex peine à typer un `rx.foreach` sur une valeur imbriquée dans un
    dict lui-même dans une liste d'un state var)."""
    out: list[tuple[str, str]] = []
    for rel in entity.relations:
        if rel.kind != "has_many":
            continue
        child = program.get_entity(rel.target)
        if child is None:
            continue
        child_table = to_snake_case(pluralize(to_ascii_identifier(child.name)))
        out.append((pluralize(rel.target), f"{child_table}_text"))
    return out


# --------------------------------------------------------------- chart ---

_CHART_COLOR = "#7c66dc"  # violet, cohérent avec le thème accent_color="violet"
# Palette utilisée pour les graphiques multi-séries (bar/line/area avec
# plusieurs champs sur `axe_y`, voir keywords.CHART_MULTI_SERIES_TYPES) :
# `_CHART_COLOR` reste toujours la première couleur, ce qui rend le rendu
# à une seule série (cas le plus courant) identique bit-à-bit à avant
# l'ajout du multi-séries. Cycle si plus de séries que de couleurs.
_CHART_PALETTE = [_CHART_COLOR, "#f5a623", "#50c878", "#e35d6a", "#4a90d9", "#f0c419"]


def _chart_state_class_name(chart: Chart) -> str:
    return f"{to_pascal_case(chart.name)}ChartState"


def _chart_route(chart: Chart) -> str:
    slug = to_snake_case(to_ascii_identifier(chart.name)).replace("_", "-")
    return f"/graphiques/{slug}" if slug else "/graphiques"


def _chart_data_source(program: NovaProgram, chart: Chart, has_auth: bool) -> tuple[str, bool]:
    """Résout `chart ... sur <source>` en (chemin_url_backend, protege) :
    - une Entity -> son API liste (`/<entites>/`), protection héritée du
      bloc `api <Entity> { proteger: <role> }` s'il existe ;
    - une Query (`requete`/`query`) -> sa route dédiée (`/requetes/<slug>`),
      jamais protégée aujourd'hui (voir codegen/api_fastapi._generate_query_router,
      qui ne pose pas Depends(get_current_user)).
    `parser._validate_charts` garantit déjà que `chart.source` correspond à
    l'une des deux, donc le cas "aucune des deux" ne devrait jamais survenir
    ici — gardé par simple prudence plutôt que de lever une exception au
    milieu de la génération."""
    entity = program.get_entity(chart.source)
    if entity is not None:
        url_path = to_snake_case(pluralize(to_ascii_identifier(chart.source))) + "/"
        api = _api_for_entity(program, chart.source)
        is_protected = bool(has_auth and api and api.protected_role)
        return url_path, is_protected
    query = program.get_query(chart.source)
    if query is not None:
        slug = to_snake_case(query.name).replace("_", "-")
        return f"requetes/{slug}", False
    return to_snake_case(to_ascii_identifier(chart.source)) + "/", False


def _generate_chart_state_and_view(chart: Chart, program: NovaProgram, has_auth: bool) -> tuple[str, str]:
    """Retourne (code_du_state, code_de_la_fonction_de_page) pour un bloc
    `chart`, sur le même modèle que `_generate_state_and_view` ci-dessus :
    un état Reflex qui charge les lignes de données au montage de la page,
    et une fonction de page qui les affiche via `rx.recharts` (aucune
    dépendance Python supplémentaire : recharts est fourni avec Reflex)."""
    state_cls = _chart_state_class_name(chart)
    url_path, is_protected = _chart_data_source(program, chart, has_auth)

    auth_header_lines = []
    if is_protected:
        auth_header_lines = [
            "        auth_state = await self.get_state(AuthState)",
            '        headers = {"Authorization": f"Bearer {auth_state.token}"} if auth_state.token else {}',
        ]
    headers_kwarg = ", headers=headers" if is_protected else ""

    state_lines = [
        f"class {state_cls}(rx.State):",
        f'    """État Reflex pour le graphique `{chart.name}` (source : {chart.source}).'
        + (' Route protégée : le jeton AuthState est envoyé en en-tête Authorization."""' if is_protected else '"""'),
        "    rows: list[dict] = []",
        "    is_loading: bool = False",
        "",
        "    async def load_rows(self):",
        "        self.is_loading = True",
    ]
    state_lines += auth_header_lines
    state_lines += [
        "        async with httpx.AsyncClient() as client:",
        f'            resp = await client.get(f"{{BACKEND_URL}}/{url_path}"{headers_kwarg})',
        "            if resp.status_code == 200:",
        "                self.rows = resp.json()",
        "        self.is_loading = False",
        "",
    ]
    state_code = "\n".join(state_lines) + "\n"

    title = chart.title or chart.name
    x_key = chart.x_field or "x"
    y_key = chart.y_field or "y"
    y_keys = chart.y_fields or ([y_key] if y_key else [])

    if chart.type == "pie":
        # La donnée du camembert se pose sur le sous-composant `pie`, pas sur
        # `pie_chart` lui-même — contrairement à bar/line/area (vérifié par
        # exécution réelle avant d'écrire ce générateur).
        chart_component = (
            "rx.recharts.pie_chart(\n"
            f'    rx.recharts.pie(data={state_cls}.rows, data_key="{y_key}", name_key="{x_key}", '
            f'fill="{_CHART_COLOR}"),\n'
            "    rx.recharts.graphing_tooltip(),\n"
            "    rx.recharts.legend(),\n"
            '    width="100%",\n'
            "    height=360,\n"
            ")"
        )
    elif chart.type == "radar":
        # Comme `pie`, vérifié par construction réelle du composant avant
        # d'écrire ce générateur : `data=` se pose sur `radar_chart` (comme
        # bar/line/area), les axes polaires remplacent x_axis/y_axis. Un
        # seul champ toujours ici : multi-séries restreint à bar/line/area,
        # voir _validate_charts/kw.CHART_MULTI_SERIES_TYPES.
        chart_component = (
            "rx.recharts.radar_chart(\n"
            f'    rx.recharts.radar(data_key="{y_key}", stroke="{_CHART_COLOR}", '
            f'fill="{_CHART_COLOR}", fill_opacity=0.6),\n'
            "    rx.recharts.polar_grid(),\n"
            f'    rx.recharts.polar_angle_axis(data_key="{x_key}"),\n'
            "    rx.recharts.polar_radius_axis(),\n"
            "    rx.recharts.graphing_tooltip(),\n"
            f"    data={state_cls}.rows,\n"
            '    width="100%",\n'
            "    height=360,\n"
            ")"
        )
    elif chart.type == "scatter":
        # Vérifié par construction réelle : contrairement à bar/line/area/
        # radar, `data=` se pose ici sur le sous-composant `scatter`, pas sur
        # `scatter_chart` — et `y_axis` porte `data_key` (axe numérique),
        # comme `x_axis`.
        chart_component = (
            "rx.recharts.scatter_chart(\n"
            f'    rx.recharts.scatter(data={state_cls}.rows, fill="{_CHART_COLOR}"),\n'
            f'    rx.recharts.x_axis(data_key="{x_key}"),\n'
            f'    rx.recharts.y_axis(data_key="{y_key}"),\n'
            "    rx.recharts.graphing_tooltip(),\n"
            '    width="100%",\n'
            "    height=360,\n"
            ")"
        )
    else:
        # bar/line/area : seuls types multi-séries (kw.CHART_MULTI_SERIES_TYPES,
        # garanti par _validate_charts). Une série par champ de `axe_y`, une
        # couleur de _CHART_PALETTE par série (cycle si plus de séries que de
        # couleurs) ; à une seule série, produit exactement le même code
        # qu'avant l'ajout du multi-séries (_CHART_PALETTE[0] == _CHART_COLOR).
        chart_fn = {"bar": "bar_chart", "line": "line_chart", "area": "area_chart"}[chart.type]
        series_fn = {"bar": "bar", "line": "line", "area": "area"}[chart.type]
        series_lines = []
        for i, field_name in enumerate(y_keys):
            color = _CHART_PALETTE[i % len(_CHART_PALETTE)]
            if chart.type == "line":
                series_kwargs = f'data_key="{field_name}", stroke="{color}"'
            elif chart.type == "area":
                series_kwargs = f'data_key="{field_name}", fill="{color}", stroke="{color}"'
            else:  # bar
                series_kwargs = f'data_key="{field_name}", fill="{color}"'
            series_lines.append(f"    rx.recharts.{series_fn}({series_kwargs}),\n")
        legend_line = "    rx.recharts.legend(),\n" if len(y_keys) > 1 else ""
        chart_component = (
            f"rx.recharts.{chart_fn}(\n"
            + "".join(series_lines)
            + f'    rx.recharts.x_axis(data_key="{x_key}"),\n'
            + "    rx.recharts.y_axis(),\n"
            + "    rx.recharts.graphing_tooltip(),\n"
            + legend_line
            + f"    data={state_cls}.rows,\n"
            + '    width="100%",\n'
            + "    height=360,\n"
            + ")"
        )

    inner = (
        "rx.card(\n"
        "    rx.vstack(\n"
        f'        rx.heading("{title}", size="7"),\n'
        f"{textwrap.indent(chart_component, '        ')},\n"
        '        spacing="4",\n'
        '        width="100%",\n'
        "    ),\n"
        '    padding="2em",\n'
        '    width="100%",\n'
        ")"
    )
    view_code = (
        f"def {to_snake_case(chart.name)}_chart_page() -> rx.Component:\n"
        + _wrap_page_body(inner, f"{state_cls}.load_rows", "900px")
    )
    return state_code, view_code


# ------------------------------------------------------------- calendar ---

_WEEKDAY_LABELS = ["Lun/Mon", "Mar/Tue", "Mer/Wed", "Jeu/Thu", "Ven/Fri", "Sam/Sat", "Dim/Sun"]


def _calendar_state_class_name(cal: Calendar) -> str:
    return f"{to_pascal_case(cal.name)}CalendarState"


def _calendar_route(cal: Calendar) -> str:
    slug = to_snake_case(to_ascii_identifier(cal.name)).replace("_", "-")
    return f"/calendriers/{slug}" if slug else "/calendriers"


def _calendar_ics_slug(cal: Calendar) -> str:
    """Slug utilisé pour la route d'export iCal générée côté backend (voir
    codegen/api_fastapi.py::_generate_calendar_ics_router) — même slug que
    `_calendar_route` (juste sans le préfixe `/calendriers/`), pour que le
    lien affiché sur la page calendrier et la route backend restent
    cohérents sans dupliquer la logique de calcul du slug."""
    return to_snake_case(to_ascii_identifier(cal.name)).replace("_", "-")


def _calendar_data_source(program: NovaProgram, cal: Calendar, has_auth: bool) -> tuple[str, bool]:
    """Résout `calendar ... sur <Entite>` en (chemin_url_backend, protege) —
    toujours une Entity ici (`parser._validate_calendars` le garantit déjà),
    même logique d'héritage de la protection `api <Entity> { proteger: ... }`
    que `_chart_data_source`."""
    url_path = to_snake_case(pluralize(to_ascii_identifier(cal.entity))) + "/"
    api = _api_for_entity(program, cal.entity)
    is_protected = bool(has_auth and api and api.protected_role)
    return url_path, is_protected


def _generate_calendar_state_and_view(cal: Calendar, program: NovaProgram, has_auth: bool) -> tuple[str, str]:
    """Retourne (code_du_state, code_de_la_fonction_de_page) pour un bloc
    `calendar` : un état Reflex qui charge TOUTES les lignes de l'entité
    (comme une page table) puis les regroupe côté serveur — au choix, jour
    par jour du mois affiché (`_build_days`, vue historique), de la semaine
    affichée (`_build_week_days`) ou de la seule journée sélectionnée
    (`_build_day_events`) — via la seule stdlib (`calendar.Calendar.
    monthdatescalendar` + `datetime.date`/`timedelta` — aucune dépendance JS
    supplémentaire, conformément au choix de conception retenu pour cette
    fonctionnalité, ET explicitement SANS glisser-déposer d'événement,
    conformément à la décision explicite prise pour cette extension : vue
    semaine/jour + export iCal, mais pas de drag & drop). `self.view`
    ("month"/"week"/"day") sélectionne la vue active ; `rx.match` choisit le
    composant à afficher — voir `inner` plus bas. Chaque jour est un dict
    PLAT (`date`, `day`, `in_month`, `events_text`) plutôt qu'un dict
    contenant une liste imbriquée d'événements : `rx.foreach` niché sur une
    valeur `list[str]` à l'intérieur d'un state var `list[dict]` lève
    `ForeachVarError` (bug réel rencontré et corrigé pendant la conception
    de ce bloc `calendar`) — d'où `events_text`, les titres des événements
    du jour déjà joints en une seule chaîne (même principe pour
    `week_days`/`day_events`)."""
    state_cls = _calendar_state_class_name(cal)
    url_path, is_protected = _calendar_data_source(program, cal, has_auth)
    date_field_snake = to_snake_case(cal.date_field)
    title_field_snake = to_snake_case(cal.title_field) if cal.title_field else None

    auth_header_lines = []
    if is_protected:
        auth_header_lines = [
            "        auth_state = await self.get_state(AuthState)",
            '        headers = {"Authorization": f"Bearer {auth_state.token}"} if auth_state.token else {}',
        ]
    headers_kwarg = ", headers=headers" if is_protected else ""

    # Sans `champ_titre`/`title_field`, on affiche un simple marqueur "•"
    # pour signaler qu'un jour a des enregistrements, plutôt que rien.
    title_expr = f'str(row.get("{title_field_snake}", ""))' if title_field_snake else '"•"'
    weekday_labels_literal = "[" + ", ".join(repr(label) for label in _WEEKDAY_LABELS) + "]"

    state_lines = [
        f"class {state_cls}(rx.State):",
        f'    """État Reflex pour le calendrier `{cal.name}` (source : {cal.entity}).'
        + (' Route protégée : le jeton AuthState est envoyé en en-tête Authorization."""' if is_protected else '"""'),
        "    rows: list[dict] = []",
        "    days: list[dict] = []",
        "    week_days: list[dict] = []",
        "    day_events: list[dict] = []",
        "    year: int = date.today().year",
        "    month: int = date.today().month",
        '    week_start: str = ""',
        '    selected_day: str = ""',
        '    view: str = "month"    # "month" | "week" | "day"',
        '    label: str = ""',
        "    is_loading: bool = False",
        "",
        "    async def load_rows(self):",
        "        self.is_loading = True",
    ]
    state_lines += auth_header_lines
    state_lines += [
        "        async with httpx.AsyncClient() as client:",
        f'            resp = await client.get(f"{{BACKEND_URL}}/{url_path}"{headers_kwarg})',
        "            if resp.status_code == 200:",
        "                self.rows = resp.json()",
        "        self.is_loading = False",
        "        if not self.week_start:",
        "            self.week_start = (date.today() - timedelta(days=date.today().weekday())).isoformat()",
        "        if not self.selected_day:",
        "            self.selected_day = date.today().isoformat()",
        "        self._build_days()",
        "        self._build_week_days()",
        "        self._build_day_events()",
        "",
        "    def set_view(self, view: str):",
        "        self.view = view",
        "",
        "    def _build_days(self):",
        '        self.label = f"{self.year}-{self.month:02d}"',
        "        weeks = calendar.Calendar(firstweekday=0).monthdatescalendar(self.year, self.month)",
        "        days = []",
        "        for week in weeks:",
        "            for d in week:",
        "                iso = d.isoformat()",
        '                events_text = ", ".join(',
        f"                    {title_expr}",
        "                    for row in self.rows",
        f'                    if str(row.get("{date_field_snake}", ""))[:10] == iso',
        "                )",
        "                days.append({",
        '                    "date": iso,',
        '                    "day": d.day,',
        '                    "in_month": d.month == self.month,',
        '                    "events_text": events_text,',
        "                })",
        "        self.days = days",
        "",
        "    def _build_week_days(self):",
        "        # Semaine de 7 jours à partir de `week_start` (toujours un lundi,",
        "        # voir load_rows/prev/next) — pas de dépendance JS, même principe",
        "        # que `_build_days` mais sans la notion de mois affiché.",
        f"        weekday_labels = {weekday_labels_literal}",
        "        start = date.fromisoformat(self.week_start)",
        "        days = []",
        "        for i in range(7):",
        "            d = start + timedelta(days=i)",
        "            iso = d.isoformat()",
        '            events_text = ", ".join(',
        f"                {title_expr}",
        "                for row in self.rows",
        f'                if str(row.get("{date_field_snake}", ""))[:10] == iso',
        "            )",
        "            days.append({",
        '                "date": iso,',
        '                "day": d.day,',
        '                "weekday": weekday_labels[d.weekday()],',
        '                "events_text": events_text,',
        "            })",
        "        self.week_days = days",
        "",
        "    def _build_day_events(self):",
        "        # Liste (pas juste un texte joint, contrairement à `events_text`",
        "        # ci-dessus) des événements de `selected_day` : la vue jour a la",
        "        # place d'afficher chaque titre sur sa propre ligne.",
        "        iso = self.selected_day",
        "        events = []",
        "        for row in self.rows:",
        f'            if str(row.get("{date_field_snake}", ""))[:10] == iso:',
        f"                events.append({{\"title\": {title_expr}}})",
        "        self.day_events = events",
        "",
        "    def prev(self):",
        '        if self.view == "month":',
        "            self.month -= 1",
        "            if self.month < 1:",
        "                self.month = 12",
        "                self.year -= 1",
        "            self._build_days()",
        '        elif self.view == "week":',
        "            self.week_start = (date.fromisoformat(self.week_start) - timedelta(days=7)).isoformat()",
        "            self._build_week_days()",
        "        else:",
        "            self.selected_day = (date.fromisoformat(self.selected_day) - timedelta(days=1)).isoformat()",
        "            self._build_day_events()",
        "",
        "    def next(self):",
        '        if self.view == "month":',
        "            self.month += 1",
        "            if self.month > 12:",
        "                self.month = 1",
        "                self.year += 1",
        "            self._build_days()",
        '        elif self.view == "week":',
        "            self.week_start = (date.fromisoformat(self.week_start) + timedelta(days=7)).isoformat()",
        "            self._build_week_days()",
        "        else:",
        "            self.selected_day = (date.fromisoformat(self.selected_day) + timedelta(days=1)).isoformat()",
        "            self._build_day_events()",
        "",
    ]
    state_code = "\n".join(state_lines) + "\n"

    weekday_header = ",\n        ".join(
        f'rx.text("{label}", size="2", weight="bold", align="center")' for label in _WEEKDAY_LABELS
    )
    month_day_cell = (
        "rx.box(\n"
        '            rx.text(day["day"], size="2", weight="bold"),\n'
        '            rx.cond(day["events_text"] != "", rx.text(day["events_text"], size="1", color_scheme="gray")),\n'
        '            opacity=rx.cond(day["in_month"], "1", "0.35"),\n'
        '            padding="0.5em",\n'
        '            border="1px solid var(--gray-5)",\n'
        '            min_height="80px",\n'
        '            width="100%",\n'
        "        )"
    )
    week_day_cell = (
        "rx.box(\n"
        '            rx.text(day["weekday"], size="1", color_scheme="gray"),\n'
        '            rx.text(day["day"], size="2", weight="bold"),\n'
        '            rx.cond(day["events_text"] != "", rx.text(day["events_text"], size="1", color_scheme="gray")),\n'
        '            padding="0.5em",\n'
        '            border="1px solid var(--gray-5)",\n'
        '            min_height="100px",\n'
        '            width="100%",\n'
        "        )"
    )
    month_grid = (
        "rx.fragment(\n"
        "    rx.grid(\n"
        f"        {weekday_header},\n"
        '        columns="7",\n'
        '        spacing="1",\n'
        '        width="100%",\n'
        "    ),\n"
        "    rx.grid(\n"
        f"        rx.foreach({state_cls}.days, lambda day: {month_day_cell}),\n"
        '        columns="7",\n'
        '        spacing="1",\n'
        '        width="100%",\n'
        "    ),\n"
        ")"
    )
    week_grid = (
        "rx.grid(\n"
        f"    rx.foreach({state_cls}.week_days, lambda day: {week_day_cell}),\n"
        '    columns="7",\n'
        '    spacing="1",\n'
        '    width="100%",\n'
        ")"
    )
    day_list = (
        "rx.vstack(\n"
        "    rx.cond(\n"
        f"        {state_cls}.day_events.length() == 0,\n"
        '        rx.text("Aucun événement / No events", size="2", color_scheme="gray"),\n'
        f'        rx.foreach({state_cls}.day_events, lambda ev: rx.text(ev["title"], size="3")),\n'
        "    ),\n"
        '    spacing="2",\n'
        '    align="start",\n'
        '    width="100%",\n'
        ")"
    )
    label_display = (
        "rx.match(\n"
        f"    {state_cls}.view,\n"
        f'    ("week", rx.heading({state_cls}.week_start, size="4")),\n'
        f'    ("day", rx.heading({state_cls}.selected_day, size="4")),\n'
        f'    rx.heading({state_cls}.label, size="4"),\n'
        ")"
    )
    slug = _calendar_ics_slug(cal)
    inner = (
        "rx.vstack(\n"
        f'    rx.heading("{cal.name}", size="7"),\n'
        "    rx.hstack(\n"
        f'        rx.button("Mois / Month", on_click=lambda: {state_cls}.set_view("month"), '
        f'size="2", variant=rx.cond({state_cls}.view == "month", "solid", "soft")),\n'
        f'        rx.button("Semaine / Week", on_click=lambda: {state_cls}.set_view("week"), '
        f'size="2", variant=rx.cond({state_cls}.view == "week", "solid", "soft")),\n'
        f'        rx.button("Jour / Day", on_click=lambda: {state_cls}.set_view("day"), '
        f'size="2", variant=rx.cond({state_cls}.view == "day", "solid", "soft")),\n'
        f'        rx.link("Exporter iCal / Export iCal", href=f"{{PUBLIC_BACKEND_URL}}/ics/{slug}.ics", is_external=True),\n'
        '        spacing="3",\n'
        '        align="center",\n'
        '        wrap="wrap",\n'
        "    ),\n"
        "    rx.hstack(\n"
        f'        rx.button("<", on_click={state_cls}.prev, size="2", variant="soft"),\n'
        f"        {textwrap.indent(label_display, '        ').strip()},\n"
        f'        rx.button(">", on_click={state_cls}.next, size="2", variant="soft"),\n'
        '        spacing="3",\n'
        '        align="center",\n'
        "    ),\n"
        "    rx.match(\n"
        f"        {state_cls}.view,\n"
        f'        ("week", {textwrap.indent(week_grid, "        ").strip()}),\n'
        f'        ("day", {textwrap.indent(day_list, "        ").strip()}),\n'
        f"        {textwrap.indent(month_grid, '        ').strip()},\n"
        "    ),\n"
        '    spacing="4",\n'
        '    width="100%",\n'
        ")"
    )
    view_code = (
        f"def {to_snake_case(cal.name)}_calendar_page() -> rx.Component:\n"
        + _wrap_page_body(inner, f"{state_cls}.load_rows", "1000px")
    )
    return state_code, view_code


# ---------------------------------------- champs riches (file/image/color/bool) ---
# Un champ `file`/`fichier`, `image`, `color`/`couleur` ou `bool` mérite un
# widget dédié plutôt qu'un `rx.input` texte générique : upload avec aperçu,
# sélecteur de couleur natif, badge Oui/Non. Ces helpers centralisent ce
# choix pour le formulaire (widget de saisie) et pour les vues table/card
# (rendu de valeur) afin que les deux restent cohérents.

_UPLOAD_FIELD_TYPES = ("file", "image")


def _input_type_and_extra_kwarg(f) -> tuple[str, str]:
    """Type HTML natif (`type="..."`) et kwarg Reflex additionnel pour un
    champ scalaire simple (pas file/image, gérés à part avec `rx.upload`) —
    donne un vrai sélecteur de date/heure/couleur/nombre au lieu d'un champ
    texte brut, sans changer le type de la variable de state (toujours
    `str`, comme avant) ni le format de la charge utile envoyée au backend."""
    if f.type == "date":
        return "date", ""
    if f.type == "datetime":
        return "datetime-local", ""
    if f.type == "int":
        return "number", ""
    if f.type == "float":
        return "number", ', step="any"'
    if f.type == "color":
        return "color", ""
    return "text", ""


def _upload_id(state_cls: str, field_snake: str) -> str:
    return f"upload_{to_snake_case(state_cls)}_{field_snake}"


def _upload_form_block_src(state_cls: str, f) -> str:
    """Bloc de formulaire pour un champ `file`/`image` : zone de dépôt
    (`rx.upload`) qui envoie le fichier au backend dès la sélection (voir
    `handle_upload_<champ>` généré dans le state) et stocke l'URL retournée
    dans `new_<champ>` — exactement comme les autres champs, qui portent
    déjà cette valeur au moment de la soumission du formulaire. Un aperçu
    (miniature pour une image, lien de téléchargement sinon) apparaît une
    fois l'upload terminé."""
    snake = to_snake_case(f.name)
    upload_id = _upload_id(state_cls, snake)
    var = f"{state_cls}.new_{snake}"
    if f.type == "image":
        preview = (
            f'rx.cond({var} != "", '
            f'rx.image(src=f"{{PUBLIC_BACKEND_URL}}{{{var}}}", width="80px", height="80px", '
            f'radius="md", style={{"object-fit": "cover"}})),'
        )
    else:
        preview = (
            f'rx.cond({var} != "", '
            f'rx.link({var}, href=f"{{PUBLIC_BACKEND_URL}}{{{var}}}", target="_blank", size="2")),'
        )
    dropzone_label = "Glisser un fichier ou cliquer / Drop a file or click"
    return (
        "    rx.vstack(\n"
        f'        rx.text("{f.name}", size="2", weight="bold", color_scheme="gray"),\n'
        "        rx.upload(\n"
        f'            rx.text("{dropzone_label}", size="2", color_scheme="gray"),\n'
        f'            id="{upload_id}",\n'
        f'            on_drop={state_cls}.handle_upload_{snake}(rx.upload_files(upload_id="{upload_id}")),\n'
        '            border="1px dashed var(--gray-8)",\n'
        '            border_radius="var(--radius-3)",\n'
        '            padding="1em",\n'
        '            width="100%",\n'
        "        ),\n"
        f"        {preview}\n"
        '        spacing="1",\n'
        '        width="100%",\n'
        "    ),"
    )


def _upload_handler_state_lines(state_cls: str, f) -> list[str]:
    """Méthode de state appelée dès qu'un fichier est déposé dans la zone
    d'upload : envoie le fichier au backend (`POST /uploads/`, voir
    codegen/api_fastapi._generate_uploads_router) et stocke l'URL relative
    retournée — la même variable `new_<champ>` que les autres types de
    champ, envoyée telle quelle dans la charge utile de `submit()`."""
    snake = to_snake_case(f.name)
    return [
        f"    async def handle_upload_{snake}(self, files: list[rx.UploadFile]) -> None:",
        "        for file in files:",
        "            data = await file.read()",
        "            async with httpx.AsyncClient() as client:",
        '                resp = await client.post(',
        '                    f"{BACKEND_URL}/uploads/", files={"file": (file.name, data)}',
        "                )",
        "                if resp.status_code == 200:",
        f'                    self.new_{snake} = resp.json()["url"]',
    ]


def _field_value_src(f, row_access: str, default_src: str) -> str:
    """Expression Reflex (texte source) affichant la valeur d'un champ `f`
    d'une ligne de données (`row_access`, ex. `row["prix"]`) dans une vue
    table/card. Rendu enrichi pour les types visuels ; `default_src` (fourni
    par l'appelant, différent entre table et card) pour tous les autres
    types — comportement inchangé par rapport à avant l'ajout des champs
    riches."""
    if f.type == "image":
        return (
            f'rx.cond({row_access} != "", '
            f'rx.image(src=f"{{PUBLIC_BACKEND_URL}}{{{row_access}}}", width="48px", height="48px", '
            f'radius="md", style={{"object-fit": "cover"}}), rx.text("—"))'
        )
    if f.type == "file":
        return (
            f'rx.cond({row_access} != "", '
            f'rx.link("Télécharger / Download", href=f"{{PUBLIC_BACKEND_URL}}{{{row_access}}}", target="_blank"), '
            f'rx.text("—"))'
        )
    if f.type == "color":
        return (
            f'rx.hstack(rx.box(width="16px", height="16px", background={row_access}, '
            f'border_radius="4px", border="1px solid var(--gray-6)"), rx.text({row_access}), '
            f'spacing="2", align="center")'
        )
    if f.type == "bool":
        return (
            f'rx.cond({row_access}, rx.badge("Oui / Yes", color_scheme="green"), '
            f'rx.badge("Non / No", color_scheme="gray"))'
        )
    return default_src


# ---------------------------------------------------------------- style ---

def _snake_to_camel(name: str) -> str:
    parts = name.replace("-", "_").split("_")
    return parts[0] + "".join(p[:1].upper() + p[1:] for p in parts[1:] if p)


def _style_kwargs_src(style: dict[str, str]) -> str:
    """Kwargs Reflex supplémentaires (`, class_name="...", style={...}`) pour
    un bloc `style { ... }` du DSL — chaîne vide si aucun style déclaré.
    Les clés connues de `keywords.STYLE_ALIASES` (ex. `couleur_fond`) sont
    traduites vers la propriété CSS réelle ; toute autre clé est passée
    telle quelle (snake_case ou kebab-case), convertie en camelCase pour
    Reflex — la "porte de sortie" qui garde ce bloc aussi souple que du CSS
    brut."""
    if not style:
        return ""
    class_name = None
    css_props: dict[str, str] = {}
    for key, value in style.items():
        if key in STYLE_CLASS_KEYS:
            class_name = value
            continue
        css_key = STYLE_ALIASES.get(key, key.replace("_", "-"))
        camel_key = _snake_to_camel(css_key.replace("-", "_"))
        css_props[camel_key] = value
    parts = []
    if class_name:
        parts.append(f'class_name="{class_name}"')
    if css_props:
        style_dict_src = ", ".join(f'"{k}": "{v}"' for k, v in css_props.items())
        parts.append(f"style={{{style_dict_src}}}")
    return (", " + ", ".join(parts)) if parts else ""


# ------------------------------------------------------------------ i18n ---
# Bloc `traductions { ... }` (textes d'interface) + modificateur
# `multilingue` sur un champ `chaine`/`texte` (données) : un état
# `LangState` partagé (langue courante persistée en cookie, comme
# `AuthState.token`), un sélecteur de langue dans la navbar, une fonction
# `t_<cle>()` par entrée du bloc `traductions`, et le rendu table/carte/
# formulaire des champs `multilingue`. Les textes/valeurs sont résolus via
# `rx.match(LangState.lang, ...)` — une expression Reflex RÉACTIVE — plutôt
# qu'un dict Python lu une fois à la génération : le texte affiché doit
# changer immédiatement quand on bascule la langue via le sélecteur, sans
# recharger la page.

_LANG_STATE_TEMPLATE = '''\
class LangState(rx.State):
    """État de langue partagé (voir bloc `traductions {{ ... }}` et le
    modificateur `multilingue` sur un champ) — persisté dans un cookie
    navigateur, valable entre deux rechargements de page, comme le jeton
    JWT de AuthState."""

    lang: str = rx.Cookie("{default_lang}", name="nova_lang")

    def set_lang(self, value: str) -> None:
        self.lang = value
'''


def _generate_lang_state(active_langs: list[str]) -> str:
    # Langue par défaut du cookie : `application { lang: ... }` si déclarée
    # (validée par parser._validate_app_languages — forcément dans
    # `active_langs` si `langues:` est aussi utilisé), sinon la première
    # langue active (généralement "fr", comportement historique inchangé
    # quand `langues:` n'est pas utilisé, puisqu'active_langs == LANG_CODES
    # commence par "fr" — voir `NovaProgram.active_languages`).
    default_lang = active_langs[0]
    return _LANG_STATE_TEMPLATE.format(default_lang=default_lang)


def _lang_switcher_src(active_langs: list[str]) -> str:
    return (
        "rx.select(\n"
        f"            {active_langs!r},\n"
        "            value=LangState.lang,\n"
        "            on_change=LangState.set_lang,\n"
        '            size="2",\n'
        "        ),\n"
    )


def _translation_fn_name(key: str) -> str:
    return f"t_{to_snake_case(key)}"


def _generate_translation_helpers(program: NovaProgram) -> str:
    """Une fonction Python par clé du bloc `traductions`, retournant une
    expression `rx.match` réactive plutôt qu'un texte figé à la
    génération."""
    active_langs = program.active_languages()
    lines = []
    for key, texts in program.translations.items():
        fn_name = _translation_fn_name(key)
        cases = ", ".join(f"({lang!r}, {texts[lang]!r})" for lang in active_langs)
        default = repr(texts[active_langs[0]])
        lines.append(f"def {fn_name}():")
        lines.append(f"    return rx.match(LangState.lang, {cases}, {default})")
        lines.append("")
        lines.append("")
    return "\n".join(lines)


def _title_expr_src(show, fallback: str) -> str:
    """Expression Reflex (texte source, sans le rendre entre guillemets)
    pour le titre d'une page : soit un appel à la fonction de traduction
    générée (`titre <cle>` -> `t_<cle>()`), soit une chaîne littérale
    entre guillemets (`titre "texte"`, ou titre absent -> nom de la
    page/du show, comportement inchangé par rapport à avant l'ajout de
    l'i18n)."""
    if show is not None and show.title_key:
        return f"{_translation_fn_name(show.title_key)}()"
    text = (show.title if show is not None else None) or fallback
    return f'"{text}"'


def _multilingual_display_expr(f, active_langs: list[str], row_var: str = "row") -> str:
    """Expression Reflex affichant la valeur d'un champ `multilingue` dans
    la langue actuellement sélectionnée — une colonne par langue ACTIVE en
    base (voir codegen/api_fastapi.py), résolue avec `rx.match` (repli sur
    la première langue active si `LangState.lang` ne correspondait à
    aucune des valeurs attendues, ce qui ne devrait jamais arriver en
    pratique)."""
    base = to_snake_case(f.name)
    cases = ", ".join(f'("{lang}", {row_var}["{base}_{lang}"])' for lang in active_langs)
    return f'rx.match(LangState.lang, {cases}, {row_var}["{base}_{active_langs[0]}"])'


def _multilingual_form_block_src(state_cls: str, f, active_langs: list[str]) -> str:
    """Bloc de formulaire pour un champ `multilingue` : un `rx.input` par
    langue ACTIVE, labellisé `<champ> (fr)`/`<champ> (en)`/..., chacun lié à
    sa propre variable de state `new_<champ>_<lang>` — même pattern de
    setters explicites que les champs simples (voir
    `_generate_state_and_view`), pour la même raison (fiabilité variable
    des setters auto-générés selon la version de Reflex installée)."""
    base = to_snake_case(f.name)
    blocks = []
    for lang in active_langs:
        var_name = f"new_{base}_{lang}"
        blocks.append(
            "    rx.vstack(\n"
            f'        rx.text("{f.name} ({lang})", size="2", weight="bold", color_scheme="gray"),\n'
            f'        rx.input(placeholder="{f.name} ({lang})", value={state_cls}.{var_name}, '
            f'on_change={state_cls}.set_{var_name}, size="3", width="100%"),\n'
            '        spacing="1",\n'
            '        width="100%",\n'
            "    ),"
        )
    return "\n".join(blocks)


# ----------------------------------------------------------------- auth ---

_AUTH_STATE_TEMPLATE = '''\
class AuthState(rx.State):
    """État d'authentification partagé (voir bloc `auth {{ ... }}` du fichier
    .nova) — le jeton JWT est persisté dans un cookie navigateur, valable
    entre deux rechargements de page."""

    token: str = rx.Cookie("", name="nova_token")
    email: str = ""
    password: str = ""
    error_message: str = ""

    def set_email(self, value: str) -> None:
        self.email = value

    def set_password(self, value: str) -> None:
        self.password = value

    async def login(self):
        self.error_message = ""
        async with httpx.AsyncClient() as client:
            resp = await client.post(
                f"{{BACKEND_URL}}/auth/login",
                data={{"username": self.email, "password": self.password}},
            )
            if resp.status_code == 200:
                self.token = resp.json()["access_token"]
                self.password = ""
                return rx.redirect("{home_route}")
            self.error_message = "Identifiants invalides / Invalid credentials"

    def logout(self):
        self.token = ""
        return rx.redirect("{login_route}")
'''


def _generate_auth_state(program: NovaProgram) -> str:
    home_route = _page_route(program.pages[0]) if program.pages else "/"
    return _AUTH_STATE_TEMPLATE.format(home_route=home_route, login_route="/connexion")


def _generate_login_page() -> str:
    inner = (
        "rx.card(\n"
        "    rx.vstack(\n"
        '        rx.heading("Connexion / Login", size="7"),\n'
        '        rx.cond(\n'
        '            AuthState.error_message != "",\n'
        '            rx.text(AuthState.error_message, color="red", size="2"),\n'
        "        ),\n"
        "        rx.vstack(\n"
        '            rx.text("Email", size="2", weight="bold", color_scheme="gray"),\n'
        '            rx.input(placeholder="email@exemple.com", value=AuthState.email, '
        'on_change=AuthState.set_email, size="3", width="100%"),\n'
        '            spacing="1",\n'
        '            width="100%",\n'
        "        ),\n"
        "        rx.vstack(\n"
        '            rx.text("Mot de passe / Password", size="2", weight="bold", color_scheme="gray"),\n'
        '            rx.input(placeholder="********", value=AuthState.password, '
        'on_change=AuthState.set_password, type="password", size="3", width="100%"),\n'
        '            spacing="1",\n'
        '            width="100%",\n'
        "        ),\n"
        '        rx.button("Se connecter / Log in", on_click=AuthState.login, size="3", '
        'width="100%", color_scheme="violet"),\n'
        '        spacing="4",\n'
        '        width="100%",\n'
        "    ),\n"
        '    padding="2em",\n'
        '    width="100%",\n'
        ")"
    )
    return "def connexion_page() -> rx.Component:\n" + _wrap_page_body(inner, "None", "420px")


def _generate_navbar(program: NovaProgram, has_auth: bool, has_i18n: bool = False) -> str:
    app_title = program.app.name if program.app else "NOVA App"
    links = "\n".join(
        f'        rx.link("{p.name}", href="{_page_route(p)}", size="3", weight="medium", '
        f'color_scheme="gray", high_contrast=True),'
        for p in program.pages
    )
    chart_links = "\n".join(
        f'        rx.link("{c.name}", href="{_chart_route(c)}", size="3", weight="medium", '
        f'color_scheme="gray", high_contrast=True),'
        for c in program.charts
    )
    if chart_links:
        links = f"{links}\n{chart_links}" if links else chart_links
    calendar_links = "\n".join(
        f'        rx.link("{c.name}", href="{_calendar_route(c)}", size="3", weight="medium", '
        f'color_scheme="gray", high_contrast=True),'
        for c in program.calendars
    )
    if calendar_links:
        links = f"{links}\n{calendar_links}" if links else calendar_links
    auth_links = ""
    if has_auth:
        auth_links = (
            "        rx.cond(\n"
            "            AuthState.token != \"\",\n"
            '            rx.button("Déconnexion / Log out", on_click=AuthState.logout, size="2", variant="soft"),\n'
            '            rx.link(rx.button("Connexion / Log in", size="2"), href="/connexion"),\n'
            "        ),\n"
        )
    lang_switcher = f"        {_lang_switcher_src(program.active_languages())}" if has_i18n else ""
    return (
        "def nova_navbar() -> rx.Component:\n"
        '    """Barre de navigation partagée entre toutes les pages générées."""\n'
        "    return rx.hstack(\n"
        f'        rx.heading("{app_title}", size="5", weight="bold"),\n'
        "        rx.spacer(),\n"
        f"{links}\n"
        f"{lang_switcher}"
        f"{auth_links}"
        "        align=\"center\",\n"
        "        width=\"100%\",\n"
        "        padding=\"1em 2em\",\n"
        "        border_bottom=\"1px solid var(--gray-5)\",\n"
        "        background=\"var(--color-panel-solid)\",\n"
        "        position=\"sticky\",\n"
        "        top=\"0\",\n"
        "        z_index=\"10\",\n"
        "    )\n"
    )


def _wrap_page_body(inner_component_src: str, on_mount_expr: str, container_max_width: str) -> str:
    """Enveloppe le contenu propre à une page (`inner_component_src`, une
    expression Reflex sans le mot-clé `return`) dans le "shell" commun à
    toutes les pages : barre de navigation, conteneur centré, fond pleine
    page. Cette fonction gère l'indentation pour que le fichier généré
    reste lisible ; Python n'exige pas d'indentation précise à l'intérieur
    d'une liste d'arguments entre parenthèses, donc une légère imprécision
    ne casserait rien, mais on la soigne pour un fichier généré agréable à
    relire."""
    indented_inner = textwrap.indent(inner_component_src.rstrip("\n"), "            ")
    return (
        "    return rx.box(\n"
        "        nova_navbar(),\n"
        "        rx.container(\n"
        f"{indented_inner},\n"
        f'            max_width="{container_max_width}",\n'
        '            padding="2em",\n'
        '            width="100%",\n'
        "        ),\n"
        f"        on_mount={on_mount_expr},\n"
        '        width="100%",\n'
        '        min_height="100vh",\n'
        '        background="var(--gray-2)",\n'
        "    )\n"
    )


def _generate_show_state_and_inner(
    page: Page, show, program: NovaProgram, has_auth: bool, state_cls: str
) -> tuple[str, str, str]:
    """Retourne (code_du_state, composant_interne_src, largeur_conteneur)
    pour UN `show` d'un bloc `page` — factorisé hors de
    `_generate_state_and_view` pour que celle-ci puisse composer plusieurs
    `show` sur la même page (pages multi-entités, voir plus bas) en
    appelant cette fonction une fois par `show` avec un `state_cls` propre
    à chacun. `composant_interne_src` est une expression Reflex SANS le
    `return`/wrapper de page (barre de nav, conteneur...) — c'est
    `_generate_state_and_view` qui assemble le/les composants renvoyés ici
    dans la page finale (un seul `show` : directement ; plusieurs : empilés
    dans un `rx.vstack`, voir plus bas)."""
    entity = program.get_entity(show.entity)
    table_url_path = to_snake_case(pluralize(to_ascii_identifier(show.entity)))
    title_expr = _title_expr_src(show, page.name)
    fields = entity.fields if entity else []
    # Relations `has_many` de cette entité (voir `_has_many_text_fields`) :
    # matérialisées en table/carte comme une colonne/ligne supplémentaire
    # par relation, lue directement depuis le résumé texte déjà calculé par
    # le backend (`load_rows` reçoit `<table_enfant>_text` tel quel, aucune
    # requête HTTP supplémentaire n'est nécessaire côté frontend). Non
    # affichées en mode `formulaire` : ce mode ne sert qu'à CRÉER un nouvel
    # enregistrement, qui n'a par définition encore aucun enfant lié.
    has_many_fields = _has_many_text_fields(entity, program) if entity else []
    # Langues actives du projet (`application { langues: ... }`, ou les 6
    # langues du DSL par défaut — voir `NovaProgram.active_languages`) :
    # utilisées pour chaque champ `multilingue` de cette entité (state vars/
    # setters/payload ci-dessous, et l'affichage table/carte/formulaire).
    active_langs = program.active_languages()
    api = _api_for_entity(program, show.entity)
    is_protected = bool(has_auth and api and api.protected_role)

    state_lines = [
        f"class {state_cls}(rx.State):",
        f'    """État Reflex pour la page `{page.name}` (affiche {show.entity} en mode {show.mode}).'
        + (' Route protégée : le jeton AuthState est envoyé en en-tête Authorization."""' if is_protected else '"""'),
        "    rows: list[dict] = []",
        "    is_loading: bool = False",
    ]
    for f in fields:
        snake = to_snake_case(f.name)
        if f.multilingual:
            for lang in active_langs:
                state_lines.append(f'    new_{snake}_{lang}: str = ""')
        else:
            state_lines.append(f'    new_{snake}: str = ""')

    if show.mode == "form":
        # Setters explicites : ne pas compter sur les setters `set_<var>`
        # auto-générés par Reflex, dont la disponibilité/le nom exact a varié
        # selon les versions de Reflex (observé en pratique : AttributeError
        # "has no attribute 'set_new_xxx'" avec certaines versions récentes).
        # Un setter écrit explicitement fonctionne quelle que soit la version.
        for f in fields:
            snake = to_snake_case(f.name)
            if f.multilingual:
                for lang in active_langs:
                    state_lines.append(f"    def set_new_{snake}_{lang}(self, value: str) -> None:")
                    state_lines.append(f"        self.new_{snake}_{lang} = value")
            else:
                state_lines.append(f"    def set_new_{snake}(self, value: str) -> None:")
                state_lines.append(f"        self.new_{snake} = value")
        # Champs `file`/`image` : pas de setter texte, un gestionnaire
        # d'upload à la place (voir `_upload_handler_state_lines`).
        for f in fields:
            if f.type in _UPLOAD_FIELD_TYPES:
                state_lines += _upload_handler_state_lines(state_cls, f)

    auth_header_lines = []
    if is_protected:
        auth_header_lines = [
            "        auth_state = await self.get_state(AuthState)",
            '        headers = {"Authorization": f"Bearer {auth_state.token}"} if auth_state.token else {}',
        ]
    headers_kwarg = ", headers=headers" if is_protected else ""

    state_lines += [
        "",
        "    async def load_rows(self):",
        "        self.is_loading = True",
    ]
    state_lines += auth_header_lines
    state_lines += [
        "        async with httpx.AsyncClient() as client:",
        f'            resp = await client.get(f"{{BACKEND_URL}}/{table_url_path}/"{headers_kwarg})',
        "            if resp.status_code == 200:",
        "                self.rows = resp.json()",
        "        self.is_loading = False",
        "",
    ]
    if show.mode == "form":
        payload_parts = []
        for f in fields:
            snake = to_snake_case(f.name)
            if f.multilingual:
                payload_parts += [f'"{snake}_{lang}": self.new_{snake}_{lang}' for lang in active_langs]
            else:
                payload_parts.append(f'"{snake}": self.new_{snake}')
        payload_items = ", ".join(payload_parts)
        redirect_route = _table_route_for_entity(program, show.entity)
        state_lines += ["    async def submit(self):"]
        state_lines += auth_header_lines
        state_lines += [
            "        async with httpx.AsyncClient() as client:",
            f'            await client.post(f"{{BACKEND_URL}}/{table_url_path}/", json={{{payload_items}}}{headers_kwarg})',
        ]
        for f in fields:
            snake = to_snake_case(f.name)
            if f.multilingual:
                for lang in active_langs:
                    state_lines.append(f'        self.new_{snake}_{lang} = ""')
            else:
                state_lines.append(f'        self.new_{snake} = ""')
        if redirect_route:
            # On revient sur le tableau qui liste cette entité une fois
            # l'enregistrement créé, plutôt que de rester sur le formulaire.
            state_lines.append(f'        return rx.redirect("{redirect_route}")')
        else:
            state_lines.append("        await self.load_rows()")
        state_lines.append("")
    state_code = "\n".join(state_lines) + "\n"

    style_kwargs = _style_kwargs_src(show.style)

    # ---- vue -------------------------------------------------------------
    if show.mode == "table":
        header_cells = ", ".join(
            [f'rx.table.column_header_cell("{f.name}")' for f in fields]
            + [f'rx.table.column_header_cell("{label}")' for label, _key in has_many_fields]
        )

        def _table_cell_src(f) -> str:
            if f.multilingual:
                return f"rx.table.cell({_multilingual_display_expr(f, active_langs)})"
            access = f"row['{to_snake_case(f.name)}']"
            return f"rx.table.cell({_field_value_src(f, access, access)})"

        row_cells = ", ".join(
            [_table_cell_src(f) for f in fields]
            + [f"rx.table.cell(row['{key}'])" for _label, key in has_many_fields]
        )
        create_page = _form_page_for_entity(program, show.entity)
        create_link = (
            f'rx.link(rx.button("+ {create_page.name}", size="2"), href="{_page_route(create_page)}"),'
            if create_page
            else ""
        )
        inner = (
            "rx.vstack(\n"
            "    rx.hstack(\n"
            f'        rx.heading({title_expr}, size="7"),\n'
            "        rx.spacer(),\n"
            f"        {create_link}\n"
            '        width="100%",\n'
            '        align="center",\n'
            "    ),\n"
            "    rx.card(\n"
            "        rx.table.root(\n"
            "            rx.table.header(\n"
            f"                rx.table.row({header_cells}),\n"
            "            ),\n"
            "            rx.table.body(\n"
            f"                rx.foreach({state_cls}.rows, lambda row: rx.table.row({row_cells})),\n"
            "            ),\n"
            '            variant="surface",\n'
            '            width="100%",\n'
            "        ),\n"
            f'        width="100%"{style_kwargs},\n'
            "    ),\n"
            '    spacing="4",\n'
            '    width="100%",\n'
            ")"
        )
        container_width = "1100px"
    elif show.mode == "form":
        field_blocks = []
        for f in fields:
            snake = to_snake_case(f.name)
            if f.multilingual:
                field_blocks.append(_multilingual_form_block_src(state_cls, f, active_langs))
                continue
            if f.type in _UPLOAD_FIELD_TYPES:
                field_blocks.append(_upload_form_block_src(state_cls, f))
                continue
            input_type, extra_kwarg = _input_type_and_extra_kwarg(f)
            type_kwarg = f', type="{input_type}"' if input_type != "text" else ""
            field_blocks.append(
                "    rx.vstack(\n"
                f'        rx.text("{f.name}", size="2", weight="bold", color_scheme="gray"),\n'
                f'        rx.input(placeholder="{f.name}", value={state_cls}.new_{snake}, '
                f"on_change={state_cls}.set_new_{snake}, size=\"3\", width=\"100%\"{type_kwarg}{extra_kwarg}),\n"
                '        spacing="1",\n'
                '        width="100%",\n'
                "    ),"
            )
        fields_src = "\n".join(field_blocks)
        inner = (
            "rx.card(\n"
            "    rx.vstack(\n"
            f'        rx.heading({title_expr}, size="7"),\n'
            f"{fields_src}\n"
            f'        rx.button("Enregistrer / Save", on_click={state_cls}.submit, size="3", '
            'width="100%", color_scheme="violet"),\n'
            '        spacing="4",\n'
            '        width="100%",\n'
            "    ),\n"
            f'    padding="2em",\n'
            f'    width="100%"{style_kwargs},\n'
            ")"
        )
        container_width = "560px"
    else:  # card

        def _card_value_src(f) -> str:
            if f.multilingual:
                return f"rx.text({_multilingual_display_expr(f, active_langs)})"
            access = f"row['{to_snake_case(f.name)}']"
            default_src = f'rx.text(f"{f.name}: {{{access}}}")'
            return _field_value_src(f, access, default_src)

        def _has_many_value_src(label: str, key: str) -> str:
            access = f"row['{key}']"
            return f'rx.text(f"{label}: {{{access}}}")'

        card_rows = ", ".join(
            [_card_value_src(f) for f in fields]
            + [_has_many_value_src(label, key) for label, key in has_many_fields]
        )
        inner = (
            "rx.vstack(\n"
            f'    rx.heading({title_expr}, size="7"),\n'
            "    rx.grid(\n"
            f"        rx.foreach({state_cls}.rows, lambda row: rx.card(\n"
            f"            rx.vstack({card_rows}, spacing=\"2\"),\n"
            '            padding="1.5em",\n'
            "        )),\n"
            '        columns="3",\n'
            '        spacing="4",\n'
            '        width="100%",\n'
            "    ),\n"
            '    spacing="4",\n'
            f'    width="100%"{style_kwargs},\n'
            ")"
        )
        container_width = "1100px"

    return state_code, inner, container_width


def _generate_state_and_view(page: Page, program: NovaProgram, has_auth: bool) -> tuple[str, str]:
    """Retourne (code_du_state, code_de_la_fonction_de_page) pour un bloc
    `page`. Une page sans `show` reste une simple page-titre (comportement
    historique inchangé). Une page avec UN SEUL `show` délègue directement
    à `_generate_show_state_and_inner` et enveloppe son résultat — sortie
    strictement identique à avant l'ajout des pages multi-entités (même
    nom de state `<NomPage>State`, voir `_state_class_name`).

    Une page avec PLUSIEURS `show` (pages multi-entités) appelle
    `_generate_show_state_and_inner` une fois par `show`, chacun avec son
    propre state (`<NomPage><Entite>State`, pas de collision même si deux
    `show` affichent la même entité dans des modes différents), empile les
    composants renvoyés dans un seul `rx.vstack` (une section par `show`,
    dans l'ordre déclaré), et charge toutes leurs données au montage via
    une LISTE de gestionnaires `on_mount=[...]` (accepté par Reflex, vérifié
    par construction réelle avant d'écrire ce générateur) plutôt qu'un seul
    `on_mount=<state>.load_rows`."""
    if not page.shows:
        state_cls = _state_class_name(page)
        state_code = f"class {state_cls}(rx.State):\n    pass\n"
        view_code = (
            f"def {to_snake_case(page.name)}_page() -> rx.Component:\n"
            + _wrap_page_body(f'rx.heading("{page.name}", size="7")', "None", "800px")
        )
        return state_code, view_code

    if len(page.shows) == 1:
        show = page.shows[0]
        state_cls = _state_class_name(page)
        state_code, inner, container_width = _generate_show_state_and_inner(
            page, show, program, has_auth, state_cls
        )
        view_code = (
            f"def {to_snake_case(page.name)}_page() -> rx.Component:\n"
            + _wrap_page_body(inner, f"{state_cls}.load_rows", container_width)
        )
        return state_code, view_code

    # Pages multi-entités : un state + une section par `show`, empilés.
    # Si la même entité apparaît plusieurs fois sur cette page (ex. `show
    # Produit as table` PUIS `show Produit as carte`), `_state_class_name`
    # produirait le même nom de classe pour les deux — on numérote alors
    # chaque occurrence (1-based) pour éviter la collision silencieuse.
    entity_counts: dict[str, int] = {}
    for show in page.shows:
        entity_counts[show.entity] = entity_counts.get(show.entity, 0) + 1
    entity_seen: dict[str, int] = {}

    state_codes = []
    sections = []
    load_exprs = []
    max_container_width = 0
    for show in page.shows:
        if entity_counts[show.entity] > 1:
            entity_seen[show.entity] = entity_seen.get(show.entity, 0) + 1
            index = entity_seen[show.entity]
        else:
            index = None
        state_cls = _state_class_name(page, show, index)
        state_code, inner, container_width = _generate_show_state_and_inner(
            page, show, program, has_auth, state_cls
        )
        state_codes.append(state_code)
        sections.append(inner)
        load_exprs.append(f"{state_cls}.load_rows")
        max_container_width = max(max_container_width, int(container_width.rstrip("px")))

    # `.strip()` ci-dessous retire l'indentation de la PREMIÈRE ligne de
    # chaque section (comme ailleurs dans ce fichier, ex. chart_component
    # dans un `rx.card`) ; `textwrap.indent` gère les lignes suivantes.
    combined_sections_lines = []
    for section in sections:
        indented = textwrap.indent(section, "        ")
        combined_sections_lines.append(indented.strip())
    combined_inner = (
        "rx.vstack(\n        "
        + ",\n        ".join(combined_sections_lines)
        + ',\n        spacing="6",\n        width="100%",\n    )'
    )
    view_code = (
        f"def {to_snake_case(page.name)}_page() -> rx.Component:\n"
        + _wrap_page_body(
            combined_inner,
            "[" + ", ".join(load_exprs) + "]",
            f"{max_container_width}px",
        )
    )
    return "\n".join(state_codes), view_code


def generate_frontend(program: NovaProgram) -> dict[str, str]:
    pkg = _app_pkg_name(program)
    app_title = program.app.name if program.app else "NOVA App"
    has_auth = program.auth is not None and program.auth.enabled
    has_i18n = bool(program.translations) or any(
        f.multilingual for e in program.entities for f in e.fields
    )
    css_path = program.app.props.get("css") if program.app else None
    css_basename = css_path.rsplit("/", 1)[-1].rsplit("\\", 1)[-1] if css_path else None

    lines = [
        _HEADER,
        "from __future__ import annotations",
        "",
        "import os",
    ]
    if program.calendars:
        # Grille de mois calculée côté serveur avec la seule stdlib
        # (`calendar.Calendar.monthdatescalendar` + `datetime.date`) — pas
        # de dépendance JS supplémentaire pour le bloc `calendar`.
        lines.append("import calendar")
        lines.append("from datetime import date, timedelta")
    lines += [
        "",
        "import httpx",
        "import reflex as rx",
        "",
        'BACKEND_URL = os.environ.get("NOVA_BACKEND_URL", "http://localhost:8000")',
        "# URL du backend joignable DEPUIS LE NAVIGATEUR (aperçus d'image, liens de",
        "# téléchargement d'un champ `file`/`image`) — distincte de BACKEND_URL",
        "# ci-dessus (utilisée côté serveur, dans les gestionnaires de State) : en",
        "# Docker, BACKEND_URL vaut \"http://backend:8000\" (nom de service interne,",
        "# invisible du navigateur), d'où NOVA_PUBLIC_BACKEND_URL séparée.",
        'PUBLIC_BACKEND_URL = os.environ.get("NOVA_PUBLIC_BACKEND_URL", BACKEND_URL)',
        "",
        "",
    ]

    if program.pages or program.charts or program.calendars or has_auth or has_i18n:
        lines.append(_generate_navbar(program, has_auth, has_i18n))
        lines.append("")

    if has_i18n:
        lines.append(_generate_lang_state(program.active_languages()))
        lines.append("")
        translation_helpers = _generate_translation_helpers(program)
        if translation_helpers:
            lines.append(translation_helpers)

    if has_auth:
        lines.append(_generate_auth_state(program))
        lines.append("")
        lines.append(_generate_login_page())
        lines.append("")

    page_fns = []
    for page in program.pages:
        state_code, view_code = _generate_state_and_view(page, program, has_auth)
        lines.append(state_code)
        lines.append("")
        lines.append(view_code)
        lines.append("")
        page_fns.append((to_snake_case(page.name) + "_page", _page_route(page), page.name))

    for chart in program.charts:
        state_code, view_code = _generate_chart_state_and_view(chart, program, has_auth)
        lines.append(state_code)
        lines.append("")
        lines.append(view_code)
        lines.append("")
        page_fns.append((to_snake_case(chart.name) + "_chart_page", _chart_route(chart), chart.title or chart.name))

    for cal in program.calendars:
        state_code, view_code = _generate_calendar_state_and_view(cal, program, has_auth)
        lines.append(state_code)
        lines.append("")
        lines.append(view_code)
        lines.append("")
        page_fns.append((to_snake_case(cal.name) + "_calendar_page", _calendar_route(cal), cal.name))

    theme_kwargs = 'appearance="light", accent_color="violet", radius="large", scaling="100%"'
    app_kwargs = f"theme=rx.theme({theme_kwargs})"
    if css_basename:
        app_kwargs += f', stylesheets=["/{css_basename}"]'
    lines.append(f"app = rx.App({app_kwargs})")
    for fn_name, route, title in page_fns:
        lines.append(f'app.add_page({fn_name}, route="{route}", title="{title}")')
    if has_auth:
        lines.append('app.add_page(connexion_page, route="/connexion", title="Connexion")')
    if not page_fns and not has_auth:
        lines.append("")
        lines.append('@rx.page(route="/")')
        lines.append("def index() -> rx.Component:")
        lines.append(f'    return rx.center(rx.heading("{app_title}"))')

    lines += [
        "",
        "# Pages/composants hors DSL (validation avancée, UI sur mesure...) :",
        "# custom.py n'est jamais régénéré par `nova compile` (créé une seule",
        "# fois s'il n'existe pas déjà) — voir sa fonction register(app).",
        "try:",
        "    from . import custom as _custom",
        "except ImportError:",
        "    _custom = None",
        'if _custom is not None and hasattr(_custom, "register"):',
        "    _custom.register(app)",
    ]

    main_code = "\n".join(lines) + "\n"

    rxconfig = (
        _HEADER
        + "import reflex as rx\n\n"
        + f'config = rx.Config(\n    app_name="{pkg}",\n)\n'
    )

    files = {
        f"frontend/{pkg}/{pkg}.py": main_code,
        f"frontend/{pkg}/__init__.py": "",
        "frontend/rxconfig.py": rxconfig,
        "frontend/requirements.txt": "reflex>=0.5\nhttpx>=0.27\n",
    }
    if css_basename:
        # Feuille de style externe (`application { css: "..." }`) : le
        # *contenu réel* du fichier référencé est copié ici par
        # `codegen.generate_project` (qui connaît le dossier source du
        # .nova) — on réserve juste l'emplacement attendu par Reflex
        # (`assets/`, servi à la racine du site) avec un contenu par défaut
        # au cas où le fichier source ne serait pas trouvé.
        files[f"frontend/{pkg}/assets/{css_basename}"] = (
            "/* Remplacé par le contenu de la feuille de style référencée dans\n"
            f"   `application {{ css: \"{css_path}\" }}` si ce fichier a été trouvé au\n"
            "   moment de la compilation (voir nova_compiler.codegen.generate_project). */\n"
        )
    return files


_CUSTOM_FRONTEND_EXAMPLE = '''\
"""
Extensions frontend "custom" (frontend/<app>/custom.py).

Ce fichier n'est JAMAIS régénéré par `nova compile` : créé une seule fois,
puis laissé intact à chaque compilation suivante — contrairement au fichier
principal (<app>.py), entièrement régénéré à chaque fois.

C'est ici qu'ajouter tout ce que le DSL NOVA ne couvre pas encore : contrôles
de formulaire avancés (validation côté client), composants sur mesure,
pages hors du modèle table/formulaire/fiche, appels à des API tierces...

`register(app)` est appelé automatiquement par le fichier principal généré,
juste après la création de `app = rx.App(...)` : ajoutez-y vos propres
`app.add_page(...)`.
"""

from __future__ import annotations

import reflex as rx


def register(app: rx.App) -> None:
    """Point d'entrée appelé automatiquement au démarrage de l'application."""
    # Exemple : une page 100% custom, hors du DSL NOVA.
    #
    # def about_page() -> rx.Component:
    #     return rx.center(rx.heading("À propos"))
    #
    # app.add_page(about_page, route="/about", title="About")
    pass
'''


def generate_frontend_scaffold(program: NovaProgram) -> dict[str, str]:
    """Fichier d'extension "custom" : créé une seule fois si absent, jamais
    réécrit par une compilation suivante (contrairement à `generate_frontend`,
    dont le contenu est toujours régénéré)."""
    pkg = _app_pkg_name(program)
    return {f"frontend/{pkg}/custom.py": _CUSTOM_FRONTEND_EXAMPLE}
